### ISSUE TITLE
how insert data bank_method  transactions table ?

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#105]
In transactions(
payable_type,
payable_id,
wallet_id,
type,
amount,
confirmed,
meta,
uuid,
created_at,
updated_at
) table

 Then i added a  column name  bank_method

$user = User::first();
$user->balance; // int(0)
$user->deposit(10);

$bank_method ='VietComBank';

Now , i want insert  bank_method  into  $user->deposit(10,$bank_method);
 

how i can do that ? 

![Capture](https://user-images.githubusercontent.com/575720/65159585-8aaec000-da5e-11e9-8c03-d4049e375bf3.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 
Out of the box - no way. You need to inherit from the wallet model and add your parameters.
If you do not know how to do this, I can make an example tomorrow.

I would not advise you to add your fields and overload models. In the future, you will not be able to easily update the library.

I recommend working with a json `meta` type field.
```php
$user->deposit(100, ['bank_method' => 'VietComBank']);
```

By json field you can filter and work with it.
https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html

**Comment by khanhnam99** [comment]
thanks

**Comment by rez1dent3** [comment]
@khanhnam99 
And here is an example with an extension, as promised
https://github.com/bavix/laravel-wallet/blob/master/tests/WalletExtensionTest.php#L36

**Comment by rez1dent3** [comment]
@khanhnam99 Still have more questions?

**Comment by rez1dent3** [comment]
So there are no questions. I close the issue.
