### ISSUE TITLE
Product price based on customer attributes

### ISSUE THREAD

**Issue by jlstandout** [bavix/laravel-wallet#117]
Hey guys.

Is it possible to generate product price based on customer attributes? I mean in `Bavix\Wallet\Interfaces\Product`  method `canBuy` there is customer variable available, but I need this variable in `getAmountProduct` as well so I can calculate price for specific user. Is it possible to do without package modification?

Thanks in advance

**Comment by rez1dent3** [comment]
@jlstandout There is no possibility at the moment. 
There was an attempt to do this, but then there were difficulties in implementation.
I'll try again on the weekend. If you manage to implement it, it will go to version 4.0.
Now 4.0 is in beta testing.

**Comment by rez1dent3** [comment]
If there is a beautiful implementation on your part, then I will once again accept PR from you.

**Comment by rez1dent3** [comment]
@jlstandout 
The `getAmountProduct` method cannot pass the parameter, I decided to act differently. An interface is added with the calculation of a personal discount on the product.
The development can be observed in the PR #119

**Comment by rez1dent3** [comment]
@jlstandout I defeated the getAmountProduct method and now I need to send the Wallet / Payer there. Wait in version 4.0

**Comment by jlstandout** [comment]
Great news. How can I switch to Version 4.0 to try it out? Tried to switch to `dev-discount` but received error `Target [Bavix\Wallet\Interfaces\Storable] is not instantiable.`

**Comment by rez1dent3** [comment]
Better wait for the release. It will be held next week.

You have an error because you need to update the configuration file:
https://github.com/bavix/laravel-wallet/blob/master/config/config.php#L25

Add row
```php
        'storable' => Bavix\Wallet\Simple\Store::class,
```

**Comment by jlstandout** [comment]
Perfect. Thanks a lot. Will wait for release :)

**Comment by rez1dent3** [comment]
@jlstandout Updated the package, see version 4.0.0.
If you have questions, write.
