### ISSUE TITLE
Uuid wallets

### ISSUE THREAD

**Issue by MarlonRaphael** [bavix/laravel-wallet#122]
Olá, estou tentando criar modelos estendendo Bavix\Wallet\Models\Wallet para utilizar UUID's no lugar de ID's inteiros convencionais, porém, não estou conseguindo, há como fazer isto de alguma forma?

**Comment by rez1dent3** [comment]
@MarlonRaphael Hello. At the moment, this is not possible. Through inheritance, it is necessary to redefine all models and write new migrations.

**Comment by rez1dent3** [comment]
It took me a very long time to nurture the idea of including UUIDs in a project, but it's all too complicated. There is no solution yet.
