### ISSUE TITLE
[Transaction] Float balance

### ISSUE THREAD

**Issue by zKoz210** [bavix/laravel-wallet#123]
How get float amount if user wallet balance float?

**Comment by saad3074** [comment]
@zKoz210 you can use **$user->wallet->balanceFloat** or **$user->balanceFloat** will return you a float wallet balance

**Comment by saad3074** [comment]
@zKoz210 I am using this **sprintf("%.2f", $item->amount / 100)** in Transactions

**Comment by rez1dent3** [comment]
@zKoz210 
No way to get it. Everything is stored in integer. 
You will have to write your formatter or override the model and add the appropriate methods.

@saad3074 Thanks for the answer. That's right.

**Comment by rez1dent3** [comment]
I close the issue, there are questions - create a new one.

**Comment by yawaRcan** [comment]
number_format( $transaction->amountfloat,2)
