### ISSUE TITLE
get deposit and withdraw date 

### ISSUE THREAD

**Issue by Zero-jano** [bavix/laravel-wallet#126]
Hi 
Thank you for your tool , and i want to ask you how can get time and date from table wallet about deposit amount and withdraw amount to can make report in user profile show what date and time deposit or withdraw money ?

**Comment by rez1dent3** [comment]
Hello. Yes. The columns of updating and creation exist.

https://github.com/bavix/laravel-wallet/blob/master/database/migrations_v1/2018_11_06_222923_create_transactions_table.php#L28

**Comment by Zero-jano** [comment]
thank you for replay , and how can get for each user because i don't see any relationship between two tables  user and wallet to can get date for deposit or withdraw

**Comment by saad3074** [comment]
@Zero-jano  you can get all transactions from transaction table by 
**$user->transactions()** or **Auth::user()->transactions** which return all transactions data with date.

**Comment by Zero-jano** [comment]
yes i know that but i need determined what exactly withdraw for this item for ex: i need pay product from my wallet after pay approve display how date this payment , i see table uuid how can use it for determined this transfer .

**Comment by rez1dent3** [comment]
If I understand you correctly, then this data is enough for you.
```php
$wallet = $user->wallet;
foreach ($wallet->transactions as $transaction) {
    var_dump($transaction->type, $transaction->uuid, $transaction->updated_at);
}
```

**Comment by Zero-jano** [comment]
Thank you
