### ISSUE TITLE
Competing requests

### ISSUE THREAD

**Issue by Laxilef** [bavix/laravel-wallet#127]
Hello!
I see in the code that cache () -> lock is used to avoid the consequences of competing requests. What is the reason for this? Why can't I use 'shared lock' or 'lock for update'?

And I can’t understand why 'store' is used (with redis). Explain, please.

---rus
Здравствуйте!
В коде вижу, что во избежании последствий конкурирующих запросов используется cache()->lock. Чем это обусловлено? Почему нельзя использовать 'shared lock' или 'lock for update'?

И не могу понять, зачем используется 'store' (с redis). Объясните, пожалуйста.

**Comment by Laxilef** [comment]
Например, возникает такая ситуация: есть 2 одновременных запроса на выполнение одного действия - пополнение баланса на 10$, оба запроса сначала получают модель wallet с балансом, предположим, 20$.
Оба запроса пытаются увеличить баланс модели на 10$, кто быстрее - ставит условную блокировку, увеличивает баланс до 30$ и сохраняет модель.
Следующий же запрос оперирует с загруженными данными модели, где баланс еще 20$, аналогично увеличивает баланс до 30$ и сохраняет модель.
Таким образом мы получаем баланс 30$ вместо 40$.

Если все так, то логично было бы внутри closure перед получением актуального баланса делать $wallet->lockForUpdate()->refresh(), а потом уже брать $wallet->balance, производить какие-то действия и сохранять модель.

**Comment by rez1dent3** [comment]
Привет, @Laxilef.
Это было сделано из-за функционала "корзина" (Cart). Так же основная задача была -- избавится от лишних запросов в базу данных (для получения баланса для каждой операции). Shared Lock -- это хорошо, но в данном случае не получилось у меня реализовать с поддержкой всего функционала библиотеки и минимальным кол-вом запросов в базу. Сейчас на боевом сервере (база мастер, не слев) QPS ~7000 и мне необходимо было не увеличивать это значение. 

![image](https://user-images.githubusercontent.com/5111255/69781107-30e51780-11be-11ea-847c-254edff77a4d.png)

![image](https://user-images.githubusercontent.com/5111255/69781030-f7141100-11bd-11ea-9d64-82b0f0092fae.png)

Lock через редис сделал и через некоторое время, буквально через недели 3, получил много новых конкурирующих запросов. Тогда решил, что баланс необходимо хранить в redis. Так появилось расширение `bavix/laravel-wallet-vacuum`. В данный момент, проблем с конкурирующими запросами на бою нет. 

Спасибо за обратную связь. 
Если у вас есть идеи -- реализуйте их и отправьте PR.  

ЗЫ,
Лучшим решением было бы не править код библиотеки, а написать функционал унаследовав часть классов и расширив их (так сделаны `laravel-wallet-vacuum` и `laravel-wallet-swap`). Многим пользователям нет необходимости в борьбе с race condition, а добавлять пару запросов в базу -- не всегда лучший вариант.

**Comment by Laxilef** [comment]
@rez1dent3, благодарю за ответ!
