### ISSUE TITLE
Encountered error: "You are not the owner of the wallet"

### ISSUE THREAD

**Issue by arjayosma** [bavix/laravel-wallet#129]
While I was testing our application, we noticed that the CanConfirm#forceConfirm method is throwing an error when it compares the wallet ID and the transaction's wallet ID.

Debugging the issue, we found out that the library is returning a string for the wallet ID.

Should the Transaction#wallet_id be cast to int?
Or, is this a database issue or perhaps configuration issue?

In the meantime, we manually updated the code inside the vendor folder. (This is not a good fix - but it worked :) )
The changes we made are the following:

> src/Models/Transaction.php

```
$casts = [
   ...,
   'wallet_id' => 'int'
];
```

Hoping to get a response.

**Comment by rez1dent3** [comment]
Hello. Thanks. I can make changes on Monday-Tuesday.  If you do PR - it will be faster

**Comment by rez1dent3** [comment]
@arjayosma there was a time, fixed. Today I will release

**Comment by arjayosma** [comment]
@rez1dent3 thanks! I forked before I submitted the issue. Thanks for the quick fix! You are awesome!

**Comment by rez1dent3** [comment]
@arjayosma tag 4.0.1

**Comment by arjayosma** [comment]
Awesome! Thank you!
