### ISSUE TITLE
Collisions when using many traits

### ISSUE THREAD

**Issue by Loafer19** [bavix/laravel-wallet#132]
When I use this traits - 

![image](https://user-images.githubusercontent.com/45109375/71448081-c6cd7d00-273f-11ea-866a-521b452f0b2f.png)

I have a problem - 

![image](https://user-images.githubusercontent.com/45109375/71448094-fe3c2980-273f-11ea-9980-5c7b09c6a742.png)

Please check

**Comment by rez1dent3** [comment]
Hello, @Loafer19 

![Screenshot from 2019-12-26 00-23-24](https://user-images.githubusercontent.com/5111255/71450612-09aa4780-2776-11ea-8aa3-51829d17eb24.png)

Replace `CanPay` and `HasWalletFloat` with `CanPayFloat` and you will be happy. https://github.com/bavix/laravel-wallet/blob/master/src/Traits/CanPayFloat.php#L7

**Comment by Loafer19** [comment]
before creating this issue, I had to review the previous issues, found almost the same - https://github.com/bavix/laravel-wallet/issues/99

CanPayFloat - I didn't know there was such a trait, I had to look at -

![image](https://user-images.githubusercontent.com/45109375/71451026-4ece7980-2776-11ea-8aec-5331e05b0edc.png)

and I think the issue can be closed)

so thank you very much))
