### ISSUE TITLE
Withdraw confirmed state for balance

### ISSUE THREAD

**Issue by krutyosila** [bavix/laravel-wallet#134]
Hello
How can I do withdraw with minus balance status.

example;
User balance = 100
withdraw(50, null, false);
User balance = 50 ??

**Comment by rez1dent3** [comment]
Hey. The question is not clear to me.
If you are working with an unconfirmed transaction, then it will not be taken into account in the translation of the balance.

I added a unit test for your peace of mind.
![image](https://user-images.githubusercontent.com/5111255/72237102-6ae17000-35ea-11ea-9c5b-19dbba326a0e.png)

**Comment by krutyosila** [comment]
I need get users balance with unconfimed transactions. If users can unconfirmed withdraw, users can see   balance with unconfirmed transactions.

for example;
user balance is 1000
user did withdraw 250 but withdraw is not confirmed
now I want to print user balance, user balance is 1000. It's not valid for me. I want to see user's balance is 750.
$user->balance = 1000;
$user->withdraw(250, ['desc'=>'description'], false);
$user->balance; // it is 1000 ,  I want to see it to 750

**Comment by rez1dent3** [comment]
@krutyosila  Will not work. If the transaction is not confirmed, then it will not be taken into account in calculating the balance.
