### ISSUE TITLE
How can I refund for withdraw

### ISSUE THREAD

**Issue by krutyosila** [bavix/laravel-wallet#135]
I can't use items for any transactions. I use only withdraw and deposit.

$user->withdraw(100, ['state'=>'wait'],1);

state change from admin. If admin cancelled this trascation,  how can I refund this transaction?

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/blob/master/src/Traits/CanConfirm.php

Make a similar trait for your goals.

1. Cancel the transaction (update ... set confirmed=0 )
2. Recalculate the balance
