### ISSUE TITLE
Transaction: `amountFloat`

### ISSUE THREAD

**Issue by go24dev** [bavix/laravel-wallet#136]
Are there any clean way to get the `amount` of transaction in float?

**Comment by rez1dent3** [comment]
@go24dev There is no such opportunity

**Comment by allcaretravels** [comment]
@rez1dent3 thank for your response.

**Comment by rez1dent3** [comment]
@go24dev added, see tag 4.1.2

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/compare/4.1.1...4.1.2
