### ISSUE TITLE
How to deduct the transaction fees from the sender account with Bavix ???

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#138]
Hello.

 How to deduct the transaction costs from the sender account with Bavix ???

 What I'm looking for is how to use Bavix to deduct the transaction "**fees**" from the customer account balance ???

**Comment by rez1dent3** [comment]
@chegmarco1989 hello.
There is a possibility. You can specify a percentage, or you can specify a minimum threshold. You can use both options.

See: https://bavix.github.io/laravel-wallet/#/taxing

**Comment by chegmarco1989** [comment]
OK. Thank you
