### ISSUE TITLE
Suggestion: use specialized package to handle financials transactions 

### ISSUE THREAD

**Issue by damms005** [bavix/laravel-wallet#139]
Mathematical manipulation of money (adding, subtracting etc.) can be very tricky (floating point precision, etc.).

For the reason above, there is a package designed specifically for this purpose. I suggest you consider using it: https://github.com/akaunting/money

Thanks

**Comment by rez1dent3** [comment]
@damms005 
Hey. I saw this library. This is a very good package for working with currency. I am of the opinion that wallet is something universal. I do not get attached to the currency - this is done by the developer. The library does not say "I only work with the dollar, the ruble and the larry", and the developer decides what he needs.
Thanks you.

**Comment by damms005** [comment]
@rez1dent3 You are very correct about that. I was curious that such a package may be advantageous over [direct money manipulations like this](https://github.com/bavix/laravel-wallet/blob/e6d4b8a7e65f12752bba4a46adcf665cfff7cb16/src/Simple/Store.php#L34).

...or maybe not `\_(0)_/`

**Comment by rez1dent3** [comment]
@damms005 Thank you! I will add gmp (GNU Multiple Precision) support for adding large numbers, a bit later.

**Comment by rez1dent3** [comment]
@damms005 Choosing between gmp and bcmath - chose bcmath. The next major version of the library will support arbitrary precision calculations.

You can follow the development [here](https://github.com/bavix/laravel-wallet/issues/146) and [here](https://github.com/bavix/laravel-wallet/pull/140).

**Comment by rez1dent3** [comment]
@damms005 see tag 5.0.0
