### ISSUE TITLE
Transfer's transaction relation

### ISSUE THREAD

**Issue by lumore** [bavix/laravel-wallet#142]
Hi, thanks for the great package!

I'm trying it out and I want to display a history of transfers for user. So, the problem is here, that Transfer model doesn't persist `amount` and other fields of transaction.

As I understood, `Transfer` has two fields that refers to `Transaction` model, and also creates `Transaction` for each user. User1 refers to `withdraw_id` and User2 refers to `deposit_id`.

How do I get amount, confirmation status and meta data for `Transfer`?

**Comment by rez1dent3** [comment]
@lumore Hello. Unfortunately, transaction data is not available in Transfer. But you can get them from the withdraw, deposit link.

```
$transfer = $first->transfer($last, 5);
var_dump($transfer->deposit->amount); // 5
var_dump($transfer->withdraw->amount); // -5
```

PS,
I would not recommend working with a Transfer table for a story. Use Transaction.
