### ISSUE TITLE
Large Numbers

### ISSUE THREAD

**Issue by DeveloperOnCall** [bavix/laravel-wallet#146]

**Comment by rez1dent3** [comment]
@DeveloperOnCall 
Hey. The library uses strong php typing. Unfortunately, the language is not intended for arbitrary precision computing. You need to look towards bcmath, gmp and develop your own solution.

I work towards [large numbers](https://github.com/bavix/laravel-wallet/pull/140), but when it will be - no one knows.

**Comment by DeveloperOnCall** [comment]
@rez1dent3 

Thanks for getting back to me - if you can offer some direction, I can put one of our in-house developers on it for you - get that one off your development list. Seems we have to do it for our needs, might as well contribute to this package in the meantime.

D

**Comment by rez1dent3** [comment]
@DeveloperOnCall 
Install bcmath and version 5.0.x laravel-wallet. In this version, support for accurate arithmetic will be added.

Here is a unit test:
https://github.com/bavix/laravel-wallet/blob/develop/tests/WalletFloatTest.php#L310

How to install?
```bash
composer req bavix/laravel-wallet:5.0.x-dev
```

**Comment by rez1dent3** [comment]
@DeveloperOnCall see tag 5.0.0
