### ISSUE TITLE
Error when try make depositFloat

### ISSUE THREAD

**Issue by fatnaydev** [bavix/laravel-wallet#147]
Hi.

In the last week when try register depositFloat has next error:
![image](https://user-images.githubusercontent.com/60872894/76646277-4f2e1380-6520-11ea-842c-e95eabbe64b9.png)

I send an Wallet model
![image](https://user-images.githubusercontent.com/60872894/76646212-345b9f00-6520-11ea-8cea-ceb2056e1d14.png)

I debug directly but "($this instanceof WalletModel ? $this->holder : $this)" return null, when make inverse "($this instanceof WalletModel ? $this : $this->holder)" works fine and register deposit, how do to work fine??
![image](https://user-images.githubusercontent.com/60872894/76646083-f1013080-651f-11ea-934c-b04492de7caa.png)

This is my code:
Verify hasWallet and it's correct, then save $wallet and try to make depositFloat
![image](https://user-images.githubusercontent.com/60872894/76646453-9b795380-6520-11ea-9be6-460a25a63e81.png)

Model Customer has Wallet and HasWallets to have multiple wallets and user WalletFloat
![image](https://user-images.githubusercontent.com/60872894/76646623-e6936680-6520-11ea-8efd-ea40e9571d8f.png)

**Comment by rez1dent3** [comment]
@fatnaydev Hello. I don’t have enough data. Need an example code.

**Comment by fatnaydev** [comment]
> @fatnaydev Hello. I don’t have enough data. Need an example code.

Updated with model and code

**Comment by fatnaydev** [comment]
The problem is the same when createWallet and then try to forceWithdrawFloat

![image](https://user-images.githubusercontent.com/60872894/76648099-a2ee2c00-6523-11ea-8ab8-6e468c93a314.png)

**Comment by rez1dent3** [comment]
@fatnaydev 
This problem does not reproduce.

![Screenshot from 2020-03-13 21-31-58](https://user-images.githubusercontent.com/5111255/76649610-1e76ca00-6572-11ea-84c3-88cff0ac12d0.png)

![Screenshot from 2020-03-13 21-33-29](https://user-images.githubusercontent.com/5111255/76649728-5120c280-6572-11ea-9e7c-7fa270abfefc.png)

**Comment by fatnaydev** [comment]
the strange thing that the system was working well and this week I mark the error but nothing has been moved to the code

> @fatnaydev
> This problem does not reproduce.

**Comment by rez1dent3** [comment]
@fatnaydev 
Please tell me which version of laravel you have installed?
What version of library (laravel-wallet) are you using?

Depending on the version, see the changes: 
https://github.com/bavix/laravel-wallet/compare/4.1.2...4.2.0
https://github.com/bavix/laravel-wallet/compare/4.2.0...5.0.0

**Comment by fatnaydev** [comment]
Laravel 6
Before error 4.2 and then update 5 to view the error gone but not

Another error appear
In server show but in my local not
![image](https://user-images.githubusercontent.com/60872894/76651781-d1bbd080-652a-11ea-8708-651e7f7410d2.png)

Model Customer are the same
![image](https://user-images.githubusercontent.com/60872894/76651828-e8622780-652a-11ea-8086-724dd71cbc29.png)


> @fatnaydev
> Please tell me which version of laravel you have installed?
> What version of library (laravel-wallet) are you using?
> 
> Depending on the version, see the changes:
> [4.1.2...4.2.0](https://github.com/bavix/laravel-wallet/compare/4.1.2...4.2.0)
> [4.2.0...5.0.0](https://github.com/bavix/laravel-wallet/compare/4.2.0...5.0.0)

**Comment by rez1dent3** [comment]
@fatnaydev Use one trait: `HasWallet` or `HasWaleltFloat`.

**Comment by fatnaydev** [comment]
> @fatnaydev Use one trait: `HasWallet` or `HasWaleltFloat`.

Thanks, can share me the file test to run it un my local to test it please

**Comment by rez1dent3** [comment]
@fatnaydev 
Unit tests are shared: https://github.com/bavix/laravel-wallet/tree/units/tests

And here is the unit test that I showed: https://github.com/bavix/laravel-wallet/blob/units/tests/MultiWalletTest.php#L93

**Comment by rez1dent3** [comment]
```bash
git clone https://github.com/bavix/laravel-wallet.git
cd laravel-wallet
composer install
./vendor/bin/phpunit
```

**Comment by fatnaydev** [comment]
I find the problem, I have 2 models Customer and Prospect, the 2 models use the same table 'customers' the difference is 1 boolean field 'prospect' true is customer and false are prospect, in each model have an global scope to return respective registers using boolean 'prospect' field and the relation holder of model Wallet when is prospect not found it, how do to add a 'withoutGlobalScopes' into holder relation??

Customer
![image](https://user-images.githubusercontent.com/60872894/76670429-1f99fe00-6556-11ea-8f96-3fc7ae27a59d.png)

Prospect
![image](https://user-images.githubusercontent.com/60872894/76670465-36405500-6556-11ea-90cf-8e3df2172d6a.png)

the morph relation but use customer the global scope return null because that customer is prospect
![image](https://user-images.githubusercontent.com/60872894/76670484-53752380-6556-11ea-86a4-1450be21a963.png)


> ```shell
> git clone -b units https://github.com/bavix/laravel-wallet.git
> cd laravel-wallet
> composer install
> ./vendor/bin/phpunit
> ```

**Comment by fatnaydev** [comment]
Yeap!

The solution are make model and config into config/wallet.php

![image](https://user-images.githubusercontent.com/60872894/76670615-2b39f480-6557-11ea-9be0-27e11c003d2f.png)

**Comment by rez1dent3** [comment]
@fatnaydev You correctly redefined the model.
Thanks for information. I will know for the future.
