### ISSUE TITLE
not working for float value 0.09699977 in Bitcoin 

### ISSUE THREAD

**Issue by ucanbehack** [bavix/laravel-wallet#149]
I'm trying to use a [wallet](url) for bitcoin but it is not supporting coins in float if I have balance in the wallet 
0.09699977

 it returns balance 0

          ```
                $balance =$user->balanceFloat; 
                var_dump($balance);    // float(0)
                var_dump($item->to_pay);   //float(0.09699977)
```

![Screenshot 2020-03-17 at 8 46 59 AM]((https://user-images.githubusercontent.com/28224590/76818547-e13d6100-682b-11ea-99c8-2ae35525ec84.png))

**Comment by rez1dent3** [comment]
@ucanbehack hello.
1. Verify that you have bcmath installed.
2. Verify that the BCMath package in the config really works for you.
https://github.com/bavix/laravel-wallet/blob/master/config/config.php#L37

Here is a usage example (unit test):
https://github.com/bavix/laravel-wallet/blob/master/tests/WalletFloatTest.php#L319

**Comment by rez1dent3** [comment]
To make it easier to believe, I added your case to unit tests. 
https://github.com/bavix/laravel-wallet/commit/f7664dea00c07549635f1890439aebd6f4d817a2

**Comment by ucanbehack** [comment]
when I'm trying 
`dd($user->WithdrawFloat(0.0970934));`
this transaction  it is creating entery 
**-10.000000000000**

but it should be **0.0970934**

**Comment by ucanbehack** [comment]
![Screenshot 2020-03-17 at 4 05 10 PM](https://user-images.githubusercontent.com/28224590/76848174-3a77b580-6869-11ea-826e-c161e349a2cc.png)
![Screenshot 2020-03-17 at 4 05 26 PM](https://user-images.githubusercontent.com/28224590/76848180-3d72a600-6869-11ea-9917-d85c5f91d315.png)
![Screenshot 2020-03-17 at 4 05 49 PM](https://user-images.githubusercontent.com/28224590/76848182-3ea3d300-6869-11ea-9325-14858ae4060b.png)

**Comment by rez1dent3** [comment]
@ucanbehack 
1. field balance and amount must be int
2. Set the value of `decimal_places` for the wallet to 8 

here is an example:
```php
$user->depositFloat(0.0970934);
var_dump($user->balance); // int(9709340)
var_dump($user->balanceFloat); // float(0.09709340)
```

The wallet will store an int value equal to 9709340

**Comment by rez1dent3** [comment]
@ucanbehack You should also make sure that you are working with the latest version of laravel-wallet.

**Comment by ucanbehack** [comment]
I have checked and updated 5.0 but still issue please check 
![Screenshot 2020-03-17 at 7 14 38 PM](https://user-images.githubusercontent.com/28224590/76862878-bfbc9380-6884-11ea-9202-ef202b99c3a3.png)
![Screenshot 2020-03-17 at 7 14 52 PM](https://user-images.githubusercontent.com/28224590/76862882-c2b78400-6884-11ea-95c3-308e6498faa3.png)
![Screenshot 2020-03-17 at 7 15 08 PM](https://user-images.githubusercontent.com/28224590/76862889-c4814780-6884-11ea-9d60-98f94c3df158.png)
![Screenshot 2020-03-17 at 7 21 23 PM](https://user-images.githubusercontent.com/28224590/76862893-c519de00-6884-11ea-8974-48c90492dd61.png)
![Screenshot 2020-03-17 at 7 21 40 PM](https://user-images.githubusercontent.com/28224590/76862898-c5b27480-6884-11ea-83df-4f7a8f0f7602.png)
![Screenshot 2020-03-17 at 7 22 15 PM](https://user-images.githubusercontent.com/28224590/76862905-c6e3a180-6884-11ea-95ac-8d546c843fa4.png)
![Screenshot 2020-03-17 at 7 22 35 PM](https://user-images.githubusercontent.com/28224590/76862911-c77c3800-6884-11ea-9218-b843caeff0d6.png)

**Comment by rez1dent3** [comment]
@ucanbehack That's right. The library stores integer amounts. Do not use decimal. Use enough int(36).

**Comment by ucanbehack** [comment]
![Screenshot 2020-03-17 at 9 32 32 PM](https://user-images.githubusercontent.com/28224590/76875624-d2d85f00-6896-11ea-8324-a74e46d0d1cb.png)
![Screenshot 2020-03-17 at 9 32 16 PM](https://user-images.githubusercontent.com/28224590/76875648-d9ff6d00-6896-11ea-9483-fc40fef834bd.png)

**Comment by ucanbehack** [comment]
I have tried many times but it is not saving actual value that I need it is changing

**Comment by rez1dent3** [comment]
@ucanbehack 
I already wrote to you above, the library works with integer numbers. Will not work with float in php - this was done intentionally in connection with the mantissa (numerical methods). Here is a striking example:
```
0.1 + 0.2 = 0.30000000000000004
```

Using integer math, I avoid such a problem.

`decimal_places` - the number of mantissa characters.
Those if `decimal_places` is 2, then in `balanceFloat` is 1 with a `balance` of 100.

If you need to store in a float, then you have to develop your own solution.

**Comment by rez1dent3** [comment]
@ucanbehack 
I close the issue. If you have questions, then open a new issue. thanks
