### ISSUE TITLE
wallet:refresh error

### ISSUE THREAD

**Issue by chartalex** [bavix/laravel-wallet#150]
When I execute: `php artisan wallet:refresh `

I get this error:

`Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'balance' in field list is ambiguous (SQL: update `wallets` left join (select `wallet_id`, sum(amount) balance from `transactions` where `confirmed` = 1 group by `wallet_id`) as `b` on `wallets`.`id` = `b`.`wallet_id` set `balance` = b.balance)`

Don't know if there is a relation, but I also have this error for refunds:

`Call to a member function morphMany() on null`

Everything else works perfectly (deposit,withdraw,pay,balance)

Any idea?

version 4.1 - laravel 5.8

**Comment by rez1dent3** [comment]
@chartalex Hello. Tell me which database is used? And the database version.

**Comment by rez1dent3** [comment]
@chartalex 
Try to edit the line
src/Commands/RefreshBalance.php:91
```php
            ->update(["$wallet.balance" => app(DbService::class)->raw('b.balance')]);
```

If it works, I’ll add to the project

**Comment by chartalex** [comment]
> @chartalex Hello. Tell me which database is used? And the database version.

@rez1dent3 Hello and thanks for your quick reply :)

MySQL 5.7.11

**Comment by chartalex** [comment]
No, it doesn't work. I get this:
`"SQLSTATE[42S22]: Column not found: 1054 Unknown column '$wallet.balance' in 'field list'"`

**Comment by rez1dent3** [comment]
> @rez1dent3 No, it doesn't work. I get this:
> `"SQLSTATE[42S22]: Column not found: 1054 Unknown column '$wallet.balance' in 'field list'"`

using double quotes.
```php
"$wallet.balance"
```

**Comment by chartalex** [comment]
Integrity constraint violation: 1048 Column 'balance' cannot be null (SQL: update `wallets` left join (select `wallet_id`, sum(amount) balance from `transactions` where `confirmed` = 1 group by `wallet_id`) as `b` on `wallets`.`id` = `b`.`wallet_id` set `wallets`.`balance` = b.balance)

**Comment by rez1dent3** [comment]
@chartalex see tag 4.2.1

**Comment by rez1dent3** [comment]
@chartalex Let me know if the patch helped you

**Comment by chartalex** [comment]
@rez1dent3 I need to upgrade from laravel 5.8 to 6.0 to check it :(

`bavix/laravel-wallet 4.2.1 requires illuminate/database ^6.0|^7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev],`

**Comment by rez1dent3** [comment]
@chartalex then fix it with your hands: https://github.com/bavix/laravel-wallet/issues/150#issuecomment-601376317

**Comment by rez1dent3** [comment]
@chartalex 
I thought well and decided to release a patch for older versions. Tag 4.1.3

**Comment by chartalex** [comment]
@rez1dent3 Thank you so much!
