### ISSUE TITLE
Call to a member function morphMany() on null

### ISSUE THREAD

**Issue by chartalex** [bavix/laravel-wallet#154]
I get an issue with all my refunds.
Everything else works perfectly (deposit,withdraw,pay,balance)
Any idea?

in `vendor/bavix/laravel-wallet/src/Traits/HasWallet.php`

line 88:
```
    /**
     * all user actions on wallets will be in this method
     *
     * @return MorphMany
     */
    public function transactions(): MorphMany
    {
        return ($this instanceof WalletModel ? $this->holder : $this)
            ->morphMany(config('wallet.transaction.model', Transaction::class), 'payable');
    }
```

version 4.1.3 - laravel 5.8

**Comment by rez1dent3** [comment]
@chartalex hello.
Not so long ago, another user of the library had such a problem. I decided not in an obvious way, maybe it suits you.
https://github.com/bavix/laravel-wallet/issues/147#issuecomment-598980961

**Comment by chartalex** [comment]
@rez1dent3 Indeed, it fixes my problem :) Thanks !
