### ISSUE TITLE
Make payments confirmuble

### ISSUE THREAD

**Issue by MickeyUr** [bavix/laravel-wallet#156]
Is a way exist to make payment confirmuble ? 
What I want: after user pay for item, freeze his money before admin confirm or declane payment.
I see that CanPay trait use CartPay and CartPay create transfer, but as I can see confirmuble can be only transactions. It would be great if you could give the cue in what direction I must look

**Comment by rez1dent3** [comment]
@MickeyUr Hey. There is no confirmation in payments and is not currently planned. Here you have to reinvent your bike.

**Comment by schrapel** [comment]
@MickeyUr You could create a wallet that you use as an escrow. Make a transfer to the escrow wallet, then when you confirm transfer to the original destination or decline and return to the original user.

**Comment by rez1dent3** [comment]
@schrapel Yes you are right. There are many options for implementation, and all are true, it depends only on the task.
