### ISSUE TITLE
Deposit from ?

### ISSUE THREAD

**Issue by cpy466** [bavix/laravel-wallet#164]
Thanks for this great package. Please help me with this issue:

 $user1 made a transfer to $user2. How to I get to see in Auth::user()->transactions table from whom(witch user) it came the deposit ? 

Thank you

**Comment by rez1dent3** [comment]
@cpy466 
Hey. No, it must be developed on your side.
The transfer is carried out from wallet to wallet. In fact, when you do transfer:
```php
$user1->transfer($user2, 1000)
```

The library brings the code to this option:
```php
$user1->wallet->transfer($user2->wallet, 1000)
```

The library does not know anything about your users and your wallets.
There is no magic in this ;)

Not so long ago, another user shared his solution to this problem. You can take a look at this
https://github.com/bavix/laravel-wallet/issues/162#issuecomment-606458346

**Comment by cpy466** [comment]
@rez1dent3 
Ok got it. Thanks alot
