### ISSUE TITLE
All purchased items of a user

### ISSUE THREAD

**Issue by upcoders** [bavix/laravel-wallet#166]
Hi, How can I get all purchased items by specific user?
I use following code,
    `DB::table('transactions')->where([['payable_id', '=', $user->id], ['type', 'withdraw']])`

Is it the only way or better solutions exist?

Thanks

**Comment by rez1dent3** [comment]
@upcoders hello! 
Purchased is listed on a specific wallet, and not on the user.
Replace the user ID with the wallet ID in the request.
```php
DB::table('transactions')->where([['payable_id', '=', $user->wallet->id], ['type', 'withdraw']])
```
