### ISSUE TITLE
Table Structure Clarification

### ISSUE THREAD

**Issue by abishekrsrikaanth** [bavix/laravel-wallet#167]
What is the significance of the `payable` morph column on the transactions table when the `wallet_id` is on the `transactions` table and the `wallets` table has the `holder` morph relation?

Also where exactly is the code that creates a wallet for a model if it doesn't exist?

**Comment by rez1dent3** [comment]
@abishekrsrikaanth hello.

> What is the significance of the payable morph column on the transactions table when the wallet_id is on the transactions table and the wallets table has the holder morph relation?

https://github.com/bavix/laravel-wallet/blob/9480f0d23db40e2afb704044656892e3ceea7a7c/tests/DiscountTaxTest.php#L57-L64

> Also where exactly is the code that creates a wallet for a model if it doesn't exist?

https://github.com/bavix/laravel-wallet/blob/9480f0d23db40e2afb704044656892e3ceea7a7c/src/Services/WalletService.php#L123-L125

**Comment by abishekrsrikaanth** [comment]
Thanks for the answers, the second answer is clear, am still not sure about the first one. Could you clarify?

**Comment by rez1dent3** [comment]
@abishekrsrikaanth 

>  the wallets table has the `holder` morph relation?

This is the owner of the wallet.

> What is the significance of the `payable` morph column on the transactions table when the `wallet_id` is on the transactions ..

The field `payable` is necessary for the operation of the purchase methods. For a product, the field will look at the product, for the user to the user.

> ...the transactions table when the `wallet_id` is on the transactions

Since multi-wallets are supported, you need to understand where to return the money.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - open or create a new one.
