### ISSUE TITLE
How to get user perticular wallet transactions history

### ISSUE THREAD

**Issue by cheran2017** [bavix/laravel-wallet#168]
For examples if user have credit wallet bonus wallet ..i want to fetch only bonus wallet transactions ..How to do it

**Comment by rez1dent3** [comment]
@cheran2017 
```php
$user->transactions()->where('wallet_id', $bonusWallet->getKey())
```

This approach is already used in the project. In the wallet balance calculation method.

https://github.com/bavix/laravel-wallet/blob/9480f0d23db40e2afb704044656892e3ceea7a7c/src/Models/Wallet.php#L115-L116

**Comment by cheran2017** [comment]
Thanks i got but i cant able to insert deposite values in amount column like 0.5 value

**Comment by cheran2017** [comment]
I want deposit 0.5 or any point values how can i change it ?please help me

**Comment by rez1dent3** [comment]
Answered here https://github.com/bavix/laravel-wallet/issues/169#issuecomment-626321901
