### ISSUE TITLE
I want deposit 0.5 or any point values how can i change it ?please help me

### ISSUE THREAD

**Issue by cheran2017** [bavix/laravel-wallet#169]
if i deposit 0.5 it saved as round value like 1

**Comment by rez1dent3** [comment]
@cheran2017 Hello. Like that...
https://github.com/bavix/laravel-wallet/blob/9480f0d23db40e2afb704044656892e3ceea7a7c/tests/WalletFloatTest.php#L24-L26

**Comment by cheran2017** [comment]
> @cheran2017 Hello. Like that...
> https://github.com/bavix/laravel-wallet/blob/9480f0d23db40e2afb704044656892e3ceea7a7c/tests/WalletFloatTest.php#L24-L26

It's not working

**Comment by cheran2017** [comment]
$u->depositFloat(0.1)
=> Bavix\Wallet\Models\Transaction {#3158
     type: "deposit",
     wallet_id: 1,
     uuid: "48a5aa48-784a-49f8-a549-80540346b1bb",
     confirmed: true,
     amount: "10",
     meta: null,
     payable_id: 1,
     payable_type: "App\User",
     updated_at: "2020-05-10 18:26:57",
     created_at: "2020-05-10 18:26:57",
     id: 8,
   }
it's converting as 10

**Comment by rez1dent3** [comment]
@cheran2017 The number of decimal places is adjusted using the parameter in the `decimal_places` table. Then you use `balanceFloat` everywhere. If the value of  `decimal_places` is 2 then your balance is divided by 10^2. Thus you can work with fractional numbers. 

The library works with integers to remove mantissa problems.
```php
var_dump(.1 + .2); // float(0.30000000000000004441)
```

**Comment by cheran2017** [comment]
working thanks

**Comment by php32** [comment]
@cheran2017 can you please attach example of how to deposit and withdraw decimal amount from wallet
