### ISSUE TITLE
🐞 Bug: deposit add 2 records at the same time 

### ISSUE THREAD

**Issue by Hussam3bd** [bavix/laravel-wallet#170]
Hi there,
When I do:
`$user->deposit(10);`

and when I check the user balance I found it 20,
`$user->balance`

I checked the transactions table, I found 2 records have been added to the user!
https://share.getcloudapp.com/X6uOjvvE

Does anyone have the same issue?

My User class:

```
namespace App\Models;

use Bavix\Wallet\Interfaces\Customer;
use Bavix\Wallet\Traits\CanPay;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail, Customer
{
    use Notifiable,
        CanPay,
        SoftDeletes;
}
```

**Comment by Hussam3bd** [comment]
Even when I do `withdraw` the same issue 2 records added to the `transactions` 🤔

**Comment by Hussam3bd** [comment]
Hmm,
I was using `$user->deposit(10);` in Route closure function, and that's why it was adding 2 rows at the same time.

Anyone can explain what was happening?

Here is my route
```
Route::get('/', [
    'as' => 'home',
    function () {
        $user = \App\Models\User::find(1);
        $user->deposit(10);
        $user->balance;

        return view('layouts.pages.home', compact('courses'));
    }
]);
```

**Comment by rez1dent3** [comment]
Hey. I have no such problem. Have you tried to execute the same code in the console command?

**Comment by rez1dent3** [comment]
I think your problem is that browsers make two requests.
1. Page request;
2. Getting favicon.ico;

If there is no icon, then the request will go to php. So you get a "error", which is not.

**Comment by Hussam3bd** [comment]
@rez1dent3 Yeah actually there's no problem when I run it in the console, it's only when I use it in `Route` closure function.

Anyway, thank you so much for your explanation and for your effort.
Everything working great for me.
