### ISSUE TITLE
How can I change balance for language?

### ISSUE THREAD

**Issue by krutyosila** [bavix/laravel-wallet#171]
Hello there,

I want to show the user balance differently by language.

Users have only one wallet. If the user changes language, I want the balance to appear as defined for that language.
en/page
$user->balance = 1 USD

de/page
$user->balance = 0.92 EUR

tr/page
$user->balance = 6.90 TRY

xx/page
$user->balance = (1 X xxrate)

If is it possible ?

**Comment by rez1dent3** [comment]
Hey. You can implement on your side. To work with the exchange rate, there is an addition: https://bavix.github.io/laravel-wallet/#/laravel-wallet-swap

**Comment by krutyosila** [comment]
Thanks, but I don't want to make exchange and create another wallet for users. if user's change language, user show language's currency on user->balance method.

**Comment by rez1dent3** [comment]
There is no magic. You still have to develop a service that will accept a wallet and give balance. The wallet has data on the currency, and you already convert the funds into the desired currency. In your case, the wallet balance will not be stable. It will change when the exchange rate changes.

**Comment by krutyosila** [comment]
You are right. Thank you for your interest.
