### ISSUE TITLE
max key lenth

### ISSUE THREAD

**Issue by ahmed25800** [bavix/laravel-wallet#172]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL:
alter table `transfers` add index `from_to_refund_ind`(`from_type`, `from_id`, `to_type`, `to_id`, `refund`))

**Comment by rez1dent3** [comment]
@ahmed25800 https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by ahmed25800** [comment]
it's another error I have already created the default thread length of the chart and it works in localhost as soon as I deploy my project in hosting it gives me this error

**Comment by rez1dent3** [comment]
@ahmed25800 
You have a problem configuring your database. You need to have a local environment the same as for the production. There is no problem in the library, the problem is in the database settings.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
