### ISSUE TITLE
What is meant by item's balance ? And how to define the item's price

### ISSUE THREAD

**Issue by hazem-taha** [bavix/laravel-wallet#175]
Hello 

Thanks for this amazing package. 

I have some questions related to it.

1. What is meant by `$item->balance` ? is it the quantity in stock ? 
2. How to define the price of the item/product ? is it the `getAmountProduct` method ?
3. If a product is purchased using another method than the wallet, like a credit card, is there a way to make a refund within the context of this package ? since as far as I understand, the refund is done for a product that is already paid for using this package's wallet `(bool)$user->paid($item); // bool(true)` 

Thanks in advance

**Comment by rez1dent3** [comment]
Hello.

1. The product has its own wallet. When you purchase, you make a transfer from wallet to wallet. Balance - the amount of "money".

2. That's right, `getAmountProduct`.

3. "Money" is returned to the wallet from which the purchase was made.

**Comment by hazem-taha** [comment]
1. A product having a wallet ? Can you please give a scenario to make it
clear for me as it makes no sense.

2. If I make a deposit in a user's wallet, and change the type of the
transaction manually to refund,  will this break something up? Considering
the concept the package is built on.

**Comment by rez1dent3** [comment]
> 1. A product having a wallet ? Can you please give a scenario to make it
clear for me as it makes no sense.

A technical feature is needed for purchase and that the points do not go nowhere.

> 2. If I make a deposit in a user's wallet, and change the type of the
transaction manually to refund,  will this break something up? Considering
the concept the package is built on.

Something like this is happening.
https://github.com/bavix/laravel-wallet/blob/master/src/Traits/CartPay.php#L160

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
