### ISSUE TITLE
When calling $user - > pay ($item), the database shows that you pay yourself?

### ISSUE THREAD

**Issue by jiangzhangy** [bavix/laravel-wallet#176]
When I call $user - > pay ($item) according to the usage document
There are two wallets under the same user in the database, and they pay for themselves. How to modify them?

**Comment by rez1dent3** [comment]
@jiangzhangy Hey. I did not understand your question. Do you want to choose which wallet to pay for your purchase?

If so, then
```php
$wallet = $user->getWallet('usd'); // we get the necessary wallet
$wallet->pay($item); // make a purchase
```

**Comment by jiangzhangy** [comment]
Capital flow at the time of purchase

**Comment by rez1dent3** [comment]
@jiangzhangy What's the question?

**Comment by jiangzhangy** [comment]
`$user->balance`
This command creates a default Wallet
`$user = User::first();
$user->balance; // int(100)

$item = Item::first();
$user->pay($item);`
This command creates another Wallet，And it's the same user's wallet

When users buy products, why does the money from one wallet flow to the other,and both wallets belong to the user。

It should be that the money in the buyer's wallet flows to the seller's wallet。

thanks

**Comment by rez1dent3** [comment]
@jiangzhangy 
One user wallet and another product wallet. When you buy, money is credited to the product account.

```php
$user->balance; // int(100)
$item->balance; // int(27)
$item->getAmountProduct($user); // int(9)
$user->pay($item); 

$user->balance; // int(91)
$item->balance; // int(36)
```

That is, the user's money was transferred to the product account.
This is necessary if someone needs to issue a certain amount of cash and monitor their movement.

For example, a points system. You know that you want to play 1,000,000 points. You take and create a wallet, and then accrue the required number of points. Create a crown team that will automatically transfer user rewards. You can’t get used to the budget and can follow the movement of funds.

Money does not burn, it moves from object to object.

**Comment by jiangzhangy** [comment]
Thank you for your explanation
