### ISSUE TITLE
There are no commands defined in the "vendor" namespace.

### ISSUE THREAD

**Issue by abduljeleelng** [bavix/laravel-wallet#177]
Hy, I am trying to install laravel-wallet in lumen.
after I load `composer require bavix/laravel-wallet`

I set my autoload as follow
```    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            "Bavix\\Wallet\\": "src/"
        }
    },
```

then I run the command 
`php artisan vendor:publish --tag=laravel-wallet-migrations`

I got the error `There are no commands defined in the "vendor" namespace.`

Please, I need help

**Comment by rez1dent3** [comment]
@abduljeleelng Hello. And why did you add this?
```php
            "Bavix\\Wallet\\": "src/"
```

Composer will automatically pick up the configs of this package and find the right code.

**Comment by abduljeleelng** [comment]
Thank for respond,
With out add `"Bavix\\Wallet\\": "src/"` and try to migrate, I got `There are no commands defined in the "vendor" namespace.`

I don't know what may cause the problem

**Comment by abduljeleelng** [comment]
@rez1dent3, Please can you help me to debug

**Comment by rez1dent3** [comment]
@abduljeleelng https://bavix.github.io/laravel-wallet/#/lumen

**Comment by abduljeleelng** [comment]
@rez1dent3, 
Thank, I am following the same instruction 
```
$app->register(App\Providers\AppServiceProvider::class);
$app->register(App\Providers\AuthServiceProvider::class);
$app->register(App\Providers\EventServiceProvider::class);

#Tymon\JWTAuth register
$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);

#Laravel Wallet
$app->register(\Bavix\Wallet\WalletServiceProvider::class);
```
I have registered/Add the service to the app

then I run `php artisan vendor:publish --tag=laravel-wallet-migrations` but I got the error `There are no commands defined in the "vendor" namespace.`

**Comment by rez1dent3** [comment]
@abduljeleelng this is what you need to connect the package to your project.

https://github.com/bavix/lumen-wallet-example/compare/ca573f99e87f51bbfde1d12fef178df8c373a18a...750ccdcc9e41bac2b2a443568367146f6d7d5244

Starting with lumen 6.x, the vendor:publish command is not necessary; lumen will automatically pick up migrations.

**Comment by abduljeleelng** [comment]
![image](https://user-images.githubusercontent.com/46464883/83972892-aef74900-a8da-11ea-9874-717b14449b1a.png)
Thank for your support, I'm so grateful,

@rez1dent3, I followed, above code sample to modify my code as it shows in snippet but I run the migration and I got above errors. please, @rez1dent3 how can I solve it.
Thank you in advance.

**Comment by rez1dent3** [comment]
@abduljeleelng https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by abduljeleelng** [comment]
problem solved !
Thank so much,
I am very grateful, Love you
