### ISSUE TITLE
How to Insert new column to transaction table

### ISSUE THREAD

**Issue by mayuriOAB** [bavix/laravel-wallet#178]
I want to insert new column to transaction table to maintain my operations. What are the steps.
Also how can I insert values to newly added column at the time of deposit.

**Comment by rez1dent3** [comment]
Hello, @mayuriOAB 

You can do it like this:
https://github.com/bavix/laravel-wallet/blob/4a597d72abe434afc81ef8690ef1ddf0a4cd6bac/tests/WalletExtensionTest.php#L25-L37

https://github.com/bavix/laravel-wallet/blob/4a597d72abe434afc81ef8690ef1ddf0a4cd6bac/tests/Common/Models/Transaction.php#L16-L21

But changing the structure, be more careful when updating. I would indicate the library version hard.

**Comment by mayuriOAB** [comment]
okay.
I want to add column as integer. I added as you suggested. But how can I use them. I am trying
$user->deposit(100, ['state' => 'QUEUED'], ['purpose' => $purpose]);
I have added state as new column and next array for meta field.
can you please help me to insert or update this while deposit and withdraw

**Comment by rez1dent3** [comment]
@mayuriOAB Did you bind the operation?
https://github.com/bavix/laravel-wallet/blob/4a597d72abe434afc81ef8690ef1ddf0a4cd6bac/tests/WalletExtensionTest.php#L19

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
