### ISSUE TITLE
Wallet giving weird behavior

### ISSUE THREAD

**Issue by kinnngg** [bavix/laravel-wallet#179]
Anyone know whats wrong with this code or its there some bug in package?

This is making the wallet go crazy. After running it the wallet amount changes to wierd high for example if a user has 6540 cent and deposit is of 750 cent then wallet bal ($user->balance) will show up 15037 till you run `php artisan wallet:refresh` (this command fixes it)

```php
\DB::beginTransaction();
$quizUsers = $this->quiz()->cursor();

 foreach ($quizUsers as $index=>$quizUser)
 {
       $quizUser->user->deposit($some_amount, ['message' => 'Prize', 'type' => 'quiz_prize', 'resource_uuid' => $this->quiz->uuid, 'reference_id' => uniqidReal() ]);
 }
 \DB::commit();
```

**Comment by kinnngg** [comment]
Hey,
       Thanks. It seems this issue is not occurring after I updated the version.

But do anyone know why the casting of Wallet "balance" to "int" doesn't work?


```php
/**
     * Wallet model configuration.
     */
    'wallet' => [
        'table' => 'wallets',
        'model' => Wallet::class,
        'casts' => [
            'balance' => 'int'
        ],
        'default' => [
            'name' => 'Default Wallet',
            'slug' => 'default',
            'decimal_places' => 0
        ],
    ],
```

**Comment by rez1dent3** [comment]
@kinnngg Most likely we have installed `bcmath`, which means that long arithmetic is included. You can add large numbers (for example, you need for bitcoin). If you want to disable, then you need to change the `mathable` field:
https://github.com/bavix/laravel-wallet/blob/52f954f11e7d991313bb3f239a818024492e23b5/config/config.php#L37-L39

You need to put the config:
```php
        'mathable' => Math::class,
```

**Comment by rez1dent3** [comment]
@kinnngg Needed for long arithmetic to work. This is a cardinal difference between the 5th version and the 4th. 

https://github.com/bavix/laravel-wallet/blob/master/src/Simple/Math.php

All arithmetic is reduced to a string in order to be able to create wallets of ether, bitcoin and others.
A lot of people asked for this functionality.

**Comment by kinnngg** [comment]
Ohk. Thanks
