### ISSUE TITLE
3.0: new features

### ISSUE THREAD

**Issue by rez1dent3** [bavix/laravel-wallet#18]
We write wishes that can be added to the project.

**Comment by zek** [comment]
Currency option like USD, EUR even Bitcoin would be cool.

**Comment by rez1dent3** [comment]
@zek The wallet is not tied to a specific currency, this restriction falls on the developer. You can even use your own coins.

If you know how to implement your idea, please share.

**Comment by rez1dent3** [comment]
- you must log actions
- to make an abbreviated syntax is more safe
- remove the difference between `$user->pay()` and `$user->wallet->pay()`

**Comment by rez1dent3** [comment]
- add ability to select by user
- add purchase groups

**Comment by rez1dent3** [comment]
@MoeCasts In branch **3.0.x-dev**. Operation `$user->pay($item)` will be equivalent to operation `$user->wallet->pay($item)`.

I advise you not to use abbreviated syntax now.

Therefore, in the Transfer model, the "from" column will be the wallet model.

**Comment by rez1dent3** [comment]
- [ ] remove the ability to set the status of the transfer

**Comment by MoeCasts** [comment]
@rez1dent3 I have create the new migration structures like that. I think that would be better.
  The `wallets` table should not have `name` `slug` `description` columns, If you change the wallet name, you would change a lot of data. So, we can solve it by that If you want to name the wallet, you can set it to `config/wallet.php` like that.
  And we can add ` from_wallet_id`  `to_wallet_id` `action` columns to the `transfers` table. Sometimes, a product has multi chargeable actions like read、download、subscribe. If there is a `action` column in `transfers` table, we can check the product was paid in the correct way.
```
<?php

return [
    ...
    'name' => [
    	'CNY' => '元',
    	'USD' => 'dollar'
    ];
    ...
];
```
```
Schema::create('wallets', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->morphs('holder');
    $table->string('currency')->default('CNY');
    $table->bigInteger('balance')->default(0);
    $table->timestamps();
});

Schema::create('transactions', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->morphs('holder');
    $table->bigIncrements('wallet_id');
    $table->enum('type', ['deposit', 'withdraw'])->index();
    $table->bigInteger('amount');
    $table->boolean('confirmed');
    $table->json('meta')->nullable();
    $table->uuid('uuid')->unique();
    $table->timestamps();
});

Schema::create('transfers', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->morphs('from');
    $table->unsignedInteger('from_wallet_id');
    $table->string('action')->comment('read/download/subscribe/trial and so on');
    $table->morphs('to');
    $table->unsignedInteger('to_wallet_id');
    $table->bigInteger('fee')->defalut(0);
    $table->unsignedInteger('deposit_id');
    $table->unsignedInteger('withdraw_id');
    $table->uuid('uuid')->unique();
    $table->timestamps();
});
```

**Comment by rez1dent3** [comment]
@MoeCasts I'll think about your structure. Thank you.

According to the changes in the table of wallets, I will not replace slug, name and description with currency. I am not tied to currencies and do not want to tie abstraction.

**Comment by rez1dent3** [comment]
I'll borrow some ideas.

**Comment by MoeCasts** [comment]
@rez1dent3 Actually, you can set currency to anything what you want, such as points, coins but not only currencies. I do not think that a currency need multi wallets.

**Comment by rez1dent3** [comment]
@MoeCasts I've studied your structure and tested it against real data, it's good and bad at the same time. In the third version, the structure will not change. But I will fix bugs of the second version and strongly rewrite the code. I will take everything to the services and with singleton it will be possible to overload any part of the code.
