### ISSUE TITLE
The transaction cannot be rejected

### ISSUE THREAD

**Issue by CreationLee** [bavix/laravel-wallet#181]
The transaction  can be confirmed but can't rejected, how can i reject users witharaw transaction

**Comment by rez1dent3** [comment]
@CreationLee Hey. No way. You will have to write your own package extension for that.

**Comment by CreationLee** [comment]
> @CreationLee Hey. No way. You will have to write your own package extension for that.

thanks

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
