### ISSUE TITLE
How can I reset user balance to 0

### ISSUE THREAD

**Issue by ysfkaya** [bavix/laravel-wallet#182]
First of all, thanks for this useful package.

I want to reset the user balance to zero. I have a tracker for each month reset the user balance. How can I reset it with safely?

Actually I put the `due_at` column in `transactions` table and I track it with cronjob for now. If has any user with `confirmed`, `transaction_type` is `deposit` and `due_at` is not null then I'm using the `forceWithDraw` method to reset balance by given user balance.

Do you think this will work?

**Comment by rez1dent3** [comment]
@ysfkaya Hello. 
For a light load, a good solution. When you have a load and there will be a lot of users, then there is a high probability of taking the user to minus. I would throw in the cache (redis) the key to change the account and forbid for this time forbade to work with the wallet.

This will protect you from race conditions.

**Comment by ysfkaya** [comment]
Thank you for support @rez1dent3. I changed the `forceWithDraw` to `withDraw`.For now, we do not expect a lot of users, I will host specific users in the system. But if there is a heap of users outside of what we expected, I will follow the advice.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
