### ISSUE TITLE
The balance always cant't auto-refresh after paid 

### ISSUE THREAD

**Issue by CreationLee** [bavix/laravel-wallet#183]
I'm using **version 4.1.4**

The balance cant't be auto refreshed after user paid,
like user has balance of 10, and buy a product(price 10), after paid , this user still has 10.
This situation not happend all the time, i don't know when it will happens, so i add

`$wallet->refreshBalance();`

after user paid.

It just getting better, but still happens, i'm using 

- laravel 5.5

- php 7.2

It is very dangerous to our system, we have millions cash flow to handle per month.

**Comment by CreationLee** [comment]
If i'm using `$wallet->refreshBalance();` , the balance can be right, but i had add `$wallet->refreshBalance();`  after user paid, sometimes it still goes wrong

**Comment by rez1dent3** [comment]
@CreationLee hello. Keep your balance in a single-threaded redis and you will be happy.

https://github.com/bavix/laravel-wallet-vacuum/blob/b0148a3889af9c5baedcef8e001097b412cb4ffd/src/Store.php

I made a package for myself corresponding package: https://packagist.org/packages/bavix/laravel-wallet-vacuum

**Comment by CreationLee** [comment]
@rez1dent3 I'm using bavix/laravel-wallet:4.1.4, so i can't use  bavix/laravel-wallet-vacuum. Is there any other way to handle it?

**Comment by rez1dent3** [comment]
> I'm using bavix/laravel-wallet:4.1.4, so i can't use bavix/laravel-wallet-vacuum.

Choose old version.

> Is there any other way to handle it?

There are many methods to deal with race condition, but you will have to develop them on your side.

**Comment by CreationLee** [comment]
@rez1dent3 Thanks, i choosed bavix/laravel-wallet-vacuum in version 0.0.1.
This problem will be solved if i just installed this package? am i need to change the config file?
i'm still confused why this problem  happend, i have read your code and i do not understand why this problem happend

**Comment by rez1dent3** [comment]
@CreationLee If I understand you correctly, then yes. But you should have a redis cache by default.

**Comment by CreationLee** [comment]
@rez1dent3 I have a redis  cache, i'm curious about this problem, why this happend

**Comment by rez1dent3** [comment]
> @rez1dent3 I have a redis cache, i'm curious about this problem, why this happend

Unfortunately, I do not know.

**Comment by CreationLee** [comment]
@rez1dent3 Thanks

**Comment by CreationLee** [comment]
@rez1dent3 The same problem still occured, does it can solve all this kind of problems by just upgrate it to 5.x

**Comment by rez1dent3** [comment]
@CreationLee Hello my friend. I don't know, I can't reproduce the problem. Do you have a stable playback case? Then I'll check.

**Comment by CreationLee** [comment]
@rez1dent3 Unfortunately, i don't know when this case will happen

**Comment by rez1dent3** [comment]
@CreationLee unfortunately I cannot help.
