### ISSUE TITLE
what is the best way to display thousand comma

### ISSUE THREAD

**Issue by anthoz69** [bavix/laravel-wallet#184]
Hi, I was confused about display float to thousand comma and 2 place of decimal and not round it.

When number is 56.567 display with PHP `number_format(56.567, 2, '.', ',')` number show 56.57 .

When user pay with `withdrawFloat` wallet will withdraw 5.56, How i can display same value.

**Comment by rez1dent3** [comment]
Hello. There is no rounding on the library side. For formatting, you need to write your own solution.

![Screenshot from 2020-07-13 18-54-26](https://user-images.githubusercontent.com/5111255/87325582-4b47e780-c53a-11ea-9a57-5e74b5c42a25.png)

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
