### ISSUE TITLE
Transaction amount how to display as float 

### ISSUE THREAD

**Issue by cheran2017** [bavix/laravel-wallet#185]
while am doing transfer i am using deposit float  and it's saving in transaction table in amount column like full value(if i deposit 12 it's saving like 1200). But while am trying to display like float value it's showing 1200.but i want to display like 12.00.
Please help

**Comment by rez1dent3** [comment]
@cheran2017 Hey. Try it like this `$transaction->amountFloat`.
https://github.com/bavix/laravel-wallet/blob/9edd3ae6f90512b510e8ea15a3f829a9d841bfd8/src/Models/Transaction.php#L102-L109

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by yawaRcan** [comment]
$transaction->amountFloat
it return number with many zerooss why

**Comment by yawaRcan** [comment]
number_format( $transaction->amountfloat,2)
i do this to remove accessive zeros
