### ISSUE TITLE
Too many migrations for 3 tables

### ISSUE THREAD

**Issue by MachariaK** [bavix/laravel-wallet#186]
Is it possible to organize the migrations so to have 3 migrations for 3 tables instead of 12?

**Comment by rez1dent3** [comment]
@MachariaK It is possible, but I will not do it. Migrations are added during the development process and with the help of them you can track when and at what point new columns were added, old ones were deleted. A lot of users still use v4.x and they will someday want to upgrade.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
