### ISSUE TITLE
Balance After Each Transaction in transactions table

### ISSUE THREAD

**Issue by ziachand** [bavix/laravel-wallet#187]
We want to show balance on each transaction. can we use any existing functionality to acheive this.

**Comment by rez1dent3** [comment]
The library does not provide this capability. You can do it yourself. For example like this:
```sql
SELECT
       t1.id,
       t1.wallet_id,
       t1.amount,
       (
           SELECT IFNULL(SUM(amount), 0)
           FROM transactions t2
           WHERE
                 t2.confirmed=1 AND
                 t2.wallet_id=t1.wallet_id AND
                 t2.id<t1.id
       ) lastBalance,
       t1.created_at

FROM transactions t1
order by t1.id desc
```

![Screenshot from 2020-07-16 18-27-50](https://user-images.githubusercontent.com/5111255/87690394-146c0e80-c792-11ea-9e5c-e00a267d696c.png)

**Comment by ziachand** [comment]
thank you so much
