### ISSUE TITLE
Conflict with laravel cache

### ISSUE THREAD

**Issue by SuryaJD** [bavix/laravel-wallet#188]
I am using this package along with laravel cashier. I got this issue on user model.  
Trait method refund has not been applied, because there are collisions with other trait methods on App\User.
Seems like both plugin use refund method in traint.
How can I solve this?

**Comment by rez1dent3** [comment]
@SuryaJD Hello. Can't use HasWallet.
Only shorthand commands will not be available to you ($user->withdraw, $user->deposit...).

But you can access the wallet like this:
```php
$user->wallet->deposit(1);
$user->wallet->withdraw(1);
```

Model example:
https://github.com/bavix/laravel-wallet/blob/master/tests/Models/UserCashier.php
