### ISSUE TITLE
Is the doc for payment wrong

### ISSUE THREAD

**Issue by MoeCasts** [bavix/laravel-wallet#19]
According to the doc, User model use CanBePaid trait, Item use hasWallet trait. I think it should be swapt. Such as User model use hasWallet trait, Item use CanBePaid trait.

**Comment by rez1dent3** [comment]
@MoeCasts I will consider replacing in the next versions, thank you

**Comment by MoeCasts** [comment]
@rez1dent3 I read the code just now, I think User model use CanPay trait is a good choice.

**Comment by rez1dent3** [comment]
@MoeCasts this week I will collect the test version and let you know

**Comment by MoeCasts** [comment]
@rez1dent3 Thank you for your work. I will looking forward it.

**Comment by MoeCasts** [comment]
@rez1dent3 I think there should be a CanBePaid/CanBePaidFloat trait for Item instead of hasWallet.

**Comment by rez1dent3** [comment]
@MoeCasts I'll think about it. Maybe I will. Thank you. Is PR #20 okay?

**Comment by MoeCasts** [comment]
@rez1dent3 Yes, it's okay.

**Comment by rez1dent3** [comment]
@MoeCasts update docs ;)

PS,
This issue will not be closed until I make a decision on the trait for the goods.

**Comment by MoeCasts** [comment]
@rez1dent3 I appreciate for your update.
