### ISSUE TITLE
Problem in new version

### ISSUE THREAD

**Issue by version31** [bavix/laravel-wallet#190]
I get this:

`Argument 1 passed to Bavix\Wallet\Services\WalletService::getWallet() must be an instance of Bavix\Wallet\Interfaces\Wallet, instance of App\User given, called in /home/user/wallet/vendor/bavix/laravel-wallet/src/Simple/Store.php on line 22`

**Comment by rez1dent3** [comment]
@version31 it looks like you didn’t belong to the interface.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by matinwd** [comment]
any updates on this?

**Comment by matinwd** [comment]
oh sorry. i just see the solution. thanks
