### ISSUE TITLE
How to get all transactions ?

### ISSUE THREAD

**Issue by jaydeepakbari** [bavix/laravel-wallet#198]
i am using https://bitfumes.github.io/laravel-multiauth/publish.html this package for multi-auth

i have following guard admin, customer, vendor how can i get all transaction in one table ?

**Comment by rez1dent3** [comment]
@jaydeepakbari Hello.
Get transactions like this:
```php
$wallet->transactions()
```

I didn't understand your question.

**Comment by jaydeepakbari** [comment]
i want all in one query it is possible ?

`
$admin->wallet->transactions();
$customer->wallet->transactions();
$vendor->wallet->transactions();
`

above three in one query with paginate.... its possible ?

**Comment by rez1dent3** [comment]
If I understand you correctly, then you will have to manually form such a request to the database.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by jaydeepakbari** [comment]
Okay thanks for your help....
