### ISSUE TITLE
Suggestion : Accounts & Period Queries

### ISSUE THREAD

**Issue by AEK-BKF** [bavix/laravel-wallet#199]
Hi,
First of all, thank you so much for this nice package,

I suggest to :
1- Add account (optional) for each transaction for Accounting Tracking.
Ex: 
```
$account = 'customers', 'vendors', 'expenses', ...etc
$user->deposit(10, $account=null); 
$user->pay($item, $account=null);
$user->refund($item, $account=null);
...etc
```
2- Get transactions records by period :
ex: 
```
$wallet->transactions($from=null, $to=null, $accounts[]=null);
$wallet->transactionsToday($accounts[]=null);
$wallet->transactionsLastweek($from, $to, $accounts[]=null);
...etc
```
Thanks.

**Comment by rez1dent3** [comment]
Hello.

Your idea is good, but not universal. It already works, here are a couple of examples:

> 1- Add account (optional) for each transaction for Accounting Tracking.

https://github.com/bavix/laravel-wallet/blob/a73723682c440becebfee31efb4341a94c3374b3/tests/FilterTest.php#L22-L24

> 2- Get transactions records by period :

https://github.com/bavix/laravel-wallet/blob/a73723682c440becebfee31efb4341a94c3374b3/tests/FilterTest.php#L36-L41

complete unit test code can be found here: https://github.com/bavix/laravel-wallet/blob/a73723682c440becebfee31efb4341a94c3374b3/tests/FilterTest.php

**Comment by AEK-BKF** [comment]
Thanks for quick answer,
But I mean Account as a model not a string, 
And for Periods, I mean, when we want to retrieve transactions (as objects) in specific range of date

Thanks

**Comment by rez1dent3** [comment]
> But I mean Account as a model not a string,

Then I did not understand you. What's the difference? You can put any structure in json and filter by it.

> And for Periods, I mean, when we want to retrieve transactions (as objects) in specific range of date

You and get the Eloquent object.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
