### ISSUE TITLE
Extending transaction model

### ISSUE THREAD

**Issue by smtlab** [bavix/laravel-wallet#201]
Hey @rez1dent3 

Can you suggest to me how should I go about the below use case?

I am working on the logistics app, where I have shipments from multiple customers.

Every customer has **cod-wallet**
I have to deposit **Cash on delivery** amount from shipments to cod-wallet.

The problem here is there is a background service which picks up unpaid shipments from DB and processes deposit, also I cannot maintain any flag in shipment model for paid status as it would not be reliable, I directly want to join with `transactions` table and check if the entry exists with type `deposit` for a shipment.

Unfortunately, the transaction only takes metadata from the user side, using the JSON column I cannot take advantage of joins.

**My thoughts on giving developers the flexibility to customize model**

- We can have a `morphTo` relation in the transaction model for developers to extend according to their requirements and allow developers to pass transaction class while doing transactions.
- We can make use of virtual columns reference: https://mysqlserverteam.com/indexing-json-documents-via-virtual-columns/#:~:text=As%20the%20MySQL%20manual%20notes,value%20from%20the%20JSON%20column.
- add an external_ref_id column to transaction table

Any suggestions would really help.

Thanks in advance

**Comment by rez1dent3** [comment]
Hello @smtlab.

You can add the required columns to the database yourself. Someone asked me already like this..
Here's an example.

Migrating a table:
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/migrations/2019_09_19_191432_alter_column_transaction_table.php#L17-L19

Adding data on insertion:
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/Objects/Operation.php#L3-L18

Overriding the transaction record object:
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/WalletExtensionTest.php#L19

And now we write data to the database:
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/WalletExtensionTest.php#L31-L36

For convenience, you can override the Transaction model:
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/TestCase.php#L68

Nothing else is needed. The complete code is available [here](https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/migrations/2019_09_19_191432_alter_column_transaction_table.php), [here](https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/Objects/Operation.php) and [here](https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/tests/WalletExtensionTest.php))))

**Comment by smtlab** [comment]
@rez1dent3 Thanks for giving a detailed explanation, really appreciate your time :)

I completely missed the config file, I see can override all services and models.

**Comment by atapatel** [comment]
@smtlab can you please share your logic for expiry logic here?

**Comment by nagsamayam** [comment]
Hi @rez1dent3 

Thank you soo much for providing such a great package. 
In the above comment you have suggested use Bavix\Wallet\Objects\Operation class to store additional 'trasactions' table columns data. But I didn't see the Bavix\Wallet\Objects\Operation class in the codebase. Can you please suggest how to add additional columns for 'transactions' table?

**Comment by rez1dent3** [comment]
@nagsamayam Hello. I don't check old issue, I found your question by accident. If you want to discuss in more detail, then create a new issue.

Yes, Operation no longer exists, but it is still possible to implement this functionality. An example is in unit tests:
https://github.com/bavix/laravel-wallet/blob/88913b5f30116956f8d6ea3dad8315930eb55e72/tests/Infra/Transform/TransactionDtoTransformerCustom.php#L18-L28

**Comment by nagsamayam** [comment]
> @nagsamayam Hello. I don't check old issue, I found your question by accident. If you want to discuss in more detail, then create a new issue.
> 
> Yes, Operation no longer exists, but it is still possible to implement this functionality. An example is in unit tests:
> 
> https://github.com/bavix/laravel-wallet/blob/88913b5f30116956f8d6ea3dad8315930eb55e72/tests/Infra/Transform/TransactionDtoTransformerCustom.php#L18-L28

Hi @rez1dent3
Thank you soo much for the solution provided and also noted your suggestion to create new issue. Once again thank you so much for providing package.
