### ISSUE TITLE
How get all the withdrawal amount and detail?

### ISSUE THREAD

**Issue by engrasadullah97** [bavix/laravel-wallet#203]
Hello, I am using laravel-wallet is working very well. now I am want to able to retrieve all the withdrawal detail like the transactions.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by humaneguy** [comment]
I think this only works when there is just a wallet. Say you want to fetch for all users and their wallets. How do you go about it?
