### ISSUE TITLE
How to change table names as I have already a table transactions in my database? Please suggest

### ISSUE THREAD

**Issue by mdhanu11** [bavix/laravel-wallet#204]

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/blob/1c26faf8cfb7bfd4066aad8c4e86bd591ae71db9/config/config.php#L91-L97

**Comment by mdhanu11** [comment]
Thanks for your reply, Is config.php is after publish or is it in vendor folder?
