### ISSUE TITLE
Database Migration Problem

### ISSUE THREAD

**Issue by gjoniemanuel** [bavix/laravel-wallet#205]
When i run migrations i get this problem below:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `transfers` add index `from_to_refund_ind`(`from_type`, `from_id`,`to_type`, `to_id`, `refund`))

Already i have fix my AppServiceProvider with:

```
use Illuminate\Support\Facades\Schema;
//....
public function boot()
{
    Schema::defaultStringLength(191);
}
```

but i get the same error.

**Comment by rez1dent3** [comment]
@gjoniemanuel Hey. I need more data about your software (php, mysql) to check, even patches are important.

**Comment by gjoniemanuel** [comment]
Laravel Framework 7.21.0
PHP 7.2.33
mysql  Ver 15.1 Distrib 10.3.24-MariaDB, for Linux (x86_64) using readline 5.1

@rez1dent3 thx for your response.

**Comment by rez1dent3** [comment]
@gjoniemanuel Checked, I have no problem.

![Screenshot from 2020-08-24 10-34-15](https://user-images.githubusercontent.com/5111255/91016414-66a41900-e5f5-11ea-961a-4b0cc8b6abf7.png)

AppServiceProvider.php
```php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
```

**Comment by fignewton** [comment]
@gjoniemanuel what DB engine and Character Set are you using?

This can happen if you're using a DB engine other than **InnoDB** or a Charset different from **UTF8** which I think are the most common Engine and Charset with MySQL and MariaDB.

**Comment by gjoniemanuel** [comment]
![Capture](https://user-images.githubusercontent.com/54986730/91232570-036ecf80-e738-11ea-99f7-9de79c8ad290.PNG)

**Comment by fignewton** [comment]
@gjoniemanuel Your settings and image show conflicting Charsets (utf8mb4 vs cp1252/latin1), so it's hard to tell which charset the actual database table the migration you're running is using (it's possible for tables within the same database to be using different charsets, though not recommended). Also the details you've provided don't show the engine your database is using.

Have a look at [this link](https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes) that explains the details of how charsets and engines affect the calculation of the key length for indexes. The top 3 responses are very informative.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
