### ISSUE TITLE
Cart::make Error

### ISSUE THREAD

**Issue by arcturustechnology** [bavix/laravel-wallet#209]
Error
Call to undefined method Bavix\Wallet\Objects\Cart::make()

**Comment by rez1dent3** [comment]
Hello, @arcturustechnology. 
This is a mistake in the documentation, before there really was a `::make` method.
Now it is better to do initialization so that:
```php
$cart = app(Cart::class);
```
You can quickly override class `Cart`.

Updated documentation in `develop` branch.
