### ISSUE TITLE
Is the wallet genuine

### ISSUE THREAD

**Issue by Kuraj11101** [bavix/laravel-wallet#211]
I am looking into using a wallet system In my new laravel money transfer app. Is Bavix Wallet the best choice?

And also if I am to use it, how do I accept user transfer and deposit input manually by the user.

For example allow a user to transfer money to another user in app... And also allow deposit by adding card?

**Comment by rez1dent3** [comment]
Hello, @Kuraj11101. 
A package is a set of standard actions for a wallet. You develop business logic on your side. 
What can:
- [multi wallets](https://bavix.github.io/laravel-wallet/#/new-wallet);
- [transfers between wallets](https://bavix.github.io/laravel-wallet/#/transfer) ([for multi wallets](https://bavix.github.io/laravel-wallet/#/wallet-transfer));
- [deposit of funds](https://bavix.github.io/laravel-wallet/#/deposit);
- [withdrawal of funds](https://bavix.github.io/laravel-wallet/#/withdraw);
- [confirmation of the transaction](https://bavix.github.io/laravel-wallet/#/confirm);
- removal of confirmation ([unconfirm](https://github.com/bavix/laravel-wallet/blob/cd63cebb8313137b10ec6006f1891413c30277ee/tests/ConfirmTest.php#L129-L140));
- [payment](https://bavix.github.io/laravel-wallet/#/payment);
- [gift](https://bavix.github.io/laravel-wallet/#/gift);
- [return for goods](https://bavix.github.io/laravel-wallet/#/refund);
- [cart payment](https://bavix.github.io/laravel-wallet/#/cart); 

Examine the packages and make a decision. Perhaps you don't need a bold package and design your own.
Good luck with your choice.

**Comment by Kuraj11101** [comment]
Thanks for the heads up. Will see how best I can work with your package to make it work with my business logic.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
