### ISSUE TITLE
rait method deposit has not been applied, because there are collisions with other trait methods on App\User

### ISSUE THREAD

**Issue by asadullah097** [bavix/laravel-wallet#213]
Trait method deposit has not been applied, because there are collisions with other trait methods on App\User
on localhost, it works fine but once I upload it to the server it gives me the above issue.

**Comment by rez1dent3** [comment]
@asadullah097 
Hey. You have a conflict between packages and I don't have enough data to answer your question.

**Comment by asadullah097** [comment]
solved  actually I import the two methods and not used that methods therefore I give me the error on the server
Thank you
