### ISSUE TITLE
Multiple wallet creation

### ISSUE THREAD

**Issue by kenwizzy** [bavix/laravel-wallet#218]
Hello. When creating custom wallet (Using laravel 7), It automatically creates two wallets (My custom wallet and another default wallet). Please how can I fix this and make it to create only my custom wallet. Below is my sample code

public function display($id)
    {
        $user = User::findOrFail($id);
        
            $wallet = $user->createWallet([
                'name' => 'System Wallet',
                'slug' => 'system',
            ]);
        
        return view('dashboard.profile', compact('user'));
    }

**Comment by rez1dent3** [comment]
Hello. Unfortunately, this can't be done. A default wallet must exist and nothing can be done about it.

This is where it is created.
https://github.com/bavix/laravel-wallet/blob/df3ce67878da3bf64da65dbe3203f5da0fdd54be/src/Traits/HasWallets.php#L90-L95

**Comment by rez1dent3** [comment]
Automatic creation was needed between 2.x and 3.x versions. Now I will try to remove the automatic creation of a wallet by default, if I make a release and unsubscribe to you

**Comment by rez1dent3** [comment]
@kenwizzy Update to version 5.4.0 and the problem should disappear.

**Comment by kenwizzy** [comment]
Thanks a lot, I appreciate
