### ISSUE TITLE
Payment user issue

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#226]
when i deposite with 2 diffrent auth it added the payment in the plus the balance instead of updating each balance

**Comment by rez1dent3** [comment]
Hello. Describe the problem in detail.

**Comment by odion-cloud** [comment]
> Hello. Describe the problem in detail.
i am knew with this package, and i want every user should have there own wallet ,but when i created two users and when i deposit  from the two user dashboard it reflex in one account all the money where stored in one place,  it was as the both user are sharing one wallet

**Comment by rez1dent3** [comment]
Send the code, I can't reproduce the situation when two different users use the same wallet. I think you have a mistake somewhere.

I tried the following code in Tinker and everything is fine:
```php
$firstUser->deposit(100);
$firstUser->balance; // 100
$secondUser->balance; // 0
$secondUser->deposit(200);
$secondUser->balance; // 200
$firstUser->balance; // 100
```

**Comment by odion-cloud** [comment]
> ```
> $firstUser->deposit(100);
> ```

thank you bro i was able to resolve the issue 
instead of 
$user->User::first();

i use this and it work for me!
$user = User::findOrFail(auth()->user()->id);

**Comment by rez1dent3** [comment]
@odion-cloud I will tell you how to optimize your code, laravel pulls the user out by itself.
Replace this 
```php
$user = User::findOrFail(auth()->user()->id);
```
 with this
```php
$user = auth()->user();
```

You will get rid of an extra query to the database
