### ISSUE TITLE
Laravel 8 Supported ?

### ISSUE THREAD

**Issue by renztoygwapo** [bavix/laravel-wallet#227]
In you read me we cannot see that you listed laravel 8 latest version, so my question is does this package support laravel 8 without any major changes?
Thanks

**Comment by rez1dent3** [comment]
Hello @renztoygwapo. 
This is how I added support for Laravel 8: https://github.com/bavix/laravel-wallet/commit/70413fb6f9db7ce48cee5a9047d630ff8b00e4e0

If you've used 5.x, you don't need to make any changes.
