### ISSUE TITLE
Hello please How make wallettype

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#230]
please i want to create different wallet type instead of direct wallet

**Comment by rez1dent3** [comment]
Hello. What does wallet type mean?

**Comment by odion-cloud** [comment]
> Hello. What does wallet type mean?

i want my user to select the wallet plan before they can pay i dont want them to pay without wallet plan ,it we be like difference type of wallet plan to select from

**Comment by rez1dent3** [comment]
@odion-cloud I think you are talking about multi-wallets: https://bavix.github.io/laravel-wallet/#/new-wallet
