### ISSUE TITLE
please i need help assist to use this

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#232]
with this package i want the admin to be able to create deference type of wallet and when user register an account every user we have multiple wallet according to the wallet categories the admin created

**Comment by rez1dent3** [comment]
@odion-cloud Hello. First, create a table with a list of possible wallets and the administrator will already be editing this list. Conclude wallets relative to the list. If I understand you correctly.

**Comment by odion-cloud** [comment]
> @odion-cloud Hello. First, create a table with a list of possible wallets and the administrator will already be editing this list. Conclude wallets relative to the list. If I understand you correctly.

yes you do understand me but how do i connect it to the wallet please i really need it  help me with the logic

**Comment by odion-cloud** [comment]
i want the user to have multiple types of wallet each wallet they select have wallet each

**Comment by rez1dent3** [comment]
table `wallet_lists`

name |
------- |
dollar |
lari |

For example, you can do this

```php
foreach (WalletList::all() as $wallet) {
    $user->createWallet([
        'name' => $wallet->name,
    ]);
}
```
