### ISSUE TITLE
transaction fee

### ISSUE THREAD

**Issue by betysam55** [bavix/laravel-wallet#233]
is there any way to handle transaction processing fee that it will be reduced from the sender and it will be paid to system admin

**Comment by rez1dent3** [comment]
Hello. There is a tax collection, but this money is not credited to anyone, but simply burned out. 

https://github.com/bavix/laravel-wallet/blob/780270c42bdb9e4a57366f45148cc83d199bfe41/tests/TaxTest.php#L26-L46

**Comment by betysam55** [comment]
thanks for your help

**Comment by betysam55** [comment]
and also one thing  i cant use payFloat method do you have any suggestion

**Comment by rez1dent3** [comment]
@betysam55 The PayFloat method was not added on purpose, since pricing goes in the product model. It is easier and better to bring there to the desired price. This saves you from being shot in the leg.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
