### ISSUE TITLE
How to get transfer history by receiver's ID?

### ISSUE THREAD

**Issue by cmarixdev** [bavix/laravel-wallet#234]
The scenario is when $user is getting the amount transfer from multiple users, how to get all the transfer history of $user.
**Example:**
`$user1->transfer($foo, 5);`
`$user2->transfer($foo, 15);`
`$user3->transfer($foo, 10);`

I want to list entry of $foo received the amount. Right now I can only list transfer history by calling `$user1->transfers;` 
Is there any method of transfer where we can get data by `to_id`?

Thanks,

**Comment by cmarixdev** [comment]
**UPDATE:** I got the transfer history by calling directly class `$receive_history = Transfer::where('to_id', $foo->id)->get();` 

Query: Can we overwrite transfer class and add our own methods to get details of sender `from_id` Model class.
i.e.
In **Transfer.php:**
```
public function sender()
 {
        return $this->belongsTo(User::class, 'from_id');
 }
```

**Controller:**
`$received_history = Transfer::with('sender')->where('to_id', $foo->id)->get();`

**Comment by rez1dent3** [comment]
Hello. You can easily overload the model and add the method you need.

https://github.com/bavix/laravel-wallet/blob/780270c42bdb9e4a57366f45148cc83d199bfe41/config/config.php#L113

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
