### ISSUE TITLE
total balance of all multiple wallet

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#235]
please how can i get all balance of the user including user default wallet balance and other wallet balance he create i want to get total of them all

**Comment by rez1dent3** [comment]
There is no such possibility out of the box, you have to do it manually.
```php
$balance = 0;
foreach ($user->wallets as $wallet) {
  $balance += $wallet->balance;
}
```

**Comment by abduljeleelng** [comment]
Hello @rez1dent3, Please, how can I get the total balance of all the users
