### ISSUE TITLE
Can a 'product' have multiple wallets?

### ISSUE THREAD

**Issue by iamroi** [bavix/laravel-wallet#237]
Thank you for this incredible package!!

I was just wondering if the below is possible as it will solve so many problems on my app

`
        $user->getWallet($walletSlug)->pay($product->getWallet($walletSlug)); // not possible at the moment
`

Currently I'm treating my 'product' as another HasWallets entity and using it like below. It would be great to understand if it's ok to use it like this

`
        $user->getWallet($walletSlug)->transfer($product->getWallet($walletSlug), $amount);
`

Thanks a ton!

**Comment by rez1dent3** [comment]
Hello. Unfortunately, it won't work. The wallet does not inherit the Product interface.

You can solve your problem with a transaction and an additional transfer, or continue doing as you do.
```php
        app(DbService::class)->transaction(function () use (&$transfer, $product, $buyer) {
            $transfer = $buyer->pay($product);
            $product->transfer($product->getWallet('testing'), $transfer->deposit->amount, $transfer->toArray());
        });

```

PS,
The disadvantage of these approaches is that refunds will not work for you.

**Comment by iamroi** [comment]
Thanks for the explanation! That's unfortunate. I think I will stick with my method as it seems I won't be able to use the refund or other useful functions anyway.

Do you think it is ok to add new columns in `transactions` table as required like mentioned in #201 ? Also I'm not sure if the json `meta` column can be used for my use case.

For example, adding `product_id`, `some_internal_type` columns in `transactions` table so that I can connect user and product transactions. 

In **CustomTransactions.php**
```
public function typeFooTransactions()
{
    return $this->transactions()->where('some_internal_type', 'foo');
}
```
```
$product->typeFooTransactions();
$product->typeBarTransactions();
// etc...
```

Or do you recommend adding a new table like `product_user_transactions` table with `transaction_id`, `product_id`, `user_id` and `some_internal_type` and use it like,
```
App\Models\ProductUserTransactions::where([
       'user_id' => 1,
       'product_id' => 1,
       'some_internal_type' => 'foo'
]);
```

**Comment by rez1dent3** [comment]
@iamroi Now in databases you can filter by meta (json) field. So you can use this method as well.
https://laravel.com/docs/8.x/queries#json-where-clauses

Any of your options can be used, but the new table option is the safest for future package updates.

**Comment by betysam55** [comment]
> ```
> transfer
> ```

there is a problem here pay method will deposit the amount to the default wallet I need to stop that

**Comment by iamroi** [comment]
@rez1dent3 Thanks! That makes perfect sense. I will probably stick with the new table approach as I don't want to mess with the original tables and very much would like to keep up to date with the package. Do you recommend if I can switch to `6.0.0+alpha1` now as my app will be in development stage for next three months?

Do you think it is ok to add just `currency` column in the `transactions` table? It will be massively helpful for me to automatically `cast` using this package `cknow/laravel-money`. Do you foresee any problem with this in the future package updates?

**Comment by rez1dent3** [comment]
@iamroi 
I do not recommend switching to alpha version, the internal architecture can change at any time. Within 1.5 months there will be a 6.x release, the update usually does not take much time.

As for adding a field, it seems to me superfluous. For you, I have prepared an example of how this can be solved without adding an extra field.

Install the package.
```bash
composer req cknow/laravel-money
```

Overriding the model.
https://github.com/bavix/laravel-wallet/blob/1aa04a2a7db67b61f1fe25116cc1455b510e34a4/tests/Common/Models/TransactionMoney.php#L11-L26

We register a new model in the config.
https://github.com/bavix/laravel-wallet/blob/1aa04a2a7db67b61f1fe25116cc1455b510e34a4/tests/WalletExtensionTest.php#L44

Don't forget to add meta information with every action.
https://github.com/bavix/laravel-wallet/blob/1aa04a2a7db67b61f1fe25116cc1455b510e34a4/tests/WalletExtensionTest.php#L52

Now how to get the Money object.
https://github.com/bavix/laravel-wallet/blob/1aa04a2a7db67b61f1fe25116cc1455b510e34a4/tests/WalletExtensionTest.php#L56-L57

**Comment by iamroi** [comment]
@rez1dent3 Genius! I was way overthinking it 😆 I got it sorted by changing two files. It would be great to get your thoughts on this

In **CustomOperation.php**

```
public function toArray(): array
{
    if(empty($this->meta['currency'])) {
        throw new \Exception("You shall not pass!!");
    }
}
```

In **CustomTransactions.php**

```
public function getAmountAttribute()
{
    return money($this->attributes['amount'], $this->meta['currency']);
}
```

**Comment by rez1dent3** [comment]
@iamroi A good solution, but there is a point. I would advise against defining getter's of native package columns. At a minimum, type hints break, and as a maximum, the complexity increases when the package is updated. I would call the field "money".

```php
public function getMoneyAttribute()
```

PS, Keep in mind one fact, the library works with integers. You need to convert the amount to the required precision.

**Comment by iamroi** [comment]
@rez1dent3 thanks for heads up! I will leave the package columns alone and use different attributes for both `Transaction` and `Wallet` classes.

I love how this package works with integers for safety and it makes my life easier. Also, I find it plays well with the [laravel-money](https://github.com/cknow/laravel-money) package for amount conversions.

You are amazing and I really appreciate the help so far 💯
