### ISSUE TITLE
How do i get single user wallet details

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#239]
please i want to get details for each multiple wallet in a single page just like single blog page

**Comment by rez1dent3** [comment]
What data do you want to display?

**Comment by odion-cloud** [comment]
recent transaction balance of a particular wallet

**Comment by rez1dent3** [comment]
```php
$wallet->transactions()->latest()->first()->amount
```

**Comment by odion-cloud** [comment]
> ```
> $wallet->transactions()->latest()->first()->amount
> ```

thanks works ,please what about last withdraw

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/issues/203

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/issues/187

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
