### ISSUE TITLE
please how to i get this 

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#240]
recent deposit of a wallet ,,,
recent withdraw of a wallet ,,,
Total balance of a wallet ,,,

help we be very grateful please

**Comment by rez1dent3** [comment]
> recent deposit of a wallet ,,,
> recent withdraw of a wallet ,,,
```php
$wallet->transactions()
```

> Total balance of a wallet ,,,
```php
$wallet->balance
```

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
