### ISSUE TITLE
Is it compatible with Laraval 8 AND how can I display the Balance of the logged-in User ???

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [bavix/laravel-wallet#244]
HELLO.

I would like to know:

**1 -** if the Package is functional with Laravel 8 ??? Is it compatible with Laraval 8 ???

**2 -** If so, how can I display the Balance of the logged-in User in my Blade view ???

**3 -** What is the default Balance of the newly registered user who has not yet made a deposit to his Balance ??? How much should the newly registered new user have as a balance ???

Thank you for informing me please.

**Comment by odion-cloud** [comment]
> HELLO.
> 
> I would like to know:
> 
> **1 -** if the Package is functional with Laravel 8 ??? Is it compatible with Laraval 8 ???
> 
> **2 -** If so, how can I display the Balance of the logged-in User in my Blade view ???
> 
> **3 -** What is the default Balance of the newly registered user who has not yet made a deposit to his Balance ??? How much should the newly registered new user have as a balance ???
> 
> Thank you for informing me please.

*it support laravel 8,
*follow this documentation:  https://bavix.github.io/laravel-wallet/#/installation,
automatically every user we have a default balance  0

**Comment by ChegMarcoADVANTECH** [comment]
ok thank you

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
