### ISSUE TITLE
knew user not having default

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#246]
hello i want after user register they should automatically have default wallet ,when ever i create new user they don't have default wallet i have place this 

use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Interfaces\Wallet;

class User extends Model implements Wallet
{
    use HasWallet, HasWallets;
}

but when i register knew user they don't have default wallet ,please what must be the issue any way to create the code to auto create default wallet on register?

**Comment by rez1dent3** [comment]
@odion-cloud hello.
The wallet is created automatically for any actions on the wallet, such as viewing the balance.
```php
$user->balance; // create default wallet
```

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
