### ISSUE TITLE
Hello How do i unconfirm every withdraw

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#254]
i don't want user withdraw to be confirm immediate of there withdrawal process i want admin to confirm the withdraw help please

**Comment by rez1dent3** [comment]
Hello.

To begin with, all transactions can be sent unconfirmed.
https://github.com/bavix/laravel-wallet/blob/780270c42bdb9e4a57366f45148cc83d199bfe41/tests/ConfirmTest.php#L25

And the administrator is already calling the confirmation method.
https://github.com/bavix/laravel-wallet/blob/780270c42bdb9e4a57366f45148cc83d199bfe41/tests/ConfirmTest.php#L29

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
