### ISSUE TITLE
how do i display transaction colum meta varieble without php syntacs

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#256]
when i try to display transaction description ilike this {{$wallet->meta}} it shows like this "description":" reason here "

**Comment by rez1dent3** [comment]
Hello! Here's an example:
```php
$wallet->meta['columnName'];
```

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
