### ISSUE TITLE
DB transaction rollback and Redis balance

### ISSUE THREAD

**Issue by iamroi** [bavix/laravel-wallet#258]
Hi @rez1dent3 !

 I'm using Redis lock to overcome the race conditions. Could you please confirm if the below is expected and always run `refreshBalance` after rollback?

```
DB::beginTransaction();

$wallet->deposit(100);

// something happened in business logic so rolling back
DB::rollBack();


// at this point database `balance` is fine but Redis `balance` is 100


// Redis is happy after doing this
$wallet->refreshBalance();
```

Thanks for your time.

**Comment by rez1dent3** [comment]
Hey, @iamroi. In this case, you manually roll back the database, the library will not know about it. You need to manually recalculate the balance, as you do with the code.

**Comment by iamroi** [comment]
Thanks for confirming @rez1dent3! Sorry another question regarding the `wallet.lock.seconds` config,

As per [Laravel doc](https://laravel.com/docs/8.x/cache#managing-lock), the Lock will be indefinite when a Closure is given so I’m trying to understand the use of `wallet.lock.seconds`

```
Cache::lock('foo')->get(function () {
    // Lock acquired indefinitely and automatically released...
});
```

In `LockService.php`,

https://github.com/bavix/laravel-wallet/blob/4960eb85f916bd962ec8ebbfa78d381157a257e5/src/Services/LockService.php#L37

**Comment by rez1dent3** [comment]
@iamroi You're right about the uncertainty, it all depends on the code. But if you look at the LockProvider interface, then everything falls into place.

```php
/**
 * Get a lock instance.
 *
 * @param  string  $name
 * @param  int  $seconds
 * @param  string|null  $owner
 * @return \Illuminate\Contracts\Cache\Lock
 */
public function lock($name, $seconds = 0, $owner = null);
```

**Comment by iamroi** [comment]
Awesome! Thanks for clarifying @rez1dent3 👍
