### ISSUE TITLE
Find out number of particular products paid for by a user?

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [bavix/laravel-wallet#259]
Hi there! First of all thanks for an awesome package that looks like to have took away a lot of boilerplate code from me to write. I have just met a particular limitation of I may be missing something from the documentation I am not sure. The scenario is as follows:

To commit a purchase from wallet balance, I am doing something similar to below:
```php
$user = App\User::find(1); // implements Customer
$user->deposit(1000);
$item = App\Item::find(1); // implements Product
$cart = app(Cart::class);
$cart->addItem($item, 25);
$user->payCart($cart);
```

The transaction(s) were recorded successfully. Now since the user purchased 25 number of same item and they may purchase more later and so on, I want to know then number of items (of a particular type) they currently have. Something like below:

```php
$user = App\User::find(1); // implements Customer
foreach (App\Item::get() /* implements Product */ as $item) {
    if ($transfer = $user->paid($item, true)) {
        $data['purchases'][] = [
            'id' => $item->id,
            'count' => ???,
        ];
    }
}
```

Can't seem to figure out the `???` part. Can you help?

**Comment by rez1dent3** [comment]
Hey, @vaibhavpandeyvpz.  In fact, the library does not store the quantity, it was not necessary for my tasks. I would advise you to create a statistics table and write this data there.

Here is a library-level solution you can do. But I do not recommend using it.

Add a method (relation) with a wallet (user) to the Item model.
```php
   /**
     * @param int[] $walletIds
     * @return MorphMany
     */
    public function boughtGoods(array $walletIds): MorphMany
    {
        return $this
            ->morphMany(config('wallet.transfer.model', Transfer::class), 'to')
            ->where('from_type', config('wallet.wallet.model', Wallet::class))
            ->whereIn('from_id', $walletIds);
    }
```

And then we use.
```php
$count = $item
    ->boughtGoods([$user->wallet->getKey()]) // pass the ID of the standard wallet
    ->count();
```

I repeat, I highly recommend creating your own statistics table and recording data there.
And don't forget about transactions
```php
        app(DbService::class)->transaction(function () use ($cart, $user) {
            $user->payCart($cart);
            // ...and save my cart stat
        });
```

**Comment by vaibhavpandeyvpz** [comment]
Ah, this looks similar to what I used as workaround (code below) until your help now. Thanks for the `transactions` tip, I was looking for a way to use transactions where I was gifting **many** items to another user and I guess that's it.

```php
$data = [
    'purchases' => [],
];
/** @var Item $item */
foreach (Item::get() as $item) {
    $transfers = $user->transfers()
        ->where('to_type', Item::class)
        ->where('to_id', $item->id)
        ->whereIn('status', ['paid', 'gift'])
        ->count();
    $data['purchases'][] = [
        'id' => $item->id,
        'count' => $transfers,
    ];
}
return $data;
```

Thanks for your tip.
