### ISSUE TITLE
refresh balance not working 

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#264]

**Comment by odion-cloud** [comment]
when i refresh the balance the balance of multiple wallet from controller it thosen work but value shows in database ,this is my logic   

$withdraw->increment('balance',$withdraw->interest_balance * 100);
        $withdraw->wallet->refreshBalance();

        $withdraw->withdraw($withdraw->balance,['description' => $saving->name], false);

**Comment by rez1dent3** [comment]
Hey. You did something very strange. Let's figure this out.
- First thing you get is the wallet, right?
- Why increase the balance using the increment method? Without a confirmation transaction, the balance is not replenished. 
When recalculating, they must return to the value before the increment.
```php
$wallet->balance; // =0
$wallet->increment('balance', 100);
$wallet->refreshBalance(); 
$wallet->balance; // =0
```

Let's figure it out, what do you expect with such a case?

**Comment by odion-cloud** [comment]
what i what to do is when user click withdraw the  interest should be added to the total amount and withdraw without confirming but the balance after incrementing the  interest with the total balance the balance still return the old balance but in database the increment value shows ,how do i do this pls logic

**Comment by rez1dent3** [comment]
You will have to withdraw from two wallets at the same time. Or, during withdrawal, move money to one wallet and make a transfer.

Example:
```php
// User wants to withdraw 10200
$withdrawAmount = 10200;

app(DbService::class)->transaction(function () use ($depositWallet, $interestWallet, $withdrawAmount)  {
    $depositWallet->balance; // 10000
    $interestWallet->balance; // 750

    $difference = $withdrawAmount - $depositWallet->balance; // 200
    // checks ...
    $interestWallet->transfer($depositWallet, $difference);
    return $depositWallet->withdraw($withdrawAmount);  
});
```

It seems to me that this problem can be solved much easier.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
