### ISSUE TITLE
comfirm transaction

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#265]
when admin confirm trasaction the user balance was still having the amount , i wanted when user place withdrawal request with the amount once admin approve the payment the user balance should be debit by the amount requested

**Comment by rez1dent3** [comment]
Hello.

Funds are debited at the time of confirmation.
https://github.com/bavix/laravel-wallet/blob/4960eb85f916bd962ec8ebbfa78d381157a257e5/tests/ConfirmTest.php#L23-L31

Specify the question.

**Comment by odion-cloud** [comment]
this is how i write the confirm logic

$conf = Transaction::where('id','=',$trid)->first();
        $conf->update(
         ['confirmed' =>  true], 
          ); 
       $conf->save();
please let me know your way on this ,i want it when admin confirm any withdraw the money should be debit from he wallet

**Comment by odion-cloud** [comment]
this is what i get when i change logic to this
```
Error
You are not the owner of the wallet
```
this is the code

$conf = Transaction::where('id','=',$trid)->first();
$conf->confirmed; // bool(false)
$user->confirm($conf);

**Comment by rez1dent3** [comment]
@odion-cloud If confirmed by a user, then a standard wallet should have been used.
Better to confirm with a wallet.
```php
$wallet->confirm($trans);
```

I have this code covered with unit tests. I am sure that this functionality works in the library.

**Comment by odion-cloud** [comment]
thank it work now!
