### ISSUE TITLE
Caching the `Wallets` query

### ISSUE THREAD

**Issue by iamroi** [bavix/laravel-wallet#271]
Hey @rez1dent3!! Excited for the 6.x :) 

Could you please confirm if the below method is a correct way to cache and flush wallets query? I'm using this package [laravel-eloquent-query-cache](https://github.com/renoki-co/laravel-eloquent-query-cache) where you can cache on query level. 

For example, route: `user/balance` is called on every page visit and would like to cache for a day for each user using tags:

In `BalanceController@index`
```
$user->wallets()
    ->cacheFor(now()->addDays(1))
    ->cacheTags(["user:{$user->id}:wallets"])
    ->get();
```

My understanding is the only place we modify the `balance` is after **withdraw** and **deposit**. So could I do this in custom `MyCommonService.php` ?

```
public function forceWithdraw(Wallet $wallet, $amount, ?array $meta, bool $confirmed = true): Transaction
{
    $result = parent::forceWithdraw($wallet, $amount, $meta, $confirmed);

    // when the holder is 'user', flush the wallets cache
    if($wallet->holder_type == User::class) {
        User::flushQueryCache(["user:{$wallet->holder_id}:wallets"]);
    }

    return $result;
}

public function deposit(Wallet $wallet, $amount, ?array $meta, bool $confirmed = true): Transaction
{
    // same concept as above
}
```

Would love to hear your thoughts and check if this is normal. Thanks for your time.

**Comment by rez1dent3** [comment]
@iamroi Hey. I can easily come up with a case when this cache is not up to date. Here's a simple example:
```php
$transaction = $wallet->deposit(1000, ['desc' => 'unconfirmed'], false); // Flushed the cache
// ....
$wallet->confirm($transaction); // We confirm the transaction and our cache is no longer up to date
```

I do not know your case, perhaps you only use deposits and withdrawals, then your option will suit you

**Comment by iamroi** [comment]
@rez1dent3 Thanks. I completely missed that. I can see myself using the `confirm` method in future. 

It looks like I can cover that feature by doing the same on `addBalance`. 

```
public function addBalance(Wallet $wallet, $amount): bool
{
    $result = parent::addBalance($wallet, $amount);

    if(method_exists($wallet->holder, 'flushWalletsCache')) {
        $wallet->holder->flushWalletsCache();
    }

    return $result;
}
```

It's working well so far but it would be great to get your advice on any other corner cases.

**Comment by rez1dent3** [comment]
1. I cannot guarantee that this type of caching will work well in newer versions of the package.
2. When accessing holder, you make a request to the database, every time.
```php
$wallet->holder
```
3. It is very difficult for me to imagine a case when it is necessary to cache entire wallets. Perhaps in the future, I will think about this question.

And remember, by making changes to the code you complicate the update process for yourself)

**Comment by rez1dent3** [comment]
4. Race condition. If two requests for processing come to the server at the same time and there is no common side, for example, redis, then the result will not be predictable. In addition to caching, it is worth thinking about the atomicity of the operation.
This problem is partially solved with the help of an additional package: https://github.com/bavix/laravel-wallet-vacuum
You just need to change the cache driver to redis. For the best effect.

**Comment by iamroi** [comment]
@rez1dent3 Thank you for your advice.

In my use case, I need to display of the user's wallets(currencies) and their balance in header. Similar to [this screenshot](https://prnt.sc/vggzz9). As this is displayed on every page, it's firing the same wallets query on every visit. Caching this for just 10mins would be a great improvement. Do you see this use case as normal from your perspective?

1. Thanks for confirming that it could be an issue in newer versions. I will try to find a workaround in future or remove my caching changes completely.

2. Regarding `$wallet->holder` request to the database, you are right on the `addBalance` method! I will switch back to using `holder_type` and `holder_id` instead.

3. https://github.com/bavix/laravel-wallet-vacuum is an awesome addition and I'm already using it :) I'm working on a way to test many race conditions so I will keep you posted on my results.

**Comment by rez1dent3** [comment]
Nice caching option, but I cannot guarantee compatibility with future versions of the package.

**Comment by iamroi** [comment]
All good @rez1dent3 :) Thanks for your help!
