### ISSUE TITLE
force confirm

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#272]
please logic to force withdraw this we help a lot, i want to be able to force confirm a withdraw ,when user force withdraw admin should be able to force confirm , without any insufficiency balance

**Comment by rez1dent3** [comment]
Hello.
Haven't tried this method?
https://github.com/bavix/laravel-wallet/blob/4960eb85f916bd962ec8ebbfa78d381157a257e5/src/Traits/CanConfirm.php#L105

**Comment by odion-cloud** [comment]
it worked thanks
