### ISSUE TITLE
brick/math版本问题

### ISSUE THREAD

**Issue by zhmuyu** [bavix/laravel-wallet#273]
能否将 brick/math的版本降低至^0.8,目前laravel默认使用ramsey/uuid#4.1.0，仅支持brick/math^0.8,ramsey/uuid#4.1.1才支持0.9！

**Comment by rez1dent3** [comment]
Hey. Can you write in English?

**Comment by zhmuyu** [comment]
aravel 8 uses ramsey/uuid#4.1.0, which only supports brick/math^0.8, and ramsey/uuid#4.1.1 supports brick/math 0.9.0, so it cannot be installed. Can you reduce the brick/math version?

**Comment by rez1dent3** [comment]
Hi. In version 5. x there is no `brick/math`, it is optional, any version. 

Starting with version 6. x (it is still in development), you need version 0.9.* and higher. In version 0.8.* there was a bug that interferes with the new version.

Laravel 8 works fine with brick/math 0.9, I have no problems. You may have some dependency in the project that uses an old version of brick and you can't update.
