### ISSUE TITLE
Target class [Bavix\Wallet\Simple\BCMath] does not exist.

### ISSUE THREAD

**Issue by vandadsoft** [bavix/laravel-wallet#274]
Laravel 8.14
Package Version: 6.0.0+alpha1

Illuminate\Contracts\Container\BindingResolutionException
Target class [Bavix\Wallet\Simple\BCMath] does not exist.

**Comment by rez1dent3** [comment]
Hey, @vandadsoft.

These classes have been removed. 6.x is not stable yet, I haven't written the update documentation yet.

You should update the config https://github.com/bavix/laravel-wallet/blob/3a36a963caab2dfd6a7a88a073523712fbd3bb78/config/config.php#L34

**Comment by rez1dent3** [comment]
https://bavix.github.io/laravel-wallet/#/upgrade-guide?id=_5xx-%e2%86%92-60x

**Comment by rez1dent3** [comment]
If there are questions, then create a new issue.  I'll close it.
