### ISSUE TITLE
Deposit meta

### ISSUE THREAD

**Issue by abdosaeedelhassan** [bavix/laravel-wallet#277]
Hi,  i did next

1- in user model: implements Wallet, WalletFloat and use HasWalletFloat

2- $this->user->depositFloat($this->balance, [
            'balance' => $this->balance,
            'description' => $this->description,
            'created_by' => auth()->user()->id,
            'timestamp' => date('Y-m-d H:i:s', time()),
        ]);

when i did
   return User::with('wallet')->where('id',1)->get();

i received next

"wallet": {
"id": 1,
"holder_type": "App\\Models\\Auth\\User",
"holder_id": 1,
"name": "Default Wallet",
"slug": "default",
"description": null,
"meta": [],
"balance": "1000",
"decimal_places": 2,
"created_at": "2020-11-16T12:50:05.000000Z",
"updated_at": "2020-11-16T14:38:02.000000Z"
}

i don't know why meta data not registered, i need help

**Comment by rez1dent3** [comment]
Hello. With deposit/withdraw, you add transaction data.
```php
$wallet->depositFloat(100, [/*any meta...*/]);
```

![Screenshot from 2020-11-16 21-34-48](https://user-images.githubusercontent.com/5111255/99293347-97da6100-2853-11eb-8f9e-4c933fff59a6.png)

**Comment by abdosaeedelhassan** [comment]
it worked for me like that, also shown for me meta added but when i did
return User::with('wallet')->where('id',1)->get();
no meta shown for the user, my question in different way, how can i get all user wallet translations meta data?

**Comment by rez1dent3** [comment]
@abdosaeedelhassan 
What you display is wallet meta data. They are needed to write extensions. For example, in version 6.x I store wallet currency data in the meta.

```php
$usdWallet = $user->createWallet([
   'name' => 'USD Wallet',
   'meta' => ['currency' => 'USD'],
]);

$usdWallet->meta; // ['currency' => 'USD']
```

And here is the output of wallet transactions.
```php
foreach ($user->transactions()->cursor() as $transaction) {
    $transaction->meta; // Transaction metadata
}
```

**Comment by abdosaeedelhassan** [comment]
$user->transactions()->get()
yes that what i am looking for, thank you for your attention.
