### ISSUE TITLE
Column not found: 1054 Unknown column 'meta'

### ISSUE THREAD

**Issue by vandadsoft** [bavix/laravel-wallet#278]
Hi
im using Laravel 8 and laravel-wallet 6

used Wallet and HasWallet for a model
and when i try to get balance or some else ...
i got an error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list' (SQL: insert into `wallets` (`holder_id`, `holder_type`, `name`, `slug`, `meta`, `balance`, `updated_at`, `created_at`) values 

also there is no new wallet created for this model and all columns are empty 
migrations are healthy

any solution?

**Comment by rez1dent3** [comment]
Hello.
Migration was added in 6.x. Tell me, did you do it?
2020_10_30_193412_add_meta_wallets_table.php

**Comment by vandadsoft** [comment]
> Hello.
> Migration was added in 6.x. Tell me, did you do it?
> 2020_10_30_193412_add_meta_wallets_table.php

Solved Thanks

**Comment by matinwd** [comment]
HI same here
but in may case it shows error when i upgraded composer

**Comment by vandadsoft** [comment]
Hey
this error because of 2020_10_30_193412_add_meta_wallets_table.php is not migrated!
try to publish vendors of package and then clean migrate

**Comment by vandadsoft** [comment]
> HI same here
> but in may case it shows error when i upgraded composer

Hey
this error because of 2020_10_30_193412_add_meta_wallets_table.php is not migrated!
try to publish vendors of package and then clean migrate

**Comment by matinwd** [comment]
hmm thanks.
