### ISSUE TITLE
Withdrawal not updating balance

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [bavix/laravel-wallet#279]
Hi @rez1dent3 Since your last advise, I was happily using this package until now when a client has brought a weird issue to me. I am sorry to bother you again but honestly I could not figure it out on my own so had to ask you.

I'll explain the scenario.

```php
$user = App\User::find(1); // implements Customer, balance = 0
$item = App\Item::find(1); // implements Product, price = 10

/* The $user has already paid for $item earlier */

$cart = app(Bavix\Wallet\Objects\Cart::class);
$cart->addItem($item, 1);
/* The user balance is 0 */
$user->refundCart($cart);
/* The user balance is 10 */
$user->withdraw(10);
/* The user balance must be 0, and it is indeed 0 if I do $user->balance below */
```

But the database still has wallet balance as 10 and every time later I retrieve the `$user->balance`, it returns 10 until I manually call  `$user->wallet->refreshBalance()`.

Calling the `Bavix\Wallet\Interfaces\Wallet::refreshBalance` works but the `Bavix\Wallet\Interfaces\Wallet::withdraw` function shouldn't update it automatically? The weirder thing is even if I call `$user->wallet->refreshBalance()` right below withdrawal, it won't help. But if I call it in separate request, it works. Is this a threading issue? If yes, please elaborate why.

My best guess is an uncommitted transaction after withdrawal.

**Comment by rez1dent3** [comment]
Hey. I will try to reproduce your problem, I will answer within two days.

**Comment by rez1dent3** [comment]
@vaibhavpandeyvpz I confirm this is a bug. Was able to reproduce.

**Comment by vaibhavpandeyvpz** [comment]
I will await your fix and I am in hurry. You can work on it when you have ample time. Thanks for a great open source project. 🙂

**Comment by rez1dent3** [comment]
@vaibhavpandeyvpz I have released releases that fix this bug.
Tags: [5.5.1](https://github.com/bavix/laravel-wallet/tree/5.5.1), [6.0.1](https://github.com/bavix/laravel-wallet/tree/6.0.1)

**Comment by vaibhavpandeyvpz** [comment]
You were too quick. Thanks for you help again.

**Comment by rez1dent3** [comment]
Let it be open for now. I will check the result for a couple of days

**Comment by vaibhavpandeyvpz** [comment]
Sure. I will also update my codebase tomorrow and review the state.

**Comment by rez1dent3** [comment]
@vaibhavpandeyvpz My problem went away completely, but how about you?

**Comment by vaibhavpandeyvpz** [comment]
OK. I'll just update my dependencies and let you know if it works as expected.

**Comment by vaibhavpandeyvpz** [comment]
@rez1dent3 Now it's even saddening I cannot use the update since the package dependencies does not align with `illuminate/database` package it depends upon. The Laravel 6.x LTS requires PHP 7.2 but the 5.5.x versions for this package require PHP 7.3 so the recent versions do not actually support Laravel 6.x and you should remove `illuminate/database` 6.x from composer.json now. Until my clients could all upgrade to PHP 7.3/4, I'll stick with my workaround. Closing this finally as you have tested it fixed the mentioned issue and I cannot test it.
