### ISSUE TITLE
Duplicate prevention?

### ISSUE THREAD

**Issue by deantheiceman** [bavix/laravel-wallet#290]
If I use this in a job is there anyway to prevent duplicate withdrawals if the job fails?

Is there perhaps support to link the withdrawal to an external model, so if the withdraw already exists it can be ignored? Or like an unique key/id to prevent duplicate transactions?

**Comment by rez1dent3** [comment]
Hello. 
The package does not and will not have duplicate protection, the developer must take care of this on his side.

I would suggest that you wrap the code in a transaction. More or less like this:
```php
use Bavix\Wallet\Services\DbService;
...
app(DbService::class)->transaction(function () use ($wallet) {
    $wallet->deposit(1000); // we are performing an operation
    // ... here is your code
});
```
In this case, the database will rollback if the transaction fails.

**Comment by deantheiceman** [comment]
Thanks for the reply. Is your Db Service any different to laravel's default DBTransaction?

**Comment by rez1dent3** [comment]
@deantheiceman Now it is not different, but there will be a difference when the wallet connection will be on a different connection.

**Comment by deantheiceman** [comment]
Thanks!
