### ISSUE TITLE
Pls is it possible to request a transfer ?

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#291]
i want user to request transfer from admin, just like withdraw ,pls logic !

**Comment by rez1dent3** [comment]
Hello. I would conduct an operation without confirmation with meta information.
```php
$user->withdraw(100, ['request' => true], false); 
```

And the administrator in the admin panel already moderates and filters unconfirmed operations and processes them.

But for your case, it's better to add the `request` column to the table. Example #105
