### ISSUE TITLE
how do i get transfer history

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#293]
hello pls i want to get the transfer history but transfer history those not return amount that was transfer ,this is what i did

 $transfers = Transfer::all();

any way i can get all transfer history and also the amount transferred? logic

**Comment by rez1dent3** [comment]
Hello. I did not understand your task, but it seems to me that you will find the answer here: https://github.com/bavix/laravel-wallet/issues/234 https://github.com/bavix/laravel-wallet/issues/259 https://github.com/bavix/laravel-wallet/issues/237 https://github.com/bavix/laravel-wallet/issues/142 https://github.com/bavix/laravel-wallet/issues/187 https://github.com/bavix/laravel-wallet/issues/162
