### ISSUE TITLE
Issue while installing packagae from composer

### ISSUE THREAD

**Issue by rashimaery-dev** [bavix/laravel-wallet#296]
Hello, I am getting this issue when trying to installl packagae: 

Problem 1
    - bavix/laravel-wallet-vacuum[1.0.0, ..., 1.0.1] require bavix/laravel-wallet ^6.0 -> satisfiable by bavix/laravel-wallet[6.0.0, 6.0.1, 6.0.2].
    - bavix/laravel-wallet[6.0.0, ..., 6.0.2] require illuminate/database ^6.0|^7.0|^8.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bavix/laravel-wallet-vacuum ^1.0 -> satisfiable by bavix/laravel-wallet-vacuum[1.0.0, 1.0.1].

-----------------------------------------------------------------
Can someone guide me what needs to be done here. Thanks!

**Comment by rez1dent3** [comment]
Hey. You need your composer.json and the command with which you perform the installation.
