### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by 7838099724** [bavix/laravel-wallet#299]
Hello, I am new at laravel-wallet and want to install it but don't know how can I  is there anyone can help me to install larawel wallet in ubuntu 18

**Comment by rez1dent3** [comment]
Hello. Package install:
```bash
composer req bavix/laravel-wallet
```

PS,
https://getcomposer.org/doc/01-basic-usage.md
https://laravel.com/docs/8.x/installation

**Comment by itsaxay** [comment]
@7838099724 You can check documentation -

https://bavix.github.io/laravel-wallet/#/installation
