### ISSUE TITLE
How Can I access it via brower

### ISSUE THREAD

**Issue by 7838099724** [bavix/laravel-wallet#300]
Hello, I have installed it and trying to access it from browser but any port is not added in service so let me tell how can I access it from browser.

**Comment by itsaxay** [comment]
@7838099724 laravel-wallet is not ui package. you cannot get any ui included.

**Comment by rez1dent3** [comment]
Hello. Everything is correct. The package is a development kit for laravel. All logic, UI is developed by the developer. The package only makes development easier.
