### ISSUE TITLE
How do i stop it from creating default wallet for user?

### ISSUE THREAD

**Issue by odion-cloud** [bavix/laravel-wallet#303]
i want to be creating the wallet my self , i don't want the package to automatically generate wallet for user how do i make this happen,pls

**Comment by rez1dent3** [comment]
@odion-cloud hello. I was unable to reproduce your problem. Most likely you are using the library incorrectly. Added the appropriate unit test.

**Comment by odion-cloud** [comment]
i am using it correctly, everything works just fine as i follow the doc, but i do not want user to have default wallet ,i want them to create a wallet by them self, when user registration it automaticall give them default wallet ,i want to disabled the default wallet option!

**Comment by rez1dent3** [comment]
@odion-cloud As you can see from the example, the wallet is not created by default.

https://github.com/bavix/laravel-wallet/blob/bbdc0bf4531a04a9eef4144e1523c84df4e4ba63/tests/MultiWalletTest.php#L52-L70

**Comment by odion-cloud** [comment]
the moment user register my app when i check balance with this code

**Comment by odion-cloud** [comment]
they is also a default wallet configuration in config/wallet.php

**Comment by rez1dent3** [comment]
I talked about this. Short calls automatically create a default wallet, this cannot be disabled.  Use the code from the example above, it will solve your problem
