### ISSUE TITLE
Error before creating default Wallet

### ISSUE THREAD

**Issue by anubra266** [bavix/laravel-wallet#305]
Anytime  I create my model, this error is thrown
```js
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default' for key 'wallets_slug_unique' (SQL: insert into `wallets` (`holder_id`, `holder_type`, `name`, `slug`, `meta`, `balance`, `updated_at`, `created_at`) values (2, App\Models\Account, Default Wallet, default, [], 0, 2021-02-27 14:31:32, 2021-02-27 14:31:32))
```

But the wallet still gets created.

**Comment by rez1dent3** [comment]
Hello.  More information needed.  According to the data that you sent the problem is on your side.

**Comment by anubra266** [comment]
I have an Account model, which implements `Wallet` and uses Trait `HasWallet`
So by default, any new instance of this model. i.e. creating a new Account creates a default Wallet.
That's where I get this error, 
And I don't even know what it means.

**Comment by rez1dent3** [comment]
I need information on how can I reproduce your problem. Maybe you can make a test project on github so I can look at the code and give you some tips.

**Comment by anubra266** [comment]
@rez1dent3  Thanks I resolved this by starting all over.
Is there a way to set a name for the default wallet, when it's about to be created?

**Comment by rez1dent3** [comment]
Of course. Everything is configurable.

https://github.com/bavix/laravel-wallet/blob/master/config/config.php#L117

**Comment by anubra266** [comment]
@reedknight I meant creating the name at runtime.
I want the default wallet's name to be the name of the user.

**Comment by rez1dent3** [comment]
I have a suspicion that you don't need the default wallet.
https://github.com/bavix/laravel-wallet/blob/5136b3c4feda1641995f51305b55d4f8e02f4ec1/tests/MultiWalletTest.php#L51-L77

But if you still need it, then you need to look in this direction. I think there will be many problems in your approach.
https://github.com/bavix/laravel-wallet/blob/5136b3c4feda1641995f51305b55d4f8e02f4ec1/src/Traits/MorphOneWallet.php#L20-L31

**Comment by anubra266** [comment]
Right,how do I just disable creating a default wallet
