### ISSUE TITLE
How to confirm Withdraw Transaction

### ISSUE THREAD

**Issue by MonMohon** [bavix/laravel-wallet#311]
user request to withdraw amount from wallet.
$user->withdraw( $widthdraw, ['description' => 'unconfirmed'], false );

next, Admin to confirm withdraw transaction
I use following code to confirm Transaction

`use App\Models\User;`
`use Bavix\Wallet\Models\Transaction;`
```
public function confirm( $id ) {
    $transaction = Transaction::find( $id );
    $trans = DB::table( 'transactions' )->select('payable_id')->find($id);
    $buyer=User::find( $trans->payable_id );
    $wallet = $buyer->wallet;
    $wallet->confirm($transaction);
}
```

but failed to confirm

**Comment by rez1dent3** [comment]
Hello, @MonMohon.
You don't need so many queries to the database.
```php
$transaction->wallet->confirm($transaction);
```

**Comment by MonMohon** [comment]
my update code
```
public function confirm( $id ) {
    $transaction = Transaction::find( $id );
    $transaction->wallet->confirm($transaction);
}
```
Bavix\Wallet\Exceptions\ConfirmedInvalid
The translation has already been confirmed

![image](https://user-images.githubusercontent.com/304477/111858579-1fe68980-8960-11eb-8c6a-4eaf72850242.png)

**Comment by rez1dent3** [comment]
@MonMohon This is a correct error. It informs you that the transaction has already been confirmed and it is not possible to confirm the confirmed transaction.

**Comment by MonMohon** [comment]
ok, but the wallet balance not update after confirm

1) Admin
2) User->wallet
user request to withdraw
admin confirm the withdraw
once admin confirm user wallet balance need to update right.

thank you

**Comment by MonMohon** [comment]
> @MonMohon This is a correct error. It informs you that the transaction has already been confirmed and it is not possible to confirm the confirmed transaction.

I check DB
Table: transactions
Field: confirmed is still 0

**Comment by rez1dent3** [comment]
At the moment I can’t tell you anything. Need information on php version, database. Better yet, you prepare an example and post it on github (dockerfile + laravel).

I don't see any problems on the library side, the confirmation functionality is covered by unit tests.

---
If you do not want to handle errors in try/catch, then you can use safeConfirm.
```php
$transaction->wallet->safeConfirm($transaction);
```
Attention, the safe confirm method calls confirm. Those mistakes are all hidden.
```php
try {
    $transaction->wallet->confirm($transaction);
} catch (BalanceIsEmpty $e) {
    // Empty balance
} catch (InsufficientFunds $e) {
    // insufficient funds
    // Chances are you get here.
} catch (ConfirmedInvalid $e) {
    // The transaction has already been confirmed
} catch (WalletOwnerInvalid $e) {
    // The non-owner of the transaction confirms the transaction
}
```

---
Perhaps you get an error only when withdrawing money from your wallet. This is possible if, as a result of the confirmation, the user's balance is negative. In this case, you need to call the `forceConfirm` method.
```php
try {
    $transaction->wallet->forceConfirm($transaction);
} catch (ConfirmedInvalid $e) {
    // The transaction has already been confirmed
} catch (WalletOwnerInvalid $e) {
    // The non-owner of the transaction confirms the transaction
}
```

@MonMohon FYI

**Comment by MonMohon** [comment]
thanks all fix
