### ISSUE TITLE
How to store transactionable data ?

### ISSUE THREAD

**Issue by vanthao03596** [bavix/laravel-wallet#314]
In my application, i want store detail of each withdraw, deposit, payment to single table. How i can to that with our package. I think i can add transactionable_type and transactionable_id to transactions table

**Comment by rez1dent3** [comment]
Hello. Details are needed.
And why can't you do this: #310 #240 #203 #198

**Comment by vanthao03596** [comment]
In my application, transaction wallet mean log change of wallet and dont have status field. I store detail to another table with status field. After status change to completed i will insert transactions. How do you think @rez1dent3

**Comment by rez1dent3** [comment]
What is your task? What are you trying to do? Why can't I create unconfirmed transactions? I do not understand the essence of your problem and need details.

**Comment by vanthao03596** [comment]
I will build my own package. Thanks anyway
