### ISSUE TITLE
encrypt wallets table->balance

### ISSUE THREAD

**Issue by farshidahmadianpin** [bavix/laravel-wallet#315]
hey there,
is Necessary to encrypt data in database table?
and how can i encrypt and decrypt wallets table balance col with getter and setter in Wallet model?
how can i publish wallet model?

**Comment by rez1dent3** [comment]
Hello. I can't imagine the task for which it is needed, but you can do it. You will have to implement the `Bavix\Wallet\Interfaces\Storable` interface and connect it
