### ISSUE TITLE
Passing additional meta info with pay() or refund() method

### ISSUE THREAD

**Issue by xihad76** [bavix/laravel-wallet#318]
Firstly, A big thanks to the contributors of this wonderful project.
I would like to know how I can pass meta info while using $wallet->pay($item) method. I understand that the meta info is fetched from getMetaProduct() method of the item while executing any item related transaction. But my requirements are I need to tag every payment with a transaction type. I am trying to create transaction history for individual user, and I need to add some additional meta for the purpose. For example, I would like to add meta 'transaction_type' => 'purchase' with the user 'withdraw' transaction when the user pays for an item. In the similar fashion i would like to add 'transaction_type' => 'refund' to deposit transaction of the user when a refund is made from an item back to the user. 
Thanks again!

**Comment by rez1dent3** [comment]
Hello. At the moment this is not possible, only with crutches. For a good solution to the task, you need to change the contract (Customer). I had plans to update the library, but at the moment there is not enough free time.

If there is a custom meta information for payments and returns, it will not be in the near future.


--- 
wild crutch
1. Start a class in which the meta-information is written before the operation;
2. Inside getMetaProduct read information from this class and return it;

Unfortunately, there are no other ways.

**Comment by xihad76** [comment]
Thanks for replying. 
Are you accepting pull request? In that case I may try to update the Customer contract as I will need to work on this anyway. Otherwise I will go for the hack you mentioned (writing a class or introducing a meta property in my item model)

**Comment by rez1dent3** [comment]
Yes, if it does not break the main logic of work and all documentation with tests will be updated. 

Maybe there will be moments on the code review that I will ask to correct.

**Comment by xihad76** [comment]
> Yes, if it does not break the main logic of work and all documentation with tests will be updated.
> 
> Maybe there will be moments on the code review that I will ask to correct.

Thanks. I will give it a try.

**Comment by rez1dent3** [comment]
@xihad76 See #323 

Added the ability to add meta information without changing the contract. In the 7th version of the package I will try to add it to the contract.

Add the cart and add products and meta information to the cart.
```php
use Bavix\Wallet\Objects\Cart;
```

Purchase example:
```php
        $cart = app(Cart::class)
            ->addItems([$product])
            ->setMeta(['type' => 'pay']);
        
        $buyer->payCart($cart);
```

Example of a purchase return:
```php
        $cart = app(Cart::class)
            ->addItems([$product])
            ->setMeta(['type' => 'refund']);
        
        $buyer->refundCart($cart);
```

**Comment by rez1dent3** [comment]
Tag 6.1.0

**Comment by xihad76** [comment]
> @xihad76 See #323
> 
> Added the ability to add meta information without changing the contract. In the 7th version of the package I will try to add it to the contract.
> 
> Add the cart and add products and meta information to the cart.
> 
> ```
> use Bavix\Wallet\Objects\Cart;
> ```
> 
> Purchase example:
> 
> ```
>         $cart = app(Cart::class)
>             ->addItems([$product])
>             ->setMeta(['type' => 'pay']);
>         
>         $buyer->payCart($cart);
> ```
> 
> Example of a purchase return:
> 
> ```
>         $cart = app(Cart::class)
>             ->addItems([$product])
>             ->setMeta(['type' => 'refund']);
>         
>         $buyer->refundCart($cart);
> ```

That's wonderful! Thank a lot for your time and effort!
