### ISSUE TITLE
Is there a way to share a wallet between users? 

### ISSUE THREAD

**Issue by sathio** [bavix/laravel-wallet#329]
I see you have `holder_type`  on your wallet model, now, suppose i wish to have a shared wallet between members of a team. 
Is there a way to achieve this right now? I've looked at the code and documentation but I don't see it.

**Comment by sathio** [comment]
oh that's clever, I see I can just save from Team model and it will get its name on `holder_type` I guess I'll just have to load from allowed "team" wallets on users and be done with it. very nice!

**Comment by rez1dent3** [comment]
Yes, that's right. A shared wallet needs to be fumbled not through a user, but through a main relationship
