### ISSUE TITLE
Using in a high write enviroment

### ISSUE THREAD

**Issue by atymic** [bavix/laravel-wallet#330]
The currently locking implementation is great for preventing race conditions when wallets are accessed in quick successions infrequently, but won't work in high write load.

In our case, we are billing for API operations. Psudeocode:

```php
$bal = $user->balance; // say 10

if ($bal <= 0) { return; }

$app->doBilledOperation();

// withdrawal, even if bal is below 0 to make sure they are billed
$user->forceWithdraw(10);
```

The issue is that with high load - say 50 concurrent threads (queue executing jobs), we end up failing to withdraw due to the locks, and everything breaks.

Would it not make sense to make `forceWithdraw` a atomic operation? i.e. execute the query:

```sql
UPDATE wallets
SET balance = balance - 10 #or plus, depending on op
WHERE id = x;
```

Which would force the database to do the update atomically?

**Comment by rez1dent3** [comment]
Hello. You need to use redis and the extension https://github.com/bavix/laravel-wallet-vacuum
