### ISSUE TITLE
Is there a way to programmatically name product's wallet?

### ISSUE THREAD

**Issue by sathio** [bavix/laravel-wallet#331]
I see wallets of products getting created automatically, but I don't like the way they are named and I can't understand if there is a way to change their name. I see that products use hasWallet rather than hasWallets which makes sense, but regardless of this, is there a way to -for example- inherit product's name as name and slug? thanks

**Comment by rez1dent3** [comment]
Hello. A default wallet is created. Settings can be set here
https://github.com/bavix/laravel-wallet/blob/392906f7f9e7db38e23fd9f4976e615b6d43885a/config/config.php#L117-L121

**Comment by sathio** [comment]
right, I saw that, but I want it to inherit programmatically the $product->name

**Comment by rez1dent3** [comment]
You have two ways to go:
- redefine the part of the code that is responsible for creating the wallet and throwing it product.name;
- update wallet.name after creating a wallet, the main thing is that wallet.slug matches the one in the config;
