### ISSUE TITLE
[Question] How to get the user of a particular transaction?

### ISSUE THREAD

**Issue by a-ssassi-n** [bavix/laravel-wallet#334]
My **User** model implements Wallet

When I do the following:

```
$transactions = Transaction::all();
foreach($transactions as $transaction)
{
    // here I need to get the Modal that made the transaction i.e the User from the recorded payable_id
}
```

Of course, I could `$user = User::find($transaction->payable_id)` but is there any way to lazyload the model?

**Comment by rez1dent3** [comment]
Hello. Mm. What you give as an example is lazy load. Maybe you need eager loading?
```php
$transactions = Transaction::with('payable')->all();
foreach($transactions as $transaction) {
    $user = $transaction->payable;
}
```

Two queries will go to the database.
```sql
SELECT * FROM transaction;
SELECT * FROM users WHERE id IN (...);
```

PS, If you still need lazy loading, then no "with".
```php
$transactions = Transaction::all();
foreach($transactions as $transaction) {
    $user = $transaction->payable;
}
```
But then N + 1 request will go to the database.
```sql
SELECT * FROM transaction;
SELECT * FROM users WHERE id=1;
SELECT * FROM users WHERE id=2;
....
```

https://laravel.com/docs/8.x/eloquent-relationships#eager-loading

**Comment by a-ssassi-n** [comment]
Thank you for your quick response. This solves my problem.
