### ISSUE TITLE
Transaction Detail/Reference Field

### ISSUE THREAD

**Issue by fignewton** [bavix/laravel-wallet#335]
Is there a way currently to add some extra information to a transaction? Either some details about the reason for a transaction or a reference to another model that is related to the transaction. something like:

`$user->withdraw(100, "Registration Fee"); //To denote what the withdrawal was for `

 or

`'$user->withdraw(100, $ticket->id); //To reference a $ticket model as the reason for the transaction`

The reference or detail would then be part of the fields returned when one ran:

`$wallet->transactions();`

If there is no such feature currently I'd be happy to make an attempt at a pull request, though it would be my first contribution to any open source project so it may be buggy

**Comment by rez1dent3** [comment]
Hello.
You can add metadata to a transaction.
```php
$transaction = $user->withdraw(200, [
    'description' => 'Registration Fee',
    'ticket_id' => $ticket->id,
]);

var_dump($transaction->meta);
```
I think this functionality will suit you.

**Comment by fignewton** [comment]
Thank you. This works for me.
