### ISSUE TITLE
Transfer between wallets

### ISSUE THREAD

**Issue by d3vilsn0w** [bavix/laravel-wallet#337]
$aWallet = $user->getWallet('A$');
$bWallet = $user->getWallet('B$');
$bWallet->transfer($aWallet, 1000);
        
Now that, Wallet A have 2 decimals and Wallet B have 5 decimals, It deducts 0.01 from the wallet B, but adds 10.00 to the wallet A. Any solution instead of using manual transfers?

**Comment by d3vilsn0w** [comment]
Tried TransferFloat too, same result.

**Comment by rez1dent3** [comment]
Hello. I do not understand your problem, can you give more details?
Describe your steps, outcome and expectation.
