### ISSUE TITLE
Is there a way to get all transactions from a particular user?

### ISSUE THREAD

**Issue by alilakrakbi** [bavix/laravel-wallet#339]
I need to show to the user his last transaction, and the time they were done? is there a way to pull the data?

I have checked the database and there is a uuid but there is no way to identify the user from the uuid?

**Comment by rez1dent3** [comment]
Hello. The package does not have a binding to the user, it has a binding to the wallet and the owner of the wallet (can be any object).

See: https://github.com/bavix/laravel-wallet/issues/334, https://github.com/bavix/laravel-wallet/issues/198, https://github.com/bavix/laravel-wallet/issues/191, https://github.com/bavix/laravel-wallet/issues/187

**Comment by alexstewartja** [comment]
> 
> 
> Hello. The package does not have a binding to the user, it has a binding to the wallet and the owner of the wallet (can be any object).
> 
> See: #334, #198, #191, #187

I think we can all agree this feature now requires a PR. Are you working on adding it @rez1dent3 ?

**Comment by rez1dent3** [comment]
@alexstewartja The package stores all transactions.  I do not understand what feature you are talking about
