### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by MoeCasts** [bavix/laravel-wallet#34]
I can not update to 2.4.0
![image](https://user-images.githubusercontent.com/37169906/57749770-0f38ad00-7712-11e9-8a31-972a2ce141ca.png)

**Comment by rez1dent3** [comment]
@MoeCasts Strange...  I think you have a cache composer. I'll try it in about an hour.  The library has been updated on one project.

**Comment by rez1dent3** [comment]
@MoeCasts The problem does not repeat.
![image](https://user-images.githubusercontent.com/5111255/57753449-db02c380-76f4-11e9-8f66-8eee1558e23b.png)

**Comment by MoeCasts** [comment]
@rez1dent3 It will be success if execute `composer update`, but the version is 2.3.*

**Comment by MoeCasts** [comment]
@rez1dent3 i will try it later, thank you!

**Comment by rez1dent3** [comment]
@MoeCasts Well, if that write.
![image](https://user-images.githubusercontent.com/5111255/57754536-5bc2bf00-76f7-11e9-8b0d-c0ffcb0b2a8b.png)
![image](https://user-images.githubusercontent.com/5111255/57754560-6b420800-76f7-11e9-9d5c-12fad8b5f401.png)

**Comment by MoeCasts** [comment]
@rez1dent3 I have tried it, it is still return error or install v2.3.2 though i run composer before.
```
laradock@8428e44494da:/var/www/nya$ composer require bavix/laravel-wallet
Using version ^2.3 for bavix/laravel-wallet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing bavix/laravel-wallet (2.3.2): Downloading (100%)
Writing lock file
Generating optimized autoload files
```

```
laradock@8428e44494da:/var/www/nya$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bavix/laravel-wallet 2.4.0 exists as bavix/laravel-wallet[0.0.1, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.x-dev, dev-master] but these are rejected by your constraint.
```

**Comment by rez1dent3** [comment]
@MoeCasts removed tag and re-created in packagist

**Comment by MoeCasts** [comment]
@rez1dent3 I got it by reinstalling it after removed it.
