### ISSUE TITLE
creating balance of the wallet by default 

### ISSUE THREAD

**Issue by ahmed-mohammed1** [bavix/laravel-wallet#346]
creating balance of the wallet by default not working when i use $user->balance it showing this error 

    "message": "Attempt to read property \"exists\" on null",
    "exception": "ErrorException",
    "file": "/home/bootfi/Desktop/backend/vendor/bavix/laravel-wallet/src/Services/WalletService.php",
    "line": 130,

**Comment by rez1dent3** [comment]
Hello. More information needed:
- php version;
- what database and version;
- what version of laravel;
- what version of the package;
- you need a User model code;
- you need an action code;
- full trace;
Then I can help you.

**Comment by ahmed-mohammed1** [comment]
ok
Laravel v8.52.0 
PHP v8.0.7
MySql v8.0.26
package 6.1

here is my Customer model
class Customer extends Model implements \Bavix\Wallet\Interfaces\Customer
{
    use Uuids, SoftDeletes, HasFactory, LogsActivity, CanPay;
     .
     .
     .
}

and my Order model
class Order extends Model implements Product, Taxable
{
    use Uuids, SoftDeletes, HasFactory, LogsActivity, HasWallet;
     .
     .
     .
  public function canBuy(Customer $customer, int $quantity = 1, bool $force = null): bool
      {
          /**
           * If the service can be purchased once, then
           *  return !$customer->paid($this);
           */
          return true;
      }
  
      public function getAmountProduct(Customer $customer)
      {
          return $this->total_amount;
      }
  
      public function getMetaProduct(): ?array
      {
          return [
              'order_number' => $this->order_number,
              'description' => 'Purchase of Order #' . $this->id,
          ];
      }
  
      public function getUniqueId(): string
      {
          return (string)$this->getKey();
      }
  
      public function getFeePercent()
      {
          return 0.03; // 3%
      }
}
and my controller 
$user = Auth::user();
return $user->balance;

i want to test the balance value. but it gave me that error

**Comment by rez1dent3** [comment]
I have reproduced the problem. The problem is in the UUID of the user, at the moment you can only use integer values in the primary key.

Unfortunately, this problem cannot be fixed in the library. I've had many attempts to drag int and uuid into the library, but backward compatibility breaks a lot.

I am currently working on a draft for the next version and will pay special attention to UUIDs.

**Comment by rez1dent3** [comment]
the problem arises in the connection between the wallet and the user, the package cannot create the wallet and we receive an error
