### ISSUE TITLE
QueryException Incorrect decimal value for column 'balance'

### ISSUE THREAD

**Issue by iamroi** [bavix/laravel-wallet#348]
Hi @rez1dent3 !

I ran into this weird issue when I was running my tests

I created a wallet with 6 decimal places
```
$user->createWallet([
    'name' => 'New Wallet',
    'slug' => 'my-wallet',
    'decimal_places' => 6,
]);
```

then when I tried to deposit 1000 like below with 6 extra zeros,  // edited**
```
$wallet->deposit(1000000000);
```

I encountered this QueryException
```
  SQLSTATE[HY000]: General error: 1366 Incorrect decimal value: '1000000000.0000000000000000000000000000000000000000000000000000000000000000' for column 'balance' at row 1 (SQL: update `wallets` set `balance` = 1000000000.0000000000000000000000000000000000000000000000000000000000000000, `wallets`.`updated_at` = 2021-08-09 09:28:25 where `wallets`.`id` = 1)
```
Please let me know if I'm missing something on my end. Thanks!

**Comment by rez1dent3** [comment]
Hello. Added a test, I'm waiting for the result. Unsubscribe tomorrow

https://github.com/bavix/laravel-wallet/blob/issue_348/tests/MultiWalletTest.php#L602

**Comment by rez1dent3** [comment]
There is no problem or I didn’t find it. Look at the test, is it correct? #349

Github Actions:
https://github.com/bavix/laravel-wallet/actions/runs/1115372136

**Comment by iamroi** [comment]
Hi @rez1dent3 Thanks for that!

I just added a comment here https://github.com/bavix/laravel-wallet/pull/349/files#r685824436

I'm still able to replicate this weird issue on my system with the below config,

MySQL 5.7.32
PHP 8.0.3
Laravel 8

**Comment by iamroi** [comment]
Hey @rez1dent3 after further playing around, I found that by changing the below in the wallet config everything works!

```
    'math' => [
        -'scale' => 64,
        +'scale' => 63,
    ],
```

I'm not sure why `64` didn't work with the `BrickMatch`. Please let me know if you have any ideas and confirm if it is safe to leave it as `63` thanks!
