### ISSUE TITLE
Problems with payments

### ISSUE THREAD

**Issue by jprm** [bavix/laravel-wallet#35]
I've tried to use this on my project but I have this error:

> Declaration of App\Item::canBuy(App\Customer $customer, bool $force = false): bool must be compatible with Bavix\Wallet\Interfaces\Product::canBuy(Bavix\Wallet\Interfaces\Customer $customer, bool $force = false): bool

**Comment by rez1dent3** [comment]
Hello @jprm. Without the code, I can't help you. Here is an example of work.

Simple code:
```php
$user->pay($item);
```

Models:
```php
class User extends Model implements Customer
{
    use CanPay;
}
```

```php
class Item extends Model implements Product
{
    use HasWallet;

    public function canBuy(Customer $customer, bool $force = false): bool
    {
        /**
         * If the service can be purchased once, then
         *  return !$customer->paid($this);
         */
        return true; 
    }

    public function getAmountProduct(): int
    {
        return 100;
    }

    public function getMetaProduct(): ?array
    {
        return [
            'title' => $this->title, 
            'description' => 'Purchase of Product #' . $this->id, 
            'price' => $this->getAmountProduct(),
        ];
    }
}
```

see: https://laravel-wallet.bavix.ru/2.2/payment

**Comment by jprm** [comment]
Thanks for your promt response.
This is the code I've used.

I've tried the same on a fresh Laravel 5.8 installation and I have the same error.
Only Laravel installation + Laravel-wallet and create the Item Model.

If I comment the line:
`// public function canBuy(Customer $customer, bool $force = false): bool;`
of \vendor\bavix\laravel-wallet\src\Interfaces the error disappear.

**Comment by rez1dent3** [comment]
@jprm What PHP version?

**Comment by rez1dent3** [comment]
@jprm I don't think you've defined the canBuy method in the Product model.

**Comment by jprm** [comment]
PHP version 7.2

What do you mean with "defined the canBuy method in the Product model."?

**Comment by rez1dent3** [comment]
@jprm 
![image](https://user-images.githubusercontent.com/5111255/57868227-3f17ab80-780b-11e9-89ac-9fb968262b8e.png)

**Comment by jprm** [comment]
Solved, I added this line to the Item Model
`use Bavix\Wallet\Interfaces\Customer;`

Thanks.
