### ISSUE TITLE
to ignore migration

### ISSUE THREAD

**Issue by ahmed-mohammed1** [bavix/laravel-wallet#350]

**Comment by rez1dent3** [comment]
add to boot
```php
WalletConfigure::ignoreMigrations()
```

https://github.com/bavix/laravel-wallet/blob/master/src/WalletConfigure.php#L30

**Comment by rst630** [comment]
> add to boot
> 
> ```
> WalletConfigure::ignoreMigrations()
> ```
> 
> https://github.com/bavix/laravel-wallet/blob/master/src/WalletConfigure.php#L30

not to boot! I must be in register() - when in boot() it not working when running phpunit
