### ISSUE TITLE
decimal dataType not working well if i want to store 19.5 to database it store 20

### ISSUE THREAD

**Issue by ahmed-mohammed1** [bavix/laravel-wallet#351]
for example
$user->deposit(19.5); it stores 20 at the amount attribute

**Comment by rez1dent3** [comment]
```php
$user = User::first();
$user->balance; // int(100)
$user->balanceFloat; // float(1.00)

$user->depositFloat(1.37);
$user->balance; // int(237)
$user->balanceFloat; // float(2.37)
```

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet#how-to-work-with-fractional-numbers

**Comment by ahmed-mohammed1** [comment]
one more thing 
am used now HasWalletFloat but..
when I'm trying to deposit 1.9 $user->depositFloat(1.9); it deposit 190

**Comment by ahmed-mohammed1** [comment]
it deposit 190 in database but when we return $user1->balanceFloat; it return 1.90

**Comment by ahmed-mohammed1** [comment]
$user1 = User::first();
return $user1->depositFloat(30.2); // store in database 3020
return $user1->balanceFloat; // returned 31.40

why is there a bug or what happen
