### ISSUE TITLE
Store wallet

### ISSUE THREAD

**Issue by Jnyawach** [bavix/laravel-wallet#352]
Might you consider adding the functionality to create a store/shop wallet. One not attached to the user model,  such that the shop wallet can be on its own and not attached to the owners wallet
For instance,
$store=store->balance  //100
$user=User::first()
$store->transfer($user, 50)

**Comment by rez1dent3** [comment]
Hello. This library is not tied to the user model. Create a store model and follow the instructions.
```php
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Interfaces\Wallet;

class Store extends Model implements Wallet
{
    use HasWallet;
}
```

Then use in the code
```php
$store->deposit(1000);
$store->withdraw(500);
```

If you need to make transfers from the store to the user, then the user must have his own wallet
```php
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Interfaces\Wallet;

class User extends Model implements Wallet
{
    use HasWallet;
}
```

And then so
```php
$store->transfer($user, 50);
```

**Comment by Jnyawach** [comment]
Thank you
