### ISSUE TITLE
Listen balance update event

### ISSUE THREAD

**Issue by verseal** [bavix/laravel-wallet#354]
Is there a way to listen balance update event?
Standard model 'updated' event for wallet is not triggering.

**Comment by rez1dent3** [comment]
Hello. During development, I did not include events in the initial design. I don't have a beautiful solution to the problem.

Let's start with the line `src/Services/CommonService.php:265`
```php
$balance = app (Storable :: class)->incBalance ($wallet, $amount);
```

Create your store and dispatch events in `incBalance` method.
Then we go to the config and change the storage to our own.
```php
'storable' => MySuperEventStorage :: class,
```
