### ISSUE TITLE
Adding currency support

### ISSUE THREAD

**Issue by salvationarinze** [bavix/laravel-wallet#357]
Thanks for such an awesome package. Requesting that we add support for multiple currencies i.e a user can have USD and EUR wallets

**Comment by rez1dent3** [comment]
Hello. Why is the current implementation not suitable?

Docs: https://bavix.github.io/laravel-wallet/#/exchange
Ready-made package: https://github.com/bavix/laravel-wallet-swap

**Comment by salvationarinze** [comment]
This is it. Thanks, I appreciate
