### ISSUE TITLE
the transfer() function keeps giving me an error   #HELP ME DEBUG THIS ISSUE

### ISSUE THREAD

**Issue by HelloMukama** [bavix/laravel-wallet#358]
![Screenshot from 2021-09-16 16-19-22](https://user-images.githubusercontent.com/26729028/133619522-0f8cbf54-9d3d-41ae-9eba-d851a1a9bb54.png)

The above lines of code give me the following error

`[13:08:11] LOG.error: Call to a member function transfer() on string {"exception":{}}`

![Screenshot from 2021-09-16 16-16-12](https://user-images.githubusercontent.com/26729028/133619259-4b5ec988-393f-43de-8e27-f3ba95d4ec36.png)

**Comment by HelloMukama** [comment]
I have tried casting the $wallet @param with int or float and nothing is working

**Comment by rez1dent3** [comment]
Hello. You are trying to transfer not from a wallet / user, but from a php scalar type and you get an error.
In fact, your code looks like this `"3"->transfer("2", 100);`. You need to work with a wallet or user, here is an example.

```php
$user1 = User::find(1);
$user2 = User::find(2);

$transferDto = $user1->transfer($user2, 1);
```

**Comment by HelloMukama** [comment]
Thanks so much for your quick reply.
the docs on that link are what i had been following.
Applying your correction seems to have removed that error .
Now what im getting is the one below.

![Screenshot from 2021-09-16 16-44-49](https://user-images.githubusercontent.com/26729028/133623419-25da7b02-90fc-4140-8042-4114083c69b2.png)

**Comment by HelloMukama** [comment]
Thanks so much for your very fast reply @rez1dent3 
I have solved the transfer function issue.
Thanks so so much.

**Comment by HelloMukama** [comment]
Allow me to continue this thread here.
I am trying to implement the functionality via an API.
Is there a way I can pass Request parameters in the function definitions such that they allow me to pass dynamic values of the different values this great library offers?

Say forexample instead of something like this,

```
$user1 = User::find(1);
$user2 = User::find(2);
$transferDto = $user1->transfer($user2, 1);
```

I do something like this

```
$user1 = User::find($id);
$user2 = User::find($id);
$transferDto = $user1->transfer($user2, $amount);
```


I tried it earlier on via functions definitions like so,..

```
public function transferWalletToWallet(Request $id, Wallet $balance) {
        $sendingWallet = User::find(2);    // this will be our sender
        $receivingWallet = User::find(1);  // our receiver

        $sendingWallet->deposit(100);   // Deposit 100 to sender

        return $sendingWallet->transfer($receivingWallet, 100);   // transfer 100 from sender to receiver
    }
```

**Comment by rez1dent3** [comment]
I think it's worth starting from afar.
1. What method (GET, POST, PUT...) is used in your API?
2. How is the route configured?
3. What is `$amount` and why should it be of type `Wallet`?
4. What should your action do?

**Comment by HelloMukama** [comment]
The route formats that I am using are these.

Say forexample when i want to view the balance of user of id 10, I would basically do something like 

The controller function being
```
public function showBalance(Request $id, Transaction $amount) { 
        $user = User::find($id);
        return $user->balance;
    }

```

Then api.php being
```
Route::get(transfer/", [WalletController::class, "showBalance"]);

Route::post(transfer/{amount}/{id}/{id}/", [WalletController::class, "transferWalletToWallet"]);
```

And then via `postman`,
I would basically do some simple routes like 
`127.0.0.1:8000/api/transfer/` for the GET request.
`127.0.0.1:8000/api/transfer/100/2/10/` for the POST request

The `2` above being the id of the sender and `10` being the id of the receiver.

Having filled the 100 above in the body of Postman's (or any other like application)'s post request.  
as '`amount': 100`

Then the reason why i use Request $id parameters is because i am entering these variables via method requests.

Then as to why I use type `Wallet` for type of `$amount,` that's because it could be in the migrations table definition.
Though maybe the correct class should be Transaction would be `Transaction $balance` but for 

So that's the overall picture of what i'm trying to achieve such that i give the API flexibility

**Comment by rez1dent3** [comment]
I think you should read the documentation for the framework.
If I understand you correctly, then you do not need to transfer any models, but only parameters are enough.

Example "show balance":
```php
public function showBalance(Request $request) 
{
    return $request->user()->balance;
}
```

I don't know why you need two user IDs, I'll modify the API a bit. We will accept only one ID, and the second will be taken from the current authorized user.

Example "transfer":
```php
// route
Route::post("transfer/", [WalletController::class, "transferWalletToWallet"]);

// custom request
// see: https://laravel.com/docs/8.x/validation#creating-form-requests
class TransferRequest  .... {
...
    return [
        'recipient_id' => 'required',
        'amount' => 'required',
    ];
...
}

// action
public function transferWalletToWallet(TransferRequest $request)
{
    $recipient = User::find($request->input('recipient_id'));
    $request->user()->transfer($recipient, $request->input('amount'));
    ...
}
```

**Comment by HelloMukama** [comment]
Hi sorry for taking long to provide feedback.
I have applied your method above in the 2 following ways but end up with the same error 
`"Call to a member function transfer() on null"`

```
public function transferWalletToWallet(TransferRequest $request)
{
    $recipient = User::find($request->input('recipient_id'));
    $request->user()->transfer($recipient, $request->input('amount'));
    ...
}
```

And I also did the following

```
public function transferWalletToWallet(TransferRequest $request)
{
    $recipient = User::find(5);
    $request->user()->transfer($recipient, $request->input('amount'));
    ...
}
```

In all cases even with 

```
public function transferWalletToWallet(Request $request)
{
    $recipient = User::find(5);
    $request->user()->transfer($recipient, 100);
    ...
}
```

The error is the same

**Comment by HelloMukama** [comment]
![Screenshot from 2021-09-17 07-32-37](https://user-images.githubusercontent.com/26729028/133724945-f36d7347-9908-4381-8a85-d0f10ad5171a.png)



I actually just realised that when i run this route as a get request via the browser, i get a successful transfer.
`Route::get("transfer/", [WalletToWalletController::class, "transferWalletToWallet"]);`

However on postman as a post request, i keep getting an error to do with the sender id being null yet i'm logged in 
`Error "Call to a member function transfer() on null"`

`Route::post("transfer/", [WalletToWalletController::class, "transferWalletToWallet"]);`

**Comment by HelloMukama** [comment]
![Screenshot from 2021-09-17 07-35-56](https://user-images.githubusercontent.com/26729028/133725204-22b91a3c-a53e-4333-81a2-17084cbe63e4.png)




I actually just realised that when i run this route as a get request via the browser, i get a successful transfer.
`Route::get("transfer/", [WalletToWalletController::class, "transferWalletToWallet"]);`

However on postman as a post request, i keep getting an error to do with the sender id being null yet i'm logged in 
`Error "Call to a member function transfer() on null"`

`Route::post("transfer/", [WalletToWalletController::class, "transferWalletToWallet"]);`

**Comment by rez1dent3** [comment]
`"Call to a member function transfer() on null"`
Says that the user was not found.

Make a request from authorizations or search for a user directly in the action.

**Comment by HelloMukama** [comment]
For  some reason `Auth::user()` or `auth()->user()`  or `$request->user()` all are working in the browser because i have a logged in session there,
But when i turn to postman, they cease to work.
The `null` error i am getting is really about the authentication via postman. I however am still trying to figure out how to solve this.
Postman seems to be failing to detect that I am having a logged in user which is correct because the session is in the browser

**Comment by HelloMukama** [comment]
But i'm loving this package. Next thing i want to implement is the fees on the different transactions.
Especially for the deposits
