### ISSUE TITLE
How to Change id to different field for the transfer() method's receiver attribute

### ISSUE THREAD

**Issue by HelloMukama** [bavix/laravel-wallet#363]
Check out the lines below.

```
$sender = $request->user();
$receiver = User::find($request->input('id'));
return $sender->transfer($receiver, $request->input('amount'));
```
What the lines above do is that they are able to send to a certain user as per the id you provide through the post request.

But I want to be able to send by entering a phone number instead.
I have a custom `Wallet` model extending `Bavix\Wallet\Models\Wallet`
And on my custom model i have defined a `phone_number` field which is a `FK` to the `phone_number` in the `User` model

I also have a `phone_number` field on the `User` model but it's not a `PK`.

How do i modify the lines above to have them point to a `User` instance by `phone_number` instead?

Do i instead define 2 `PKs` in `User` so that I can uniquely identify each `User` instance?

I have tried the line below and they definitely failed to work.
```
$sender = $request->user();
$receiver = User::find($request->input('phone_number'));
return $sender->transfer($receiver, $request->input('amount'));
```

**Comment by rez1dent3** [comment]
Hello. This does not apply to the package. Read the framework documentation: https://laravel.com/docs/8.x/eloquent#retrieving-single-models

**Comment by HelloMukama** [comment]
So it's on my framework side and not the package??
