### ISSUE TITLE
get customer's Cart 

### ISSUE THREAD

**Issue by starking8b** [bavix/laravel-wallet#379]
hello, I want to use Cart in my system, I implement required interfaces , but as admin, I want to see the content of every client's cart , how can  I do that

**Comment by rez1dent3** [comment]
Hello. If there was a payment without unique data in the meta, then nothing. The package does not store information about the shopping cart. In current versions, a purchase equates to multiple calls to the pay methods. Now I am doing refactoring and thinking through the design, everything is complicated there. I want to maintain a painless transition and flexibility. In the next major version, nothing will change, it will hurt to work with the basket.

I advise adding metadata to the cart.
