### ISSUE TITLE
Unable to implement

### ISSUE THREAD

**Issue by victorolayemi** [bavix/laravel-wallet#386]
Please help me with how t implement, what am i missing?
<img width="653" alt="Screen Shot 2021-10-30 at 3 05 37 PM" src="https://user-images.githubusercontent.com/13328789/139536256-87a9ad8b-b3b9-454e-a60c-eba598ce29d1.png">

<img width="653" alt="Screen Shot 2021-10-30 at 3 06 01 PM" src="https://user-images.githubusercontent.com/13328789/139536279-45548b02-d4e3-4f96-8da9-f3d69dad5db6.png">
 i also tried this but non worked
<img width="653" alt="Screen Shot 2021-10-30 at 3 07 00 PM" src="https://user-images.githubusercontent.com/13328789/139536336-f48db7a3-5e37-436f-ac55-cc6dbfd798a6.png">

**Comment by rez1dent3** [comment]
Hello. I can see that the WalletPayment model uses a wallet, but I do not see the User and Customers model.  Most likely, there is no library connection in these models.

**Comment by victorolayemi** [comment]
The customers model is the user model

<img width="653" alt="Screen Shot 2021-10-30 at 6 57 54 PM" src="https://user-images.githubusercontent.com/13328789/139547466-3f4058f2-77e1-4fcd-9519-575574120217.png">

**Comment by rez1dent3** [comment]
I'm not 100% sure, but it looks right. What's the problem?

**Comment by victorolayemi** [comment]
> I'm not 100% sure, but it looks right. What's the problem?

i don't know balance property or deposit method all return error 500

**Comment by rez1dent3** [comment]
There is too little data to reproduce the problem. Could you please make an example and upload it to github, I will clone and try to help you with your problem.

**Comment by victorolayemi** [comment]
B

> There is too little data to reproduce the problem. Could you please make an example and upload it to github, I will clone and try to help you with your problem.

Before i do that i need to ask if it works with Passport

**Comment by rez1dent3** [comment]
Why should there be problems? I don't see any conflicts in the contract.
@victorolayemi
