### ISSUE TITLE
Recursion issue after Upgrading to 6.2.0.

### ISSUE THREAD

**Issue by AbdullahFaqeir** [bavix/laravel-wallet#387]
After upgrading to 6.2.0, the system stopped working completely yet it was displaying zero errors.

After spending almost 5 hours trying to investigate the issue, it turned out that the update caused laravel service container itself to fall into a recursion loop when trying to fetch `WalletService::class` and `Storable::class` as it wasn't able to find their aliases in the registered alias list.

**Comment by rez1dent3** [comment]
Hello. I will try to study this moment, thanks for the information. It would be great if you provide more information

**Comment by AbdullahFaqeir** [comment]
@rez1dent3 
If I had enough time I would've fixed it and submitted a PR, but I already spent hours trying to figure it out.

There's honestly no further information to be provided, I believe if you have a fresh installation of laravel and install it with a simple implementation and simply run the app, the app will give timeout exception or if you have `xdebug` installed it'll throw an exception telling you that maximum depth of recursion has been reached, and if you go through the stack-trace of the exception you'll find that the IoC of laravel is stuck trying to find the alias for the above mentioned Classes, and if you try to dump `app()` and search the aliases for it you won't find the alias.

**Comment by rez1dent3** [comment]
It seems to me that the matter is in the cache. The problem is not reproducible

**Comment by rez1dent3** [comment]
Problems are reported in the adjacent issue. I will try to study this issue. Thanks for your feedback.

**Comment by AbdullahFaqeir** [comment]
I will study the issue as well and I'll keep you posted, mostly if I managed to fix it I'll submit a PR.

**Comment by rez1dent3** [comment]
@AbdullahFaqeir 
I reproduced the problem. I tried to connect the config from version 6.1 to 6.2 and got an error.

The problem lies in the line
```php
'mathable' => BrickMath::class,
```

Try to remove it and if the problem goes away, then I can quickly make changes to the code.

**Comment by rez1dent3** [comment]
@AbdullahFaqeir A new version has been released 6.2.1. Can you test it?

**Comment by AbdullahFaqeir** [comment]
Sure, on it.

**Comment by AbdullahFaqeir** [comment]
@rez1dent3 It's working for me, thanks a lot.

**Comment by rez1dent3** [comment]
@AbdullahFaqeir Thank you very much. Sorry it took so long.

**Comment by rez1dent3** [comment]
I will wait. The 7.x development https://github.com/bavix/laravel-wallet/pull/390#issue-1041460293 has been going on for half a year now, and some of the changes are already available in 6.2. Due to the large number of changes, I broke the update.

https://github.com/bavix/laravel-wallet/compare/6.1.0...6.2.0

**Comment by rez1dent3** [comment]
Hello, @AbdullahFaqeir. You said you could help. So a good task has appeared for you, if, of course, you are interested in it. We need to benchmark the 6.x versus 7.x library. The new version is in the develop branch.

Requirements for the project:
- create a new project on laravel 8.x or lumen 8.x;
- sqlite, postgres, mysql must be supported;
- the project should not have additional dependencies, only laravel wallet;
- Create API contracts and run them through https://github.com/denji/awesome-http-benchmark;
- Single methods, multi-wallet methods, basket and merchandise methods and currency exchange should be covered;

Are you ready to help?
