### ISSUE TITLE
Why is this happening? "Deadlock found when trying to get lock..."

### ISSUE THREAD

**Issue by JoelVeloz** [bavix/laravel-wallet#389]
![FireShot Capture 118 - 🧨 SQLSTATE 40001 _ Serialization failure_ 1213 Deadlock found when t_ - localhost](https://user-images.githubusercontent.com/85255169/139557714-4c2ee8b5-0e45-4977-93a4-5cf57f4205ad.png)

I have been testing transfers between users and when I try to make several transfers simultaneously, I get that error. Exactly why does this happen and how can I avoid it?

**Comment by rez1dent3** [comment]
Hello. I tried to reproduce on mysql 8, it didn't work. You can suggest server information (php, mysql ...), package version.

**Comment by JoelVeloz** [comment]
Use php 8.0.0, mysql 8, laravel 8.65, this package in version 6.2.

The error occurs as follows:
I try to send money transfers from account1 to account2
I do this about 100 times in a "for", with a random amount of money.

// CODE
Route :: get ('test2', function () {
    $ user1 = User :: first ();
    $ user2 = User :: find (2);
    $ wallet1 = $ user1-> getWallet ("USD");
    $ wallet2 = $ user2-> getWallet ("USD");

    for ($ i = 0; $ i <100; $ i ++) {
        $ wallet1-> transfer ($ wallet2, random_int (1, $ wallet1-> balance) * 0.5);
        $ wallet2-> transfer ($ wallet1, random_int (1, $ wallet2-> balance) * 0.5);
    }
});
////////////////////////////////////////////////
This to test if the package works with a massive load of transactions between 2 users.
All good with that block of code, the total money remains the same in the end.

Now I wanted to run the same code block on 2 computers to see if it has any kind of limit.
And apparently when executing this code block between 2 users on 2 different computers at the same time, it throws this error, which makes the total sum of money vary with the initial one and that money is transferred into an account without being debited from other.

I do not know if there are certain restrictions when transferring money between users, the point is that I try to find out that simultaneous transfers to a specific user coexist without a failure in the process.

**Comment by rez1dent3** [comment]
Everything is fine with the infrastructure. What about your package configuration?

PS,
I would advise using a `redis server` to deal with race conditions.
```php
# config/wallet.php
'lock' => [
    'cache' => 'redis',
     'enabled' => true,
],
    
'cache' => [
    'driver' => 'redis',
],
```
