### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes)

### ISSUE THREAD

**Issue by Hussam3bd** [bavix/laravel-wallet#391]
Hi team,
After I upgraded to v6.2.0 I started to get this error when I use the ```Cart``` helper class

```php
Symfony\Component\ErrorHandler\Error\FatalError
Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes)
```

**Comment by alexstewartja** [comment]
It's also present when using the HasWallet trait. I think it's a bug in a lower level class. @rez1dent3 , as much you may not want to admit it, #387 is definitely not a `no-problem`.

**Comment by rez1dent3** [comment]
Hello. I will look for a problem. Thanks for your feedback.
@alexstewartja @Hussam3bd FYI^

**Comment by rez1dent3** [comment]
Released version `6.2.1`, fix your problems.
If you suddenly have problems, then discard your `config/wallet.php`.

@alexstewartja @Hussam3bd FYI^

**Comment by alexstewartja** [comment]
@rez1dent3 That was fast man! I'm gonna checkout and test. Soon report back.

**Comment by alexstewartja** [comment]
Works beautifully! The latest release fixes this (#391) and that (#387) so I vote that you close them. Only thing left to do is add an entry to the Upgrade Guide -> https://bavix.github.io/laravel-wallet/#/upgrade-guide

**Comment by rez1dent3** [comment]
@alexstewartja 
Now the manual does not need to be updated, minor fixes should not break the code and require changes. At the moment, config edits are no longer required.

I will update the manual when I complete version 7.x. There will need to update the config file: https://github.com/bavix/laravel-wallet/pull/390#issue-1041460293

Thank you very much.

Issue will remain open for now. Let's wait for a response from @Hussam3bd.

**Comment by Hussam3bd** [comment]
Hi @rez1dent3 
thank you so much, that was fast! 
The issue has been solved, thank you so much
