### ISSUE TITLE
Lock specific amount credit on user wallet

### ISSUE THREAD

**Issue by dalisalvatore** [bavix/laravel-wallet#397]
hi guys,  i'd like to lock some specific amount of credit on wallets for first purchasement.
lets say, user registered to my website, charge some credit on their wallet then purchase the product on website. After the product is downloaded, got refund.

so if user charge his wallet for the first time, i want prevent him to demand refund. If he charges 5 credit first time, i'd like to block 5 credit on his wallet.
I hope i could make myself clear. If anyone help me out, i'd be appereciated.

Thanks in advance.

**Comment by rez1dent3** [comment]
Hello. An interesting challenge. I would suggest that you use gifts. You create a wallet for the administrator and replenish it for the amount you need, and the administrator gives the desired product to the user.
https://bavix.github.io/laravel-wallet/#/gift

Without deep knowledge of your business process, it will not be possible to give you the correct answer. Can you describe how this should look in detail?

**Comment by dalisalvatore** [comment]
I'd sell subscriptions. User registers to system, charge his/her wallet. During their subscription, cron system will cut off daily subscription fee from their wallet. So untill that credit runs out of, i dont want user(new users only) to refund on subscription module. Lets say, xx user registers to the system, charge his wallet 10 credits. untill this 10 credits runs out of, he can not refund.

**Comment by rez1dent3** [comment]
I think you need to create an additional table with a counter and check already at the level of the request to the backend. This is a layer of business logic that does not concern the wallet.
