### ISSUE TITLE
Wallet balance - Question

### ISSUE THREAD

**Issue by japhyamg** [bavix/laravel-wallet#399]
Hi guys, i am trying to modify my forked version of this repo.
In the docs, we can check user wallet balance like this $user->balance; // 10.
And i have look for this method (balance) which is what i want to modify but can seem to find it.

**Comment by rez1dent3** [comment]
Hello. The documentation for the framework will help you.
https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor

**Comment by japhyamg** [comment]
There is method getAvailableBalance() in the Wallet model.
public function getAvailableBalance()
    {
        return $this->transactions()
            ->where('wallet_id', $this->getKey())
            ->where('confirmed',true)
            ->sum('amount')
        ;
    }
But i want this;
public function getBalanceAttribute()
    {
        return $this->transactions()
            ->where('wallet_id', $this->getKey())
            ->where('confirmed','=', Transaction::TRANSACTION_CONFIRMED)
            ->sum('amount')
        ;
    }
but this doesnt give me the result i am looking for

**Comment by rez1dent3** [comment]
So create a method. Everything works according to laravel documentation

**Comment by japhyamg** [comment]
Ok, thank you very much. This is a very good package
