### ISSUE TITLE
Getting issue after composer update under laravel 7

### ISSUE THREAD

**Issue by nitiz143** [bavix/laravel-wallet#409]
Hi,

I am getting issue after composer update 
Bavix\Wallet\Internal\Exceptions\LockProviderNotFoundException

**Comment by rez1dent3** [comment]
Hello. Yes, this is due to the fact that I always have redis registered there. And the default is null, now I'll fix it (6.2.4 tag).
Thank you
https://github.com/bavix/laravel-wallet/commit/4fffe3707aecb779d0f3c95dac95ceb11336c1cc

**Comment by rez1dent3** [comment]
If you have a file `config/wallet.php`, then you need to put down any cache with support for locks. I would recommend redis, but you can use any other.
```php
    'lock' => [
       'cache' => 'redis', // default value 'array'
```

**Comment by MiladAheshmeh** [comment]
I had same issue 

delete `config/wallet.php` file and then run command `php artisan vendor:publish --tag=laravel-wallet-config`
