### ISSUE TITLE
Refund does not work correctly

### ISSUE THREAD

**Issue by decisive-dev** [bavix/laravel-wallet#41]
Hello.

```php
$wallet = $user->getWallet('myWallet');
$wallet->balance; // 16 
// product price = 13
$wallet->pay($product); // success
$wallet->balance; // 3
$wallet->refund($product); // success
$wallet->balance; // 3. Wtf?
```

**Comment by rez1dent3** [comment]
Hello. Yes, there is a problem. And it is fixed in the [3.0.x-dev](https://github.com/bavix/laravel-wallet/tree/3.0) branch. 
Commit: https://github.com/bavix/laravel-wallet/pull/40/commits/5b0b3bb626ccda83ebb46f174bb8089aa24feab0
PR #40 

You can already use the new version.
```php
composer req bavix/laravel-wallet:3.0.x-dev
```

**Comment by decisive-dev** [comment]
@rez1dent3 Has the API changed much? Need changes to your code?

**Comment by decisive-dev** [comment]
Can you fix in version 2.x?

**Comment by rez1dent3** [comment]
@decisive-dev Unfortunately, the wrong architecture does not allow to fix the bug in version 2.x. If you do not use outdated methods and tools, and do not override the code, you can easily upgrade to version 3.x. 

By the way, there may be problems if you have overridden protected methods. Many of them will leave in the 3rd version.

If you worked exclusively on documentation, you do not need to edit the code.

**Comment by decisive-dev** [comment]
@rez1dent3 Yes it does. Now I will make a fork and drive on test benches, then go on sale.
