### ISSUE TITLE
Total amount per transaction

### ISSUE THREAD

**Issue by JoelVeloz** [bavix/laravel-wallet#416]
Hello, I have been reviewing the package I really liked the truth and I would like to add on my own a 'total' attribute within the transactions to know the total amount of my wallet after having made that transaction, in order to know how much balance I had in a given transaction.
I'm not sure whether to add the attribute into the meta array or add a column, but I would like to know in which section I could modify this, without touching the vendor folder.

I have other questions, how can I get a list of transactions by wallet? I have dealt with '$wallet-> transactions' but it returns all transactions by user.

And one last question, when generating a transaction, the package already includes a function to verify that the aggregate balance is correct? That is, to verify that the 'balance' of a wallet is correct, I must compare it with the sum of the transactions of this wallet.

**Comment by rez1dent3** [comment]
Hello.
> my own a 'total' attribute within the transactions to know

like this.
https://github.com/bavix/laravel-wallet/blob/ef6ecd5638d64c8b7ea7c7e97e89c9146e4aabde/tests/Infra/Transform/TransactionDtoTransformerCustom.php#L20-L30

> I have dealt with '$wallet-> transactions' but it returns all transactions by user.

So it happened historically, but now this "feature" bothers me a little. But I don't want to break the package's backward compatibility.

You can easily achieve the desired result by adding where.
```php
$wallet->transactions()->where('wallet_id', $wallet->getId())->...
```

> And one last question, when generating a transaction, the package already includes a function to verify that the aggregate balance is correct?

Details are needed here, I did not understand your question.

**Comment by rez1dent3** [comment]
I decided to try adding a new method `walletTransactions` that might replace the old one.

**Comment by JoelVeloz** [comment]
Hello
I've been testing the package, and still haven't found a way to insert the full amount of money per transaction, without altering the vendor.
I would like to know if it is possible to add that in a future update since when executing the 'composer update' everything restarts.
I wanted to tell you that yesterday I ran 'composer update' and something curious happened, at the moment a transaction code block like this is used:

   DB :: transaction (function () {
         Auth :: user () -> withdrawFloat (100);
     });

It stopped working, and erroneously, the transaction was generated but the amount of the wallet was not withdrawn. I tried the package's transactions function and everything worked correctly, but I still don't understand why my code block stopped working.


Another thing I wanted to know is how to verify that the sum of the amount of all transactions is equivalent to the total amount of a wallet, is there a package function for this? Or should I create it by eloquent. I need this for the reason that as I progress in my project, it is verified that no error occurs in the transactions.

**Comment by rez1dent3** [comment]
The update takes place not only in the database, but also in the storage. There is no way to implement atomicity at the transaction level. Package operations are atomic and will not let you get shot in the foot if you work with the package correctly.

If you need to combine several operations into one transaction, then you need to upgrade the package to version 7.1 and work through the package functions. More details here: https://bavix.github.io/laravel-wallet/#/transaction

**Comment by rez1dent3** [comment]
I have freed myself from my affairs and there is time to respond in more detail.

The fact is that the package never declared to work with laravel transactions and until version 7.1, when using your case, the data was not inserted / updated into the database, but was updated in the storage (see the section race condition). I described the problem in more detail here: https://github.com/bavix/laravel-wallet/pull/412

If you want to maintain data atomicity, then you need to work with the internal transaction interface. It is optimized to work with the package and does not violate the atomicity of the data between the database and the store.

This interface allowed us to get rid of unnecessary updates in the database, which gave a big performance boost for 7.x. More details can be found here: https://github.com/bavix/laravel-wallet-benchmark

Now the package does not make +100500 database updates for the wallet, but only updates the state. **Upon completion of the transaction, writes to the database**. If you wrap in your own transaction, then you need to repeat everything that the package does inside.

**Comment by JoelVeloz** [comment]
Could you give more detail about how the transactions work? and how it is connected to the wallet. What do you mean by data atomicity? Could you show a diagram of the process of how a transaction is generated, please
I would like to study the package further. That would help me to solve certain needs that I have in my project.

Regarding the transfers, I will update the package to test the new features, thank you.

**Comment by rez1dent3** [comment]
You'd better look at the pull request https://github.com/bavix/laravel-wallet/pull/412, it's all there. Atomicity is an indivisible operation. Either applied or rolled back.
