### ISSUE TITLE
It's not possible to create database factory for Wallet model class

### ISSUE THREAD

**Issue by rziw** [bavix/laravel-wallet#421]
Hi, 
I'm going to write a feature test which needs generating a database factory of Wallet model,
but it's not possible cause the Wallet class does not use HasFactory trait.

**Comment by rez1dent3** [comment]
Hello. Create a new class and inherit the wallet model. Register the new model in the config.
https://github.com/bavix/laravel-wallet/blob/f06bd6199ada8cd06c4dd7c96e1a42933f00207d/config/config.php#L161
