### ISSUE TITLE
Do it work with blockchian?

### ISSUE THREAD

**Issue by vahidalvandi** [bavix/laravel-wallet#422]
I have project with sensitive finance data in wallet . I need a way to store wallet transaction in blockchain

**Comment by rez1dent3** [comment]
Hello. There is no such functionality out of the box. You can modify the required functionality yourself.

**Comment by vahidalvandi** [comment]
@rez1dent3 please help me , Where should I start?

**Comment by rez1dent3** [comment]
Why do you need blockchain? What do you want to do with it?

It is screwed up quite simply, at the time of creating a new transaction in the database, make a request and get the previous one by adding lock. Calculate the cash amount and create a transaction.

**Comment by vahidalvandi** [comment]
@rez1dent3  i want to store transaction in one cripto blockchain . for incrase securite in change local database

**Comment by rez1dent3** [comment]
I don't understand what you want to implement. I need technical information.
