### ISSUE TITLE
After Confirm the Transaction the wallet of user not updates

### ISSUE THREAD

**Issue by MahmoudSaidHaggag** [bavix/laravel-wallet#429]
After Confirm the Transaction the wallet of user not update

For Example

$user->balance; // 0
$transaction = $user->deposit(100, null, false);
$user->balance; // 0

$user->confirm($transaction);
$user->balance; // 0 => Not Changed

Can help me please

**Comment by MahmoudSaidHaggag** [comment]
I found the error, i am using

DB::beginTransaction();

$user->balance; // 0
$transaction = $user->deposit(100, null, false);
$user->balance; // 0

$user->confirm($transaction);
$user->balance; // 0 => Not Changed

DB::commit();

and database transaction not working correctly with package

**Comment by mattvb91** [comment]
how did you end up fixing this? I upgraded from "7.0.0-beta3" to "7.3.*" and now I am also having issues with similar code not updating the wallet balance?

**Comment by rez1dent3** [comment]
@mattvb91 Hello. Prior to version 7.1, the transaction did not work, it still updated the state in another store. Read more here
https://github.com/bavix/laravel-wallet/pull/412

**Comment by mattvb91** [comment]
So I have been getting through my upgrades and have noticed another small issue (Not sure if this is related but ill throw it in here) but I am not sure if it is related but i do think it stems from this.

My config is the following:

```php
    'math'         => ['scale' => 64],

    /**
     * Storage of the state of the balance of wallets.
     */
    'cache'        => ['driver' => 'redis'],

    /**
     * A system for dealing with race conditions.
     */
    'lock'         => [
        'driver'  => 'redis',
        'seconds' => 1,
    ],

```

On  ` "bavix/laravel-wallet": "7.0.0-beta3"`  in the `StorageService.php` on line 28 where the cache is fetched it with the following:

```php
        $this->cache = $cacheManager->driver(
            $config->get('wallet.cache.driver', 'array')
        );
```
which returns me the following:
![image](https://user-images.githubusercontent.com/11991564/153590559-40aedbaf-be7f-465f-8eaf-db2fb78b61b8.png)

So this works as expected as I get a `RedisManager` instance back (Which ive set in the config as seen above. However in ` "bavix/laravel-wallet": "7.3.*",` the `StorageService.php` is now set with the `$cacheRepository` as such: 

```php
        $this->cacheRepository = $cacheRepository;
```

but the `$cacheRepository` no longer yields `Redis` it now yields `FileStore`? Im assuming this is where my issue stems from? I would be expecting to see `Redis` here too?

![image](https://user-images.githubusercontent.com/11991564/153591149-cf028bef-ad90-446f-90d9-020888d2d126.png)


But maybe its unrelated. Im just trying to debug through why its getting a different cache setting now.

**Comment by rez1dent3** [comment]
@mattvb91 hello. If you directly use the class, then there really will be a cache by default. But the classes needed for the package will be thrown from the configuration

https://github.com/bavix/laravel-wallet/blob/cbafc106822fede460d4f20ebc272acd439c7add/src/WalletServiceProvider.php#L182-L202

**Comment by rez1dent3** [comment]
I'll check again tomorrow. I have a modified service provider in my project, you never know.

**Comment by rez1dent3** [comment]
I decided to double check the information. It feels good. Can you provide the code you tested on?

<img width="864" alt="Снимок экрана 2022-02-12 в 12 12 21" src="https://user-images.githubusercontent.com/5111255/153705188-2f010669-2ca3-4735-b540-7650c946e352.png">

**Comment by rez1dent3** [comment]
I looked at the project, it's ok. Tomorrow I will test the package in its pure form. I don't have a standard service provider here.

<img width="913" alt="Снимок экрана 2022-02-12 в 12 28 47" src="https://user-images.githubusercontent.com/5111255/153705731-5173867c-c016-4e7a-87c8-ae55e96183cb.png">

**Comment by mattvb91** [comment]
Sorry I couldn't be of more help, the code I was testing was actually just during the laravel boot() where everything was registering I didnt even get to my own code yet :laughing:

**Comment by mattvb91** [comment]
@rez1dent3 I think I spotted another small issue in that I think the wallet.php `cache` config setting is being ignored completely and overwritten by the global 'CACHE_DRIVER' env setting? This is on 7.3.1. 

global .env: `CACHE_DRIVER=file`
wallet.php:    ` 'cache'        => ['driver' => 'redis'],`

`php artisan config:clear`

![image](https://user-images.githubusercontent.com/11991564/153707791-95d3e30d-5547-42f0-8932-7e9ac603acdd.png)

When I update global .env to `CACHE_DRIVER=redis`
`php artisan config:clear`

![image](https://user-images.githubusercontent.com/11991564/153707855-9fee0dde-154c-41dc-872e-8c0067abe206.png)

**Comment by rez1dent3** [comment]
@mattvb91 I will try to reproduce it. Thank you

**Comment by mattvb91** [comment]
Sorry just to add more detail the $cacheRepository is from `StorageService.php` on line 23. I am not sure if the initial `boot()` is correct in taking in the system CacheRepository but I would assume maybe it should be the Wallet defined config setting? Not sure just pointint it out.

**Comment by rez1dent3** [comment]
@mattvb91 Laravel requires an explicit indication of the keys, apparently. I will test locally and if everything is ok, then I will make a new release
https://github.com/bavix/laravel-wallet/pull/435/files

**Comment by rez1dent3** [comment]
My project uses a custom service provider since version 3.0. We need to return to using the service from the package, I would have found a bug faster.

**Comment by mattvb91** [comment]
I can confirm that 7.3.2 passes on my CI setup now correctly! Thanks rez1dent3 although I am not sure if it was the same issue or not. I will be throwing a donation on open collective for the great package
