### ISSUE TITLE
Pending transfer between wallets

### ISSUE THREAD

**Issue by haurs** [bavix/laravel-wallet#439]
Hey! I've been playing around with using the wallet v.6.2 for some months now and its been great.

Now I'm stepping it up a bit and wonder if transfers between wallets doesn't support `confirm` bool true/false?

Say for example you want to transfer funds to another users wallet in exchange for a service/product. But you don't want them to get the funds until they've done their part of the deal. So along with the transfer you initiate, you set `confirm => false` in order to keep the transfer on hold. Once the other party completes the deal you confirm the transfer the the funds are released.

Is this supported somehow or would I need to build a custom solution for this?

**Comment by rez1dent3** [comment]
Hello. Transfers do not have this option. The functionality needs to be developed by yourself. Perhaps in the future such functionality will appear, I do not promise.
