### ISSUE TITLE
Event dispatcher fails for testing.

### ISSUE THREAD

**Issue by ysfkaya** [bavix/laravel-wallet#444]
Version: ^7.3

Hello. I am writing a test using balance. However, when I use the `Event::fake` method in Laravel, 

I get the following error

![screenshot](https://user-images.githubusercontent.com/16710972/155517596-f102ced0-c78b-4a5e-9425-2ec3c2b2b692.png)

Is it possible to change the constructor parameter to interface to solve this?

**Comment by rez1dent3** [comment]
Hello. I do not mind. Make a cherry pick of the latest version in 7.x and prepare MR. If everything is ok, I will prepare a release.

**Comment by rez1dent3** [comment]
tags: 7.3.3, 8.0.6
