### ISSUE TITLE
How to send meta when pay?

### ISSUE THREAD

**Issue by megaezz** [bavix/laravel-wallet#446]
I need to store some meta info, that can't be received from $product->getMetaProduct() method.
Is there a way to send meta information during $user->pay($product) method?

**Comment by megaezz** [comment]
Actually I can first set the value I want to $product entity, e.g.
`$product->pay_comment = 'comment'`
and write getMetaProduct() like:
```
public function getMetaProduct(): ?array
    {
        return [
            'comment' => $this->comment,
        ];
    }
```
and then do
`$user->pay($product)`
and get what I want. But it's so ugly. Is there any option to do it right way?

**Comment by rez1dent3** [comment]
Hello. You need to use the shopping cart
```
use Bavix\Wallet\Objects\Cart;

$cart = app(Cart::class)
    ->addItems([$product])
    ->setMeta(['comment' => $comment])
;

$transfers = $buyer->payCart($cart);
```
