### ISSUE TITLE
Use Uuid column type insted of int for  holder_id colum

### ISSUE THREAD

**Issue by kamasuPaul** [bavix/laravel-wallet#451]
So after installing the package, and  doing all the necessary steps, to get it up and running, i run into this error
of not being able to insert a `wallet` because the `holder_id` is `int` and my modal has `uuid` primary keys, which i then changed, to uuid, but then still got this error
`Bavix\\Wallet\\Internal\\Events\\WalletCreatedEvent::__construct(): Argument #2 ($holderId) must be of type int, Ramsey\\Uuid\\Lazy\\LazyUuidFromString given`,
which in my understanding means, the `holder_id` column in the `wallets`  table should be int.
So is there a way of making holder of an id use uuid instead of int?

**Comment by rez1dent3** [comment]
@kamasuPaul Hello. Until version 8, the package works exclusively with int. Starting from version 8, it became possible to use string. You can upgrade to the latest version of the package, but it will not accept a UUID object, you will need to convert to a string.

**Comment by kamasuPaul** [comment]
Ok. Great. Thanks, let me look into using version 8
