### ISSUE TITLE
Error on checking wallet balance

### ISSUE THREAD

**Issue by jerexbambex** [bavix/laravel-wallet#452]
I have this error 
```php
Bavix\Wallet\Internal\Exceptions\TransactionFailedException with message 'Transaction failed'
```

on checking wallet balance using 
```php
$user->balance
```

**Comment by rez1dent3** [comment]
Hello. Need details.

**Comment by jerexbambex** [comment]
> 

After installation, I tried to test the wallet feature in tinker but I am getting the ```Transaction failed``` error.

although when I do this 
```php 
$user->wallet 
```   
It shows the wallet resource.

**Comment by rez1dent3** [comment]
You need a full error trace.  I won't be able to reproduce your error.

**Comment by jerexbambex** [comment]
> I need the full error trace. I won't be able to reproduce your error.

This is what I receive in tinker

```php
>>> $user = User::first();
[!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
=> App\Models\User {#4755
     id: "1bb65ceb-d739-4fb3-a6f4-4cd9dec7f6aa",
     provider_name: null,
     provider_avatar: null,
     first_name: "Olumide",
     last_name: "Brabus",
     email: "olumide@gmail.com",
     type: "buyer",
     avatar: null,
     phone_number: null,
     gender: null,
     email_verified_at: null,
     #password: "$2y$10$NbHloke2UZfFAXCsHRkL0u3j5aIjD4sdOh9K1sB8FcGlo/K1xSYvy",
     #remember_token: null,
     created_at: "2021-11-29 12:34:46",
     updated_at: "2021-11-29 12:34:46",
     deleted_at: null,
   }
>>> $user->balance
Bavix\Wallet\Internal\Exceptions\TransactionFailedException with message 'Transaction failed'
>>> 
```

**Comment by rez1dent3** [comment]
If there was a full trace, then I would have told you about your problem earlier.  There was partial support for guid only in the 8th version of the package.

**Comment by jerexbambex** [comment]
> If there was a full trace, then I would have told you about your problem earlier. There was partial support for guid only in the 8th version of the package.

Ohh you mean I cannot use UUID in this latest release?

**Comment by rez1dent3** [comment]
In version 8 you can, but for this you need to write a migration for the columns (transactions.payable_id, wallets.holder_id, transfers.from_id, transfers.to_id).

After you change the type from int to string (characters, binary characters, ...) you will greatly decrease the sampling rate in the negative direction, up to 25 times.

But UUID (GIUD) will work.
