### ISSUE TITLE
How to set float product price?

### ISSUE THREAD

**Issue by oranog** [bavix/laravel-wallet#454]
Hello, Product seem to be extending simple Wallet interface. What if product may have price with decimal points?

For example, if product price is 2.90 and we try to pay for it like this

`$user->safePay($item)`

The amount of 3.00 will be deducted from the user. That is not correct. User model uses CanPayFloat trait in this example.

Right now i've found the only solution (that seem not to be that great) is to convert value of getAmountProduct method from 2.90 to 290.

**Comment by rez1dent3** [comment]
Hello. No way. The package only works with integers to avoid problems with the mantissa.
You will have to convert this to an int anyway. You are correctly casting to int for the value decimal_places=2.
