### ISSUE TITLE
balance udpate is not happening in Nova Action

### ISSUE THREAD

**Issue by sinamiandashti** [bavix/laravel-wallet#455]
Hi

I tried to deposit balance to a user wallet inside a Nova Action

but the balance of the wallet is not updating ... I'm not sure if it depends to Locking mecansim or queue of laravel nova actions

but the balance is not updating

any suggestion ?

**Comment by rez1dent3** [comment]
Hello. Provide the code with which you change the balance. In general, you cannot change the balance parameter directly.

**Comment by sinamiandashti** [comment]
```php
public function handle(ActionFields $fields, Collection $models)
    {
        $title = 'Panel Transaction';
        $meta = ['description' => $fields->description,'title' => $title];
        /** @var User $model */
      foreach ($models as $model) {
            $model = $model->deposit($fields->amount, $meta);
             $this->markAsFinished($model);
       }

  


        return Action::message('Site balance updated successfully!');
    }
```

**Comment by sinamiandashti** [comment]
when this code executed via laravel nova action , the transaction record is created in DB , but the balance is not updated

but when I normally call "deposit" in other areas (like in controllers) it works

I did some investigation and find out that BookkeeperService::sync is not getting called inside laravel nova action somehow

I'm still investigating why

**Comment by ysfkaya** [comment]
I have the same issue. When I run the `refreshBalance` method after making a deposit, the balance is updated, but other than that, it does not.

Version: ^7.3
Laravel: ^8
Nova: ^3

**Comment by sinamiandashti** [comment]
yeah it has something to do with the locking/blocking

as workaround a distpach a job to do the deposit async @ysfkaya

**Comment by rez1dent3** [comment]
@sinamiandashti @ysfkaya Thank you. I'll try to debug this part this week. I have never tried to update the balance through nova. The admin panel was used only for displaying information.

**Comment by rez1dent3** [comment]
@sinamiandashti @ysfkaya At the moment, the solution is to put rollback in the first line. In the future, I will think about a solution out of the box, while there are no ideas.
```php
use Illuminate\Support\Facades\DB;
...
public function handle(ActionFields $fields, Collection $models)
{
    DB::rollBack(0);
...
}
```

**Comment by sinamiandashti** [comment]
If you can explain me how locking is working (or maybe in documentation) I could think about the solution
or if u can explain me the solution I can create a pull request and contribute

**Comment by rez1dent3** [comment]
It's not about blocking, but about the transaction that laravel nova hangs on the whole action.

The package should now be able to correctly implement the saga (db + cache). We throw the balance into the cache and hang a lock for all operations.

In case of an erroneous transaction, we should not update the data in the cache.

You can read more about the state in a transaction here: https://github.com/bavix/laravel-wallet/pull/412

**Comment by ibrunotome** [comment]
@rez1dent3 the same is happening if you run transactions in a migration, the balance in the wallet is only updated with `DB::rollBack(0);` at the beginning.

**Comment by rez1dent3** [comment]
@ibrunotome Yes, that's right. This is due to the framework transaction starting. If the package completely removes the fight against the race condition, then you can allow the use of framework transactions.

Right now, I'm leaning towards adding a new exception that will tell the client about the transaction that was fired above. This will get rid of obvious errors.

**Comment by rez1dent3** [comment]
At the moment there is only one solution to these cases. If I come up with a different solution, I'll be sure to update the documentation. Now the performance of the package is in the foreground.

Working with the internal state accelerated the package twice.
https://github.com/bavix/laravel-wallet-benchmark/

https://19b01766.laravel-wallet.pages.dev/#/nova-action

<img width="1440" alt="Снимок экрана 2022-03-31 в 20 26 55" src="https://user-images.githubusercontent.com/5111255/161114597-82837853-440b-4869-a5cf-8dd7db9dede5.png">
