### ISSUE TITLE
default wallet not created 

### ISSUE THREAD

**Issue by aissadado44** [bavix/laravel-wallet#457]
hi bros im use this package 
but 
whene i use 
$user->balance ;
is not works  bécasse the defult wallet not created 
if i create second wallet and select it its work 

i need help

**Comment by rez1dent3** [comment]
Hello. I need a full trace of the error, without it I can’t say anything.

**Comment by rez1dent3** [comment]
See #452. Maybe this is your problem too.

**Comment by aissadado44** [comment]
thanks all brothers  is my problem
implements Wallet
