### ISSUE TITLE
send user payment description

### ISSUE THREAD

**Issue by Temian1** [bavix/laravel-wallet#459]
so I was working with the the transfer functionality I was thinking how can I send the receiver a message or description about payment received?

also please can we pend transfer until the user confirms the product release payment

**Comment by rez1dent3** [comment]
Hello. So you can add a description to the transfer (transactions[deposit, withdraw]):
```
$user1->transfer($user2, 100,  ['message' => 'Ready to receive a translation?']);
```
https://bavix.github.io/laravel-wallet/#/transfer

You can implement deposit and withdrawal of funds through two operations. And after confirming... https://bavix.github.io/laravel-wallet/#/confirm

**Comment by Temian1** [comment]
@rez1dent3  I mean can transfer from wallet to Wallet be on pending until the user confirm the product

**Comment by rez1dent3** [comment]
@Temian1 What's the difference?  In any case, this logic needs to be developed for yourself.  There is no such solution out of the box.
