### ISSUE TITLE
how to get user transactions history

### ISSUE THREAD

**Issue by Temian1** [bavix/laravel-wallet#460]
so in user profile I did this not working tho can you help me out here
```
@foreach($user->transactions as transaction)
    {{ $transaction->amount }}
@endforeach

**Comment by rez1dent3** [comment]
Hello. What does the user model look like?

**Comment by rez1dent3** [comment]
Example:

https://github.com/bavix/laravel-wallet/blob/88913b5f30116956f8d6ea3dad8315930eb55e72/tests/Units/Domain/TransactionsFilterTest.php#L19-L34

**Comment by Temian1** [comment]
my user model has The Wallet And HasWallet Traits nothing special

**Comment by rez1dent3** [comment]
then the example above should work.

**Comment by Temian1** [comment]
you mean like this will work
```
$buyer = Auth()->user()
$traansactions = $buyer->transactions()->count()

**Comment by rez1dent3** [comment]
Yes. Your example should work too

**Comment by humaneguy** [comment]
This issue can be closed now.
