### ISSUE TITLE
Null Uuid when retrieving balance

### ISSUE THREAD

**Issue by humaneguy** [bavix/laravel-wallet#462]
Hi I encounter this error when trying to get a user's balance

`Bavix\Wallet\Services\RegulatorService::getKey(): Argument #1 ($uuid) must be of type string, null given, called in /home/vendor/bavix/laravel-wallet/src/Services/RegulatorService.php on line 45`

**Comment by rez1dent3** [comment]
Hello. You don't have a uuid in your wallet, that's the problem. Most likely you updated the package without performing a migration. https://github.com/bavix/laravel-wallet/blob/88913b5f30116956f8d6ea3dad8315930eb55e72/database/2021_11_02_202021_update_wallets_uuid_table.php#L20-L40

**Comment by rez1dent3** [comment]
https://bavix.github.io/laravel-wallet/#/upgrade-guide?id=_6xx-%e2%86%92-7xx

**Comment by humaneguy** [comment]
Yeah. I had to run migration

**Comment by humaneguy** [comment]
Hi @rez1dent3, after running the migration, the uuid columns are empty. They're supposed to contain values right?

**Comment by rez1dent3** [comment]
Yes, the data should be populated with random uuids.  If suddenly this did not happen to you (this should not happen), then you need to fill it out manually.

**Comment by humaneguy** [comment]
I have about 57k rows.

**Comment by humaneguy** [comment]
How do I go about filling them manually?

**Comment by rez1dent3** [comment]
sql update query with uuid

**Comment by rez1dent3** [comment]
Migration, in theory, should not be marked as completed, as at the end the ability to put down nullable value instead of uuid is removed.  Need some context from you to give more information

**Comment by rez1dent3** [comment]
@humaneguy Have you solved the problem?

**Comment by humaneguy** [comment]
Yeah. I have.
