### ISSUE TITLE
Model Events Seem not to be firing

### ISSUE THREAD

**Issue by emmannl** [bavix/laravel-wallet#465]
**Describe the bug**
I extended the Transaction model that comes with this package and updated the config file accordingly. I included a trait in this custom model which is [bootable](https://laravel-news.com/booting-eloquent-model-traits) and should.
Unfortunately this trait is not booted. I have also tried defining [closure based events](https://laravel.com/docs/9.x/eloquent#events-using-closures) with no luck.

**To Reproduce**
Extend any Model provided by this library and either use a bootable trait or define a closure based event in your custom model. Notice that the events are not fired.

**Expected behavior**
Bootable traits and closure based events should work properly.

**Server:**
 - php version: 8.1
 - database: sqlite
 - wallet version 8.2

**Comment by rez1dent3** [comment]
Hello. This is not a bug. So it should be, the main emphasis of the package on performance. Therefore, we unbind the eloquent events and dispatch new events on top of the events. Inside the package, there are two events that you can listen to. If an additional event is needed, then you can bring the PR and, perhaps, he will fall into the master.

**Comment by emmannl** [comment]
I'm using snowflakes for IDs on my current application. I was hoping to use same for the ids on the tables this package works with.

A PR with more events would not be the best in this case.

**Comment by ibrunotome** [comment]
> I'm using [snowflakes](https://github.com/kra8/laravel-snowflake) for IDs on my current application. I was hoping to use same for the ids on the tables this package works with.
> 
> A PR with more events would not be the best in this case.

I also use snowflakes for ids in the wallet too. You just need to override the transformes in wallet settings for Transaction and Transfer models, including the id generation in the returned transformed DTO to array.

```php
    /**
     * Objects of transformer from DTO to array.
     */
    'transformers' => [
        'transaction' => WalletTransactionDtoTransformer::class,
        'transfer'    => WalletTransferDtoTransformer::class,
    ],
``` 

Wallet model should work properly with bootable event.

**Comment by rez1dent3** [comment]
Hmm, very interesting approach.  Thank you.  However, I cannot guarantee future support for this package.
