### ISSUE TITLE
Error when trying to fetch merchants.

### ISSUE THREAD

**Issue by humaneguy** [bavix/laravel-wallet#467]
When trying to fetch merchants with their wallet, I seem to be encountering an error

This is the code being executed

```php
return User::query()->whereHas('wallet', function($query) {
            $query->where('balance', '>=', 10);
        })->whereHas('transactions', function($query) {
            $query->where('created_at', '>=', now()->subMonth());
        })->selectSub(function ($query) {
            $query->selectRaw('IFNULL(SUM(amount), 0)')->from('transactions')->where('wallet_id', '=', DB::raw('transactions.wallet_id'));
        }, 'lastBalance')->get();
```

I seem to be getting this error.

This is the error I'm getting. https://flareapp.io/share/87na3DMP#F65

**Comment by humaneguy** [comment]
The query works well. When I'm trying access the balance of a merchant that's when it throws the error.

So for example:

```php
<option value="{{$merchant->id}}">{{$merchant->first_name . " " . $merchant->last_name}} {{ $merchant->msisdn }} (Bal: ₦{{ number_format($merchant->wallet->balance, 2) }})</option>

```

**Comment by rez1dent3** [comment]
In your example, only select, but here insert. Somewhere you have a transaction created from an unsaved user.

> Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'holder_id' cannot be null

![screen](https://user-images.githubusercontent.com/5111255/163150432-fb9af3e4-d16b-4f49-9b24-42da2411cd71.png)

**Comment by humaneguy** [comment]
Is there a way I can find out who this user is?

**Comment by rez1dent3** [comment]
You need to profile your code.  Somewhere you have the creation of a transaction from such a user, and where I don’t tell you, you’ll have to look for it yourself

**Comment by rez1dent3** [comment]
In general, the package does not impose additional restrictions. Read documentation: https://laravel.com/docs/9.x/eloquent-relationships
