### ISSUE TITLE
getting problems with CreateTransactionsTable

### ISSUE THREAD

**Issue by rovillesarate** [bavix/laravel-wallet#47]
Getting the following error when i try to migrate the db
`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `uuid` char(36) not null, `created_at` timestamp null, `updated_at` t' at line 1 (SQL: create table `transactions` (`id` int unsigned not null auto_increment primary key, `payable_type` varchar(255) not null, `payable_id` bigint unsigned not null, `type` enum('deposit', 'withdraw') not null, `amount` bigint not null, `confirmed` tinyint(1) not null, `meta` json null, `uuid` char(36) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_general_ci' engine = InnoDB)`

**Comment by rez1dent3** [comment]
Hello. @rovillesarate What version is mariadb version?

**Comment by rez1dent3** [comment]
@rovillesarate https://github.com/laravel/framework/issues/13622#issuecomment-221567026

**Comment by rez1dent3** [comment]
@rovillesarate added crutch to the database without support for JSON. The master branch.
```bash
composer req bavix/laravel-wallet:dev-master
```

Expect the release tomorrow.

**Comment by rez1dent3** [comment]
@rovillesarate tag 3.0.2
