### ISSUE TITLE
confirmed option in transfer

### ISSUE THREAD

**Issue by clickervinod** [bavix/laravel-wallet#475]
Hi,

I want to add confirmed option in transfer  as it is in transaction. Is ther any way to do this.

Thanks

**Comment by rez1dent3** [comment]
Hello. #439 
Such functionality needs to be developed independently. There is no such option out of the box.

**Comment by rez1dent3** [comment]
As part of the draft, I implement this functionality as well. https://github.com/bavix/laravel-wallet/pull/479

**Comment by rez1dent3** [comment]
Preliminary syntax for this functionality in 9.x.

```php
        $transfer = $user1->transfer(
            $user2,
            500,
            new Extra(
                deposit: [
                    'type' => 'extra-deposit',
                ],
                withdraw: new Option(
                    [
                        'type' => 'extra-withdraw',
                    ],
                    false
                ),
            )
        );
```
