### ISSUE TITLE
add diffrent description for transfer

### ISSUE THREAD

**Issue by clickervinod** [bavix/laravel-wallet#476]
Hi,

Can we add option to add diffrent description in transfer . currently same desctiption is added in both transaction of a transfer.

**Comment by rez1dent3** [comment]
Hello. Now this is not possible, but you can override the TransferLazyDtoAssemblerInterface inside which and implement the necessary functionality.

If I have time this week, I'll make an example.

**Comment by rez1dent3** [comment]
#479 While a draft. I'm considering implementation as long as I like it. If everything goes well, then this feature will appear in 9.x.

**Comment by rez1dent3** [comment]
Preliminary syntax for this functionality in 9.x.

```php
        $transfer = $user1->transfer(
            $user2,
            500,
            new Extra(
                deposit: [
                    'type' => 'extra-deposit',
                ],
                withdraw: new Option(
                    [
                        'type' => 'extra-withdraw',
                    ],
                    false
                ),
            )
        );
```

**Comment by rez1dent3** [comment]
#475 I will close. Because in fact, this is one issue.

**Comment by rez1dent3** [comment]
The syntax stuck. One of these days the first alpha version 9.x will be released. There you can try this functionality.

**Comment by rez1dent3** [comment]
@clickervinod tag 9.0.0
