### ISSUE TITLE
Trying to get property 'balance' of non-object

### ISSUE THREAD

**Issue by masitings** [bavix/laravel-wallet#477]
**Describe your task**
Hi guys, i have a problem when i want to get the balance from the default wallet.

**To Reproduce**
1. I have put the same exact tutorial from the Basic Usage of the Documentation on User model, this is my code
```php
namespace App\Models;

use Bavix\Wallet\Interfaces\Customer;
use Bavix\Wallet\Interfaces\Wallet;
use Bavix\Wallet\Traits\CanPay;
use Bavix\Wallet\Traits\HasWallet;
use Bpuig\Subby\Traits\HasSubscriptions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Ramsey\Uuid\Uuid;
use Staudenmeir\EloquentHasManyDeep\HasRelationships;

class User extends Authenticatable implements Wallet, Customer
{
    use HasApiTokens, HasFactory, Notifiable, HasSubscriptions, HasWallet, CanPay, HasRelationships;
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'uuid',
        'email',
        'password',
        'ext_phone',
        'phone',
        'google_id',
        'facebook_id',
        'referrer_id',
        'referral_token',
        'referral_reward_percent'
    ];
```

2. And nothing happen here until i try test to see if its works using TestController that i've create : 
```php
public function index()
{
    $user = auth()->user();
    return $user->balance;
}
```

**Expected behavior**
I just want it works on my application and it seems didn't work out.

**Server:**
 - php version: 7.4.3
 - database: Mysql  8.0.28-0ubuntu0.20.04.3]
 - wallet version ^7.3
 - cache lock: -
 - cache wallets: -

**Comment by rez1dent3** [comment]
@masitings Hello.
> Trying to get property 'balance' of non-object
You are trying to get balance from null. Apparently you don't have a user in the request.
