### ISSUE TITLE
Handling Race Conditions

### ISSUE THREAD

**Issue by segun931** [bavix/laravel-wallet#484]
Hi @rez1dent3, what an awesome package you've got here.

My observation is that when concurrent requests are made to withdraw from a wallet, all the requests go through irrespective of the user balance. And from the package documentation, a mention is made of handling this using redis. 

I have followed the redis configuration guide on the package documentation however, race conditions still occur.

Kindly assist with an explainer on how to fix this.

**Comment by rez1dent3** [comment]
Hello, @segun931. I can't help you without technical information (db, php, package, cache, lock...). How many seconds of waiting in the lock service. In my project, the race condition went away in version 4.x. Describe the problem in more detail and better with code examples.

**Comment by segun931** [comment]
Finally figured it out.
