### ISSUE TITLE
Cannot install on Laravel 8.83.0

### ISSUE THREAD

**Issue by goodmuyis** [bavix/laravel-wallet#496]
I ran the install command `composer req bavix/laravel-wallet` and `composer require bavix/laravel-wallet`

I got the error below. I have searched google but cannot find a solution

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bavix/laravel-wallet[9.0.0-alpha, ..., 9.0.0] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bavix/laravel-wallet ^9.0 -> satisfiable by bavix/laravel-wallet[9.0.0-alpha, ..., 9.0.0].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

What am I missing?

**Comment by rez1dent3** [comment]
Hello. You need version 7.x of the package:
```bash
composer req bavix/laravel-wallet:^7.3
```

**Comment by rez1dent3** [comment]
Here is the info from the readme.

| Version    | Laravel        | PHP         | End of improvements | End of support |
|------------|----------------|-------------|---------------------|----------------|
| 7.x        | ^6.0,^7.0,^8.0 | 7.4,8.0,8.1 | 1 Mar 2022          | 6 Sep 2022     |
| 8.x        | ^9.0           | 8.0,8.1     | 1 May 2022          | 1 Jun 2022     |
| 9.x [LTS]  | ^9.0           | 8.0,8.1     | 1 Feb 2023          | 6 Nov 2023     |

**Comment by goodmuyis** [comment]
> Hello. You need version 7.x of the package:
> 
> ```shell
> composer req bavix/laravel-wallet:^7.3
> ```

Thank for the quick reply. It works now. Be blessed
