### ISSUE TITLE
How to update transaction meta data?

### ISSUE THREAD

**Issue by nagsamayam** [bavix/laravel-wallet#498]
Hi @rez1dent3 

I am facing below error when I am trying to update meta data

`
Transaction failed. Message: Indirect modification of overloaded property Bavix\Wallet\Models\Transaction::$meta has no effect.
`

Below is my code snippet

```bash
use Bavix\Wallet\Models\Transaction;

$txn = Transaction::find(1);
$txn->meta['description'] = 'Your transaction has been approved';
$txn->save();
```

Can you please suggest how to update transaction meta data?

**Comment by rez1dent3** [comment]
Hello. You cannot update part of the array, you must overwrite the entire property.
https://github.com/bavix/laravel-wallet/blob/7ae5d696454928508f35b20df3b3db1c9fc7792b/tests/Units/Domain/BalanceTest.php#L59-L63
