### ISSUE TITLE
Transaction failed. Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta' in 'field list'

### ISSUE THREAD

**Issue by Jacobtims** [bavix/laravel-wallet#500]
**Describe your task**
I updated the package from 6.1 to 9.0.0 (the latest).
I followed the migration guides.

**Trace Error**
https://flareapp.io/share/17WbgxEP#F98

**Server:**
 - php version: 8.0
 - database: mySQL
 - wallet version 9.0.0

Why can't I get the user's balance anymore?

**Comment by rez1dent3** [comment]
Hello, @Jacobtims. In version 6.2, a "meta" column was added to the wallets table. First you had to upgrade to 6.2.4, after to 7.3.3, after to 8.4.1, and after that, switch to 9.0.0. I don't support upgrading across multiple versions. I assume users are updated sequentially.

**Comment by rez1dent3** [comment]
@Jacobtims I checked, there is no difference in migrations between 7.3.3 and 9.0.0. Therefore, it is enough to switch to 6.2.4, and after that roll 9.0.0.

**Comment by Jacobtims** [comment]
Thx that worked!
