### ISSUE TITLE
How to use paginate in Transition

### ISSUE THREAD

**Issue by huyvv12** [bavix/laravel-wallet#501]
$transactions = Transaction::where(function ($query) use ($select) {
			$query->where('payable_id', '=', $select)
				->join('wallets', 'transactions.wallet_id', '=', 'wallets.id')
				->select('transactions.*', 'wallets.name')
				->get();
		})->orderBy('created_at', 'desc')
			->paginate(10);

/// here is my code but when I click on page 2 it isn't work

**Comment by huyvv12** [comment]
I want to use pagination in Transition.

**Comment by rez1dent3** [comment]
I asked about the problem you are trying to solve with your request. Here's an example with a eagerly loaded wallet.

```php
        Transaction::with('wallet')
            ->where('payable_id', $payableId)
            ->orderBy('created_at', 'desc')
            ->paginate(10);
```

In theory, your request should work well. I think your problem is somewhere else.

https://laravel.com/docs/9.x/pagination#paginating-eloquent-results

PS, please don't duplicate the issue.

**Comment by huyvv12** [comment]
sorry my english isn't good. I want to get some information in the database to show out to the user. And I want each page to have 10 records. But when my database has 11 records, I click to the second page it doesn't work.

**Comment by rez1dent3** [comment]
My example should suit you. Have you tried it?

**Comment by rez1dent3** [comment]
@huyvv12 I wrote a test for your case and everything works for me.

https://github.com/bavix/laravel-wallet/blob/623de51fb798d0a91c6eeb890dc1b78c91c089c1/tests/Units/Domain/TransactionsFilterTest.php#L117-L132

**Comment by rez1dent3** [comment]
@huyvv12 Here's your example, and it works.

https://github.com/bavix/laravel-wallet/blob/d3e8c3e436a9a34464b3ca129cf4dcdb0e6fb9fd/tests/Units/Domain/TransactionsFilterTest.php#L152-L176

**Comment by huyvv12** [comment]
> @huyvv12 Here's your example, and it works.
> 
> https://github.com/bavix/laravel-wallet/blob/d3e8c3e436a9a34464b3ca129cf4dcdb0e6fb9fd/tests/Units/Domain/TransactionsFilterTest.php#L152-L176
