### ISSUE TITLE
unable to install in laravel 8 getting error

### ISSUE THREAD

**Issue by Temian1** [bavix/laravel-wallet#506]
Problem 1
    - bavix/laravel-wallet[9.0.0-alpha, ..., 9.0.1] require illuminate/contracts
 ^9.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev] but these were
not loaded, likely because it conflicts with another require.
    - Root composer.json requires bavix/laravel-wallet ^9.0 -> satisfiable by ba
vix/laravel-wallet[9.0.0-alpha, ..., 9.0.1].

**Comment by rez1dent3** [comment]
Hello. #496
