### ISSUE TITLE
Bavix\Wallet\Internal\Repository\WalletRepository::getBySlug(): Argument #2 ($holderId) must be of type string|int, null given, called in <project>\vendor\bavix\laravel-wallet\src\Services

### ISSUE THREAD

**Issue by Vladimir-Urik** [bavix/laravel-wallet#509]
**Describe your task**
I started migrations, implemented "Wallet" and added Has Wallet, Has Wallets. I added the
```php
    protected function books(): Attribute
    {
        $myWallet = $this->getWallet('books');
        return new Attribute(
            get: fn () => $myWallet->balanceInt,
        );
    }
```
 attribute and added its append to the serialization. An error occurred after running the request.

**To Reproduce**
Check **Describe your task**

**Trace Error**
[Error](https://flareapp.io/share/OmVDppA7#F61)

**Expected behavior**
Serialization of the balance in the "books" account

**Server:**
 - php version: 8.1.4 
 - database: mysql 8.0
 - wallet version ^9.0
 - cache lock:  array
 - cache wallets:  array

**Comment by Vladimir-Urik** [comment]
![obrázok](https://user-images.githubusercontent.com/47532155/170940981-cbb02f9f-517a-4376-8c55-607c65efb983.png)

**Comment by rez1dent3** [comment]
Hello, @Vladimir-Urik. There are two options here:
- Your primary key is not numeric (for example, guid);
- Your user does not exist at the time getWallet is called;
