### ISSUE TITLE
barryvdh/laravel-ide-helper model generate bug

### ISSUE THREAD

**Issue by keatliang2005** [bavix/laravel-wallet#516]
**Describe the bug**
Since [3.1.4](https://github.com/bavix/laravel-wallet/releases/tag/3.1.4) mention the package is supported, but it has similar bug occur on issue https://github.com/bavix/laravel-wallet/issues/78 , but this time is `walletTransactions()` method from HasWallet Trait, I am using MySQL 5.7

i am not sure why the `\Bavix\Wallet\Services\CastService::getWallet` would get executed, if laravel-ide-helper is just simply do code reflection and parse the methods. so i don't have any good idea to resolve this.

**To Reproduce**
when running `artisan ide-helper:models "App\Models\User" --verbose`,

It Produce the error
```bash
 Do you want to overwrite the existing model files? Choose no to write to _ide_helper_models.php instead (yes/no) [no]:
 > 

Loading model 'App\Models\User'
Error resolving relation model of App\Models\User:walletTransactions() : Transaction failed. Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'holder_id' cannot be null (SQL: insert into `wallets` (`balance`, `decimal_places`, `uuid`, `holder_id`, `holder_type`, `name`, `slug`, `meta`, `updated_at`, `created_at`) values (0, 2, c82437ae-200c-454c-bebf-315e29604692, ?, App\Models\User, Default Wallet, default, [], 2022-06-16 12:35:06, 2022-06-16 12:35:06))
Model information was written to _ide_helper_models.php

```

**Trace Error**
I have narrow it down to specific class that produce the error `\Bavix\Wallet\Services\CastService::getWallet`

```php
    /**
     * @throws ExceptionInterface
     */
    public function getWallet(Wallet $object, bool $save = true): WalletModel
    {

        $wallet = $this->getModel($object);
        if (!($wallet instanceof WalletModel)) {
            $wallet = $wallet->getAttribute('wallet');
            assert($wallet instanceof WalletModel);
        }

        if ($save && !$wallet->exists) {
            $this->databaseService->transaction(function () use ($wallet) {

                $result = $wallet->saveQuietly(); // << saving will cause error because $wallet->holder_id the value is null
                $this->dispatcherService->dispatch($this->walletCreatedEventAssembler->create($wallet));

                return $result;
            });
        }

        return $wallet;
    }
```

**Expected behavior**
able to generate helper dockblock which implement the `Bavix\Wallet\Interfaces\Wallet` and use trait `Bavix\Wallet\Traits\HasWallet`  which result  with dockblock below

```php
/**
 * @property-read \Illuminate\Database\Eloquent\Collection|\Bavix\Wallet\Models\Transaction[] $walletTransactions
 * @property-read int|null $wallet_transactions_count
 */
```

**Screenshots**
<img width="1587" alt="Screenshot 2022-06-16 at 8 47 30 PM" src="https://user-images.githubusercontent.com/473990/174072936-64ae1ca1-5cc9-49f8-84ac-999f0f62577d.png">

**Server:**
 - php version: 8.0.8
 - database: mysql 5.7.34
 - wallet version 9.0.1
 - cache lock: array
 - cache wallets: array

**Additional context**
it seems like when run `php artisan ide-helper:models` it would try to execute save wallet for non exists user, in other words it tries to create wallet without user_id `holder_id`

**Comment by rez1dent3** [comment]
@keatliang2005 thank you. tag: 9.0.2
