### ISSUE TITLE
reset the balance of all users

### ISSUE THREAD

**Issue by imRezaAlie** [bavix/laravel-wallet#522]
Dears,
There are about 2000 users in my project, how can I reset the balance of all users to zero?

laravel ver : 8 
database  : mysql

regards,
reza

**Comment by rez1dent3** [comment]
Hello. Create a console command that will run through all users and, depending on the balance, make the replenishment or withdrawal of funds to zero. There is no such functionality out of the box and never will be.

**Comment by imRezaAlie** [comment]
Dear @rez1dent3 ,
`     $users=User::all();
     foreach ($users as $user)
     {
         if($user->balance > 0){
             $user->withdraw($user->balance,['description'=>'yearly reset balance']);
         }
      }`
i think above solution not bad

**Comment by rez1dent3** [comment]
@imRezaAlie If the user's balance is <0, then you will not reset the balance to zero. In this case, you need to call deposit
