### ISSUE TITLE
Confliction With Laravel Cashier

### ISSUE THREAD

**Issue by hilal-hipster** [bavix/laravel-wallet#530]
**Describe the bug**
Already handling subscriptions with Laravel Cashier, so as per Laravel Cashier my User Model contains Cahier's **Billable** trait
```
use Laravel\Cashier\Billable; 
class User extends Authenticatable
{
   use Billable;
    ....
    ....
}
```
Now, need to use Wallet's Purchases feature So Changed my User model to this
```
use Laravel\Cashier\Billable;
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Interfaces\Wallet;
use Bavix\Wallet\Traits\CanPay;
use Bavix\Wallet\Interfaces\Customer;
class User extends \TCG\Voyager\Models\User implements Customer
{
    use Billable, HasApiTokens, HasFactory, Notifiable, SoftDeletes, HasWallet;
    use CanPay;
    .......
    .....
 ```

But now I am getting below error and even unable to serve.
**PHP Fatal error:  Trait method Bavix\Wallet\Traits\CanPay::pay has not been applied as App\Models\User::pay, because of collision with Laravel\Cashier\Billable::pay in /var/www/html/better_cloud/app/Models/User.php on line 20

   Symfony\Component\ErrorHandler\Error\FatalError 

  Trait method Bavix\Wallet\Traits\CanPay::pay has not been applied as App\Models\User::pay, because of collision with Laravel\Cashier\Billable::pay**

![image](https://user-images.githubusercontent.com/43673169/181010603-ee99550c-b5b5-4e75-9a8a-0e1c24fad214.png)

**Comment by rez1dent3** [comment]
Hello. duplicate #87
You need to use the functionality of [Multi Wallets](https://bavix.github.io/laravel-wallet/#/new-wallet).

Model example: https://github.com/bavix/laravel-wallet/blob/77b781e2ccef1a4638d5fb414a5a1f5570ba5777/tests/Infra/Models/UserCashier.php

**Comment by hilal-hipster** [comment]
Hey @rez1dent3 
Thanks for the prompt response, the wallet is working as expected with cashier until and unless am not adding "**CanPay** trait and **Customer** interface to your User model."

```
use Bavix\Wallet\Traits\CanPay;
use Bavix\Wallet\Interfaces\Customer;

class User extends Model implements Customer
{
    use CanPay;
    ....
    ....
```

No collision with Cashier if am not using CanPay Trait along with Customer interface.

**Comment by hilal-hipster** [comment]
> Hello. duplicate #87 You need to use the functionality of [Multi Wallets](https://bavix.github.io/laravel-wallet/#/new-wallet).
> 
> Model example: https://github.com/bavix/laravel-wallet/blob/77b781e2ccef1a4638d5fb414a5a1f5570ba5777/tests/Infra/Models/UserCashier.php
> 
> https://github.com/bavix/laravel-wallet/blob/59a80260ae78f9f993acf0049de83d597bda534f/tests/Units/Domain/MultiWalletTest.php#L530-L554

In reference of suggested way to implement desired functionality I have changed my User model to be like this 
```
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Traits\MorphOneWallet;
use Bavix\Wallet\Traits\CanPay;
use Bavix\Wallet\Interfaces\Customer;
use Laravel\Cashier\Billable;

class User extends \TCG\Voyager\Models\User implements Customer
{
    use Billable, HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    use HasWallets;
    use MorphOneWallet;
    use CanPay;

```
But still am facing the same problem 
![image](https://user-images.githubusercontent.com/43673169/181162019-2edc7569-616f-4db0-a35f-cfa0b4ca7576.png)


Can see in the above image am even unable to make the server up i.e, `php artisan serve` itself fails with the above error.

**Comment by rez1dent3** [comment]
So it will not work, because.  Packages use methods with the same name.  You need to use multi wallets, they have all the necessary functionality

**Comment by rez1dent3** [comment]
I mean, CanPay is already inside the wallet and there is no need to mark it in the model

**Comment by hilal-hipster** [comment]
So @rez1dent3 
Need to change this 
```
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Traits\MorphOneWallet;
use Bavix\Wallet\Traits\CanPay;
use Bavix\Wallet\Interfaces\Customer;
use Laravel\Cashier\Billable;

class User extends \TCG\Voyager\Models\User implements Customer
{
    use Billable, HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    use HasWallets;
    use MorphOneWallet;
    use CanPay;

```

to this

```
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Traits\MorphOneWallet;
use Laravel\Cashier\Billable;

class User extends \TCG\Voyager\Models\User 
{
    use Billable, HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    use HasWallets;
    use MorphOneWallet;

```

**Comment by rez1dent3** [comment]
Yes

**Comment by hilal-hipster** [comment]
Changing the User Model to look like this 
```
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Traits\MorphOneWallet;
use Laravel\Cashier\Billable;

class User extends \TCG\Voyager\Models\User 
{
    use Billable, HasApiTokens, HasFactory, Notifiable, SoftDeletes;
    use HasWallets;
    use MorphOneWallet;
```


can serve now.
Let me tinker and test **Purchases** flow now 

@rez1dent3 Thanks mate (y)

**Comment by hilal-hipster** [comment]
Furthermore, just to clear silly doubt 
`$user->balance` gives Error with exception as
LogicException with message 'App\Models\User::balance must return a relationship instance.'

Need to use full syntax in place of shorthand syntax right?

`$user->wallet->balance`

**Comment by hilal-hipster** [comment]
@rez1dent3 
Now with the wallet's **Purchases** module
Whenever am doing this
```
$item = Item::first();
$item->getAmountProduct($user);
```
am receiving an error saying ** TypeError: App\Models\Order::getAmountProduct(): Argument #1 ($customer) must be of type Bavix\Wallet\Interfaces\Customer, App\Models\User given on line 1 **
![image](https://user-images.githubusercontent.com/43673169/181168957-89371731-2a96-4fe4-ae91-d4dcf9e1abb6.png)

**Comment by rez1dent3** [comment]
purchases come from the wallet.  you need to get the wallet and pass it to the method

**Comment by hilal-hipster** [comment]
So need to change 
```
$item = Item::first();
$item->getAmountProduct($user);
```
with this 
```
$item = Item::first();
$item->getAmountProduct($user->wallet);
```

**Comment by rez1dent3** [comment]
if the purchase was this wallet, then yes

**Comment by hilal-hipster** [comment]
Well as per your suggestion am using multi wallet now but am not creating any new wallet rather than working with default wallet as of now
So yes the purchase needs to use User's default wallet which we can get by `$user->wallet` or we need to use something else?

**Comment by hilal-hipster** [comment]
Maxim @rez1dent3 
Thanks for the quick support as well as such an awesome digital wallet.

**Comment by rez1dent3** [comment]
yes, if you only use one wallet, then you need to transfer it. I wrote this for general understanding.
