### ISSUE TITLE
Wallet Balance life-span

### ISSUE THREAD

**Issue by hilal-hipster** [bavix/laravel-wallet#532]
Hello @rez1dent3 
Does the wallet have a feature to expire wallet balance throughout the lifecycle?
For example, If I'm going to top-up my wallet each and every top-up added balance can have (say) 1 year of expiry from the date of topup?

**Comment by rez1dent3** [comment]
Hello. There is no such functionality. You need to develop yourself.

**Comment by hilal-hipster** [comment]
Okay @rez1dent3 understood.
