### ISSUE TITLE
Any Means to listen to Transaction::created Event?

### ISSUE THREAD

**Issue by myckhel** [bavix/laravel-wallet#535]
**Is your feature request related to a problem? Please describe.**
I would like to observe `Transaction::created` or listen to `Transaction::created` event.

**Describe the solution you'd like**
Emit `Transaction::created` event on transactions created

**Comment by rez1dent3** [comment]
Hello. Thank you. I will think about your idea.

**Comment by rez1dent3** [comment]
@myckhel hello. tag 9.1.0

**Comment by myckhel** [comment]
Thanks To you @rez1dent3 You are the G.O.A.T
