### ISSUE TITLE
how can I check if user withdraw is not yet confirmed 

### ISSUE THREAD

**Issue by Temian1** [bavix/laravel-wallet#536]
so a user placed a withdraw which is not yet confirmed, I want to restrict the user from requesting another withdraw 

because when a user requested a withdraw there balance is still intact

so how I check if user have a pending withdraw and restrict the user from making another request

**Comment by rez1dent3** [comment]
Hello. 
1. Put a lock;
2. Check the number of unconfirmed transactions per wallet/user (according to business logic);
3. Release the lock;

An example sql query.
```sql
select count(1) 
from transactions 
where wallet_id = 42 and confirmed = 0;
```

---
You can, when requesting a withdrawal of funds, throw it into the key-value storage and use the flag.

Pseudocode (redis):
```
127.0.0.1:6379> set withdrawal_42 1 
OK
127.0.0.1:6379> get withdrawal_42
"1"
127.0.0.1:6379> del withdrawal_42
(integer) 1
127.0.0.1:6379> get withdrawal_42
(nil)
```

**Comment by Temian1** [comment]
do you mean something like this
```
 $user = auth()->user();
        $confirm =  $user->transactions()->where('confirmed', 0)->latest()->take(1);

**Comment by rez1dent3** [comment]
Yes, you can.  But I would implement the storage through the key-value (so there will be no extra load on the database)
