### ISSUE TITLE
Null Uuid when retrieving balance

### ISSUE THREAD

**Issue by Zero-jano** [bavix/laravel-wallet#539]
**Describe your task**
 Null Uuid when retrieving balance in blade or control class

**Trace Error**
Bavix\Wallet\Services\RegulatorService::getKey(): Argument #1 ($uuid) must be of type string, null given, called in project/vendor/bavix/laravel-wallet/src/Services/RegulatorService.php on line 45

**Screenshots**

<img width="1369" alt="Screen Shot 2022-08-04 at 1 44 19 PM" src="https://user-images.githubusercontent.com/17266752/182828550-64403767-facd-4e94-b489-9b2bb1c40cfe.png">

**Server:**
 - php version: 8.0
 - database:  mysql 8.0
 - wallet version 8.4

**Additional context**
I update everything in class and config but still not fix

**Comment by rez1dent3** [comment]
Hello.
1. User ID of type int?
2. Is the user exactly stored in the database?

**Comment by Zero-jano** [comment]
it was working before in version 8 but when to upgrade to 9 this issue occurs

**Comment by rez1dent3** [comment]
Describe the problem in detail.  At the moment, I don't understand what to check.

**Comment by Zero-jano** [comment]
This issue occur because I upgrade the laravel-wallet from 8 to 9 version because I upgraded also laravel version to 9 but before was worked fine

**Comment by rez1dent3** [comment]
I need code examples to reproduce the problem. I don't see such a problem.

**Comment by Zero-jano** [comment]
this code was working before but when upgrading the version of wallet from 8 to 9 , do you get like this issue when some when was working in version 8 and upgrade to 9 ????

**Comment by rez1dent3** [comment]
When switching to 9.x, strong typing was added. Your code may not have worked correctly before.
It's hard for me to judge the correctness of code without code.

**Comment by Zero-jano** [comment]
Thank you but I found the issue, that was in the database need to add a UUID column in the wallet table

**Comment by rez1dent3** [comment]
Yes, I forgot about this.  Thank you for report
