### ISSUE TITLE
feat: fallback cache and lock driver

### ISSUE THREAD

**Issue by ibrunotome** [bavix/laravel-wallet#546]
**Is your feature request related to a problem? Please describe.**

Recently, I got almost 100 concurrent requests to debit balance from one wallet via api, and I got a redis exception "could not acquire lock"

**Describe the solution you'd like**

Read data directly from database when could not acquire lock (and update the state in redis in the next request)

**Describe alternatives you've considered**

Tried other cache drivers, but the only centralized is redis, array driver for example would give two different results if you access balance in a http container vs a container for queues for example.

P.S: I would put a warning about that non centralized cache drivers in the docs.

**Comment by rez1dent3** [comment]
Hello.
This is not a package issue, but an infrastructure issue. Redis did its job, you didn't get a race condition.
Consider a cluster solution, for example
https://redis.io/docs/manual/sentinel/

**Comment by ibrunotome** [comment]
Hi @rez1dent3, thank you for the quick support.

But, I didn't said it's a package issue, I made a feature request.

Would it possible to make a change to achieve this behavior?

**Comment by rez1dent3** [comment]
> Would it possible to make a change to achieve this behavior?

No. This is the infrastructure layer. The code shouldn't work in that case.

Your cache should be behind a balancer (for example, haproxy) and monitor it. In case of problems, change the master.

I would consider sentinel if I were you.

**Comment by rez1dent3** [comment]
For example, if you solve this with code, then you need to maintain data consistency in the failback storage. And this is already overhead.

**Comment by rez1dent3** [comment]
If you are going to solve a problem with code, you will most likely have a race condition.

Sample packages can be found in packagist. Someone solved a similar problem: https://github.com/mathieu-bour/laravel-cache-fallback

PS, I highly recommend using cluster solutions.

**Comment by ibrunotome** [comment]
Thank you for all the links/recommendations.

**Comment by rez1dent3** [comment]
@ibrunotome You are welcome.
If you want to pull the balance directly, then interfaces will help you:
https://github.com/bavix/laravel-wallet/blob/c6b8a229e098b2bc0415b24f10db4ffd3194226c/src/Services/BookkeeperServiceInterface.php#L11
https://github.com/bavix/laravel-wallet/blob/c6b8a229e098b2bc0415b24f10db4ffd3194226c/src/Services/RegulatorServiceInterface.php#L9

Strongly do not abuse and read the feature of working with the state #412

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/blob/7a30789a2f102f5dd1e4a094a177e726cdb64f0b/tests/Units/Domain/StateTest.php#L80-L98

**Comment by rez1dent3** [comment]
@ibrunotome The last thing I remembered, you can pull the balance from the database directly. It is clear that there may be data lagging a bit (race condition).
https://github.com/bavix/laravel-wallet/blob/c4e5d697b7e359857f6f1f1d78a20b178ceca06f/src/Models/Wallet.php#L122

**Comment by ibrunotome** [comment]
@rez1dent3 sometimes I'm getting exceptions with no messages, have you seem that before?

<img width="395" alt="Screen Shot 2022-08-28 at 09 57 23" src="https://user-images.githubusercontent.com/4256471/187075186-00d059fd-e1b3-41b5-a3e8-450939541f09.png">

<img width="903" alt="Screen Shot 2022-08-28 at 09 58 08" src="https://user-images.githubusercontent.com/4256471/187075216-5e3fcf02-3450-4036-83da-a65f72c601ca.png">

the code is a transaction with 1 to 3 possible transactions, ex:

```php

app(DatabaseServiceInterface::class)->transaction(function () use ($workContract) {
    $this->transaction($workContract); // transaction that always occurs
    $this->distributeAffiliateEarnings($workContract); // transaction that conditionally occurs
    $this->distributeBonus($workContract);  // transaction that conditionally occurs
});

```

**Comment by rez1dent3** [comment]
@ibrunotome 
I put the error in $previous, you can get it from there.
At first glance, this is some kind of error in the framework or your code. I ran through the code and I see that all of my exceptions have a message.

Example:
```php
try {
    app(DatabaseServiceInterface::class)->transaction(function () use ($workContract) {
        $this->transaction($workContract); // transaction that always occurs
        $this->distributeAffiliateEarnings($workContract); // transaction that conditionally occurs
        $this->distributeBonus($workContract);  // transaction that conditionally occurs
    });
} catch (\Throwable $t) {
    dd($throwable->getPrevious());
}
```

**Comment by ibrunotome** [comment]
It was a LockTimeoutException, who doesn't has messages. (so even with ->getPrevious() there wasn't messages)

<img width="655" alt="Screen Shot 2022-08-28 at 12 16 58" src="https://user-images.githubusercontent.com/4256471/187081359-b97ea288-f486-4ca0-b606-613d774b7666.png">


I switched the lock driver to database, by now these are my settings:

<img width="256" alt="Screen Shot 2022-08-28 at 12 18 48" src="https://user-images.githubusercontent.com/4256471/187081447-c62c6147-a975-4d55-841e-548c064c66d2.png">


Facing issues in production that I can't simulate in local or testing environment, maybe because i'm using redis in  https://cloud.google.com/memorystore, and, in all other environments a simple `redis:7.0.2-alpine` container in the same network.

**Comment by rez1dent3** [comment]
There are two options here:
1. Somewhere in the transaction you block and wait (until you get a lock timeout);
2. Somewhere in parallel, methods are twitching with the preservation of atomicity and blocking the transaction, so the current one cannot be executed;

here you need to profile.
