### ISSUE TITLE
support request for newbie

### ISSUE THREAD

**Issue by robertgarrigos** [bavix/laravel-wallet#56]
Sorry to ask you what is provably a newbie question, but I'm trying just the basic usage with no luck. My doubt is where should I use this?:

```
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Interfaces\Wallet;

class User extends Model implements Wallet
{
    use HasWallet;
}
```
Of course, laravel already has a User class which extends the Model class. Should I modify that class in Illuminate\Foundation\Auth ?? I don't think so. But then? Sorry, I'm lost. Thanks for your help.

**Comment by rez1dent3** [comment]
@robertgarrigos This example. You just need to add the interface and trait to any model.
```php
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Bavix\Wallet\Traits\HasWallet;
use Bavix\Wallet\Interfaces\Wallet;

class User extends Authenticatable implements Wallet
{
    use Notifiable;
    use HasWallet;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

**Comment by rez1dent3** [comment]
@robertgarrigos that is, you use the standard laravel model.

**Comment by robertgarrigos** [comment]
ok. thanks. I'll do that.
