### ISSUE TITLE
Error after create

### ISSUE THREAD

**Issue by kak2z7702** [bavix/laravel-wallet#57]
Hi)) I do this:
1.
```
    public function index(User $user)
    {
        if(is_null($user->getWallet('refill'))){
            $user->createWallet([
                'name' => ucfirst('refill') . 'Wallet',
                'slug' => 'refill',
            ]);
        }
        //$user->fresh();
        //$user->wallet->fresh();

        dd($user->getWallet('refill'));
    }

```

2. i have error
```
Illuminate \ Database \ QueryException (23000)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'App\Models\User-2-refill' for key 'wallets_holder_type_holder_id_slug_unique' (SQL: insert into `wallets` (`name`, `slug`, `holder_id`, `holder_type`, `updated_at`, `created_at`) values (RefillWallet, refill, 2, App\Models\User, 2019-07-05 19:05:32, 2019-07-05 19:05:32))
```

3. refresh page 
```
Wallet {#638 ▼
  #fillable: array:6 [▶]
  #casts: array:1 [▶]
  #connection: "mysql"
  #table: "wallets"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:9 [▶]
  #original: array:9 [▶]
  #changes: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #hidden: []
  #visible: []
  #guarded: array:1 [▶]
}
```

What am I doing wrong? Thank.

**Comment by kak2z7702** [comment]
```
    public function createWallet(array $data): WalletModel
    {
        /**
         * Create a default wallet
         */
        $this->getBalanceAttribute();

        /**
         * @var WalletModel $wallet
         */
        $wallet = $this->wallets()->create($data);
        $this->_wallets[$wallet->slug] = $wallet;

        return $wallet;
    }
```
my wallet has a default name "refill"
If I create this wallet, then it is created twice. need to check the existence of the wallet in this method.

**Comment by kak2z7702** [comment]
this work better

```
    /**
     * @param array $data
     * @return WalletModel
     */
    public function createWallet(array $data): WalletModel
    {

        /**
         * @var WalletModel $wallet
         */
        $wallet = $this->wallets()->create($data);
        $this->_wallets[$wallet->slug] = $wallet;

        /**
         * Create a default wallet
         */
        $this->getBalanceAttribute();
        
        return $wallet;
    }
```

**Comment by rez1dent3** [comment]
@kak2z7702 Alexey, Thank you! This morning I will fix it.

---
Алексей, спасибо. Сегодня утром сделаю фикс данного бага.

**Comment by rez1dent3** [comment]
@kak2z7702 fixed. thank. tag 3.0.3

**Comment by rez1dent3** [comment]
I will close issue, if I can help you with anything else-create a new one or open it

**Comment by ucanbehack** [comment]
it is a bug if you want custom default wallet

**Comment by rez1dent3** [comment]
@ucanbehack I did not understand your problem. More?

**Comment by Ecoent** [comment]
Hi there,
got few questions:
1) does the wallet work with fiat currencies and cryptos?
2) can this work with Stripe (for ecommerce), Paypal?
3) Any test / demo links?
4) Can admin control KYC for the users?

**Comment by rez1dent3** [comment]
@Ecoent This is a library for creating virtual wallets. Everything can be implemented, but the developer is already doing it on his side.

**Comment by Ecoent** [comment]
@rez1dent3 thank you very much! would love to use this as early as possible for ecommerce apps. If you can share links or any more information, that will be awesome! 

so the code thats published, is this usable now for real life app testing?

**Comment by rez1dent3** [comment]
@Ecoent I use the library in production, but I can’t decide for you.If you have more questions, then create an issue. This issue is about another issue that most likely is no longer there.

**Comment by ucanbehack** [comment]
> @ucanbehack I did not understand your problem. More?

/**
     * @param array $data
     * @return WalletModel
     */
    public function createWallet(array $data): WalletModel
    {

        /**
         * @var WalletModel $wallet
         */
        $wallet = $this->wallets()->create($data);
        $this->_wallets[$wallet->slug] = $wallet;

        /**
         * Create a default wallet
         */
        $this->getBalanceAttribute();
        
        return $wallet;
    }



in this case if we want to set custom default wallet name so have to return from above after creating new wallet

**Comment by rez1dent3** [comment]
@ucanbehack All right. The default wallet will be created automatically. This is the expected behavior of the system.

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.
