### ISSUE TITLE
Model::preventSilentlyDiscardingAttributes throws error for missing [created_at, updated_at] in fillable

### ISSUE THREAD

**Issue by itsrafsanjani** [bavix/laravel-wallet#572]
**Describe the bug**
Laravel 9.28 **added Eloquent mode to prevent silently discarding fills for attributes not in $fillable ([#43893](https://github.com/laravel/framework/pull/43893))**

**To Reproduce**
1. Go to `AppServiceProvider`'s `boot` method
2. Add 
```php 
Model::preventSilentlyDiscardingAttributes(! app()->isProduction());
``` 
3. Try to `deposit`

**Trace Error**
```{"type":"error","message":"Transaction failed. Message: Add fillable property [created_at, updated_at] to allow mass assignment on [Bavix\\Wallet\\Models\\Transaction]."}```

**Expected behavior**
`created_at` and `updated_at` should not throw error like this

**Server:**
 - php version: 8.1
 - database: mysql 5.7
 - wallet version 9.3
 - cache lock: file
 - cache wallets: file

**Comment by rez1dent3** [comment]
@itsrafsanjani Hello. Thank you. I'll have to add this to my tests.

**Comment by rez1dent3** [comment]
@itsrafsanjani tag 9.4.0
