### ISSUE TITLE
Return value of Bavix\Wallet\Services\WalletService::getWallet() must be an instance of Bavix\Wallet\Models\Wallet, int returne

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#58]
$user = User::find(1);
        print_r($user);
        $s =   $user->balance;

**Comment by khanhnam99** [comment]
use laravel 5.6
 in WalletModel is must be an instance of
public function getWallet(Wallet $object): WalletModel
    {
        if ($object instanceof WalletModel) {
            return $object;
        }

        /**
         * @var HasWallet $object
         */
        return $object->wallet;
    }

and  this is run to right

public function getWallet(Wallet $object)
    {
        if ($object instanceof WalletModel) {
            return $object;
        }

        /**
         * @var HasWallet $object
         */
        return $object->wallet;
    }

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61606116-f4833700-ac72-11e9-8b4e-c4a3adfe8589.PNG)

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61606155-1a104080-ac73-11e9-9ddb-a491ec79d0e9.PNG)

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61606214-55127400-ac73-11e9-8d28-3de74078d820.PNG)

**Comment by khanhnam99** [comment]
pls help me

**Comment by rez1dent3** [comment]
@khanhnam99 Not reproduced.
I need the users table structure and the php version, db, os.

**Comment by rez1dent3** [comment]
@khanhnam99 I think you have a column in the user table called wallet with an int type.
Only in this case I manage to reproduce the error, but this error is not on my side and I cannot solve it.

![Screenshot from 2019-07-22 09-09-25](https://user-images.githubusercontent.com/5111255/61609987-76b63000-ac60-11e9-9110-3c9cb16a3d62.png)

![Screenshot from 2019-07-22 09-10-10](https://user-images.githubusercontent.com/5111255/61610023-8a619680-ac60-11e9-9ae1-4dbf96861c91.png)

**Comment by khanhnam99** [comment]
table : users (id,wallet) , wallets(id,holder_type,holder_id,name,slug,description,balance),
transactions(payable_type,payable_id,wallet_id,type,amount,confirmed,meta,uuid)
transfers(from_type,from_id,to_type,to_id,status,status_last,deposit_id,withdraw_id,fee,uuid)

use php version 7.3, laravel 5.6, Server version: 10.3.15-MariaDB Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61613755-5e5c0a80-ac8c-11e9-9df2-f35303708fd5.PNG)

**Comment by khanhnam99** [comment]
use
![Capture](https://user-images.githubusercontent.com/575720/61613815-7c296f80-ac8c-11e9-8d7c-fec08b3540b0.PNG)

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61613866-995e3e00-ac8c-11e9-9da3-bf40666dce50.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 problem in the users table. Remove the wallet column!

**Comment by khanhnam99** [comment]
thanks, that's right, i made it

**Comment by khanhnam99** [comment]
thanks, I did it

**Comment by rez1dent3** [comment]
@khanhnam99 That's good, I'll have more questions - create or reopen an issue

**Comment by matinwd** [comment]
same here to but in my case i do not have any column named wallet in users table.

![2020-10-23_15-38-07](https://user-images.githubusercontent.com/52950867/97001807-dbd49180-1545-11eb-91da-7aab4d5183cb.png)

**Comment by matinwd** [comment]
```
$user = User::find($id);
        dd($user->balance);
```

**Comment by matinwd** [comment]
Argument 1 passed to Bavix\Wallet\Services\WalletService::getWallet() must be an instance of Bavix\Wallet\Interfaces\Wallet, instance of App\Models\User given, called in C:\xampp\htdocs\hyper\vendor\bavix\laravel-wallet\src\Simple\Store.php on line 21

**Comment by matinwd** [comment]
and user model

```
class User extends Authenticatable
{
    use HasApiTokens, Notifiable;
    use HasRoles;
    use HasWallet;
```

**Comment by rez1dent3** [comment]
@matinwd You forgot to add an interface:
```php
use Bavix\Wallet\Interfaces\Wallet;
class User extends Authenticatable implements Wallet
```

**Comment by rez1dent3** [comment]
No more questions. I am closing the issue. There will be questions - reopen or create a new one.

**Comment by rez1dent3** [comment]
@delasoftcode hello. If you have problem, please create a new issue and I can help you.
The issue should contain details of php, laravel and laravel-wallet.
