### ISSUE TITLE
fee on transfers

### ISSUE THREAD

**Issue by kooroshkdt2** [bavix/laravel-wallet#584]
Hi 
i was playing this package , this is just an idea 

what if we can define transfer fee , like PayPal to send money to other people 

like if you want send 100$ to another person , 100$ plus  2% or constant number ,  user payes  102$ and target wallet receives 100$

**Comment by rez1dent3** [comment]
Hello. You need to create a separate wallet for commissions.
It is not particularly important for which model it will be (it can be a service department or an admin user).
Example:
```php
$feeWallet = $serviceModel->createWallet(['name' => 'fee']);
```

laravel-wallet <9.5. [AtomicService](https://bavix.github.io/laravel-wallet/#/atomic-service) & [Transfer](https://bavix.github.io/laravel-wallet/#/wallet-transfer)
```php
use Bavix\Wallet\Services\AtomicServiceInterface;

app(AtomicServiceInterface::class)->block([$wallet1], function () use ($wallet1, $wallet2, $amount, $feeWallet) {
    $wallet1->transfer($feeWallet, $amount*0.02);
    $wallet1->transfer($wallet2, $amount);
});
```

OR 

```php
use Bavix\Wallet\Services\AtomicServiceInterface;
use Bavix\Wallet\Services\ConsistencyServiceInterface;

app(AtomicServiceInterface::class)->block([$wallet1], function () use ($wallet1, $wallet2, $amount, $feeWallet) {
    app(ConsistencyServiceInterface::class)->checkPotential($wallet1, $amount*1.02);
    
    $wallet1->forceTransfer($feeWallet, $amount*0.02);
    $wallet1->forceTransfer($wallet2, $amount);
});
```

If you have version 9.5 and above, then it is better to use the high-performance api handle. It generates fewer requests to the database and cache. [AtomicService](https://bavix.github.io/laravel-wallet/#/atomic-service) & [API. Batch Transfers](https://bavix.github.io/laravel-wallet/#/batch-transfers?id=api-batch-transfers)
```php
use Bavix\Wallet\External\Api\TransferQuery;
use Bavix\Wallet\External\Api\TransferQueryHandlerInterface;
use Bavix\Wallet\Services\AtomicServiceInterface;
use Bavix\Wallet\Services\ConsistencyServiceInterface;

app(AtomicServiceInterface::class)->block([$wallet1], function () use ($wallet1, $wallet2, $amount, $feeWallet) {
    app(ConsistencyServiceInterface::class)->checkPotential($wallet1, $amount*1.02);
     
    app(TransactionQueryHandlerInterface::class)->apply([
        new TransferQuery($wallet1, $feeWallet, $amount*0.02, null),
        new TransferQuery($wallet1 $wallet2, $amount, null),
    ]);
});
```
