### ISSUE TITLE
Hello, I would like an automatic wallet to be created but setting a variable currency in the meta, depending on the user's country, for example, if when registering the user chooses Colombia, the currency would be COP and so, how could I do it? since when using createWallet it works fine for me but then another wallet is created by default and I only need 1;

### ISSUE THREAD

**Issue by MaironU** [bavix/laravel-wallet#592]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rez1dent3** [comment]
Hello. It will definitely not work dynamically, because this is the config. The only thing you can do is set the config (though not sure if it will work with laravel octane).

```php
config(['wallet.wallet.default.currency' => 'USD']);
```
