### ISSUE TITLE
canWithdraw function allowZero

### ISSUE THREAD

**Issue by Algeneralo** [bavix/laravel-wallet#598]
**Describe the bug**
I'm having an issue with the `canWithdraw` function that allow zero even if the $allowZero parameter is false
if the user has 10 in the balance, and I tried `$user->canWithdraw(10,false)`, it return true

**Expected behavior**
Return false instead of true

**Screenshots**

**Server:**
 - php version: 8.1
 - database: mysql
 - wallet version 7.3.4

**Comment by rez1dent3** [comment]
Hello, @Algeneralo. $allowZero only allows $amount to be passed equal to zero. It does not affect the balance check. This parameter appeared when there was a need for the payFree method.

The method works correctly and is covered by tests: https://github.com/bavix/laravel-wallet/blob/fb2eb07d8a9c6dfecf0ad12f62d7cf2b79c9c71b/tests/Units/Domain/BalanceTest.php#L85-L91

**Comment by Algeneralo** [comment]
@rez1dent3 Thanks for explaining this, I misunderstood it.
Is there any way to deny the withdrawal for any amount that will make the balance equal to 0?

**Comment by rez1dent3** [comment]
> Is there any way to deny the withdrawal for any amount that will make the balance equal to 0?

If I understood you correctly, then this check is enough for you:
```php
$wallet->balanceInt > $amount
```
