### ISSUE TITLE
Balance is not being updated

### ISSUE THREAD

**Issue by Algeneralo** [bavix/laravel-wallet#599]
**Describe the bug**
The transaction is created, but the balance is not changed, I think that it's related to #429 

**To Reproduce**
```
try {
    DB::beginTransaction();
    \App\Models\User::find(22802)->withdraw(500);
    DB::commit();
} catch (\Throwable $th) {
    DB::rollback();
}
```

**Server:**
 - php version: 8.1
 - database: mysql 
 - wallet version 7.3.4
 - cache lock:  DynamoDB
 - cache wallets: array (default)

**Comment by rez1dent3** [comment]
@Algeneralo Hello. The ability to use standard transactions appeared only in version 9.6 (not long ago).

The instruction is relevant for you:
https://bavix.github.io/laravel-wallet/#/transaction?id=if-you-are-using-a-version-below-96-then-the-following-is-relevant-for-you

**Comment by rez1dent3** [comment]
More details for version 7.x can be found here:
https://github.com/bavix/laravel-wallet/pull/412

**Comment by Algeneralo** [comment]
Thanks!
