### ISSUE TITLE
how check negative numbers ?

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#60]
how check negative numbers
$user = User::first(); 
$user->balance; // int(10)
$user->withdraw(11); 

how  balance > withdraw
{
  $user->withdraw(11); 
   echo 'Yes withdraw'
}else
{
  echo 'No withdraw'
}

balance - 11 =  - 1 (negative)
 notification not enough balance

**Comment by rez1dent3** [comment]
@khanhnam99 
https://github.com/bavix/laravel-wallet/blob/3.0.4/src/Traits/HasWallet.php#L147

If you need validation, then
```php
if ($buyer->canWithdraw($amount)) {
    echo 'Yeah!';
}
```

If you need to go to the [minus](https://bavix.github.io/laravel-wallet/#/withdraw), then
```php
$buyer->forceWithdraw(10);
```

**Comment by rez1dent3** [comment]
once there are no more questions, then I close the issue

**Comment by khanhnam99** [comment]
thanks
