### ISSUE TITLE
how get all from table transactions type='deposit' reference table wallets

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#61]
wallets(id,holder_id)
transactions(wallet_id,type)

ex: holder_id = 1 how get all recorder from transactions type='deposit' OR type='withdraw' ? 

pls help me!

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61681451-b1d76280-ad37-11e9-8abc-b5a376cdd43f.PNG)

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61681486-cd426d80-ad37-11e9-9a44-f2410061340e.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 If I understand you correctly, then so
```php
var_dump($user->transactions); // all
var_dump($user->transactions()); // query builder
```

**Comment by rez1dent3** [comment]
If you want a more complex connection, just add it to the user model.

```php
    /**
     * @return HasManyThrough
     */
    public function allTransactions(): HasManyThrough
    {
        return $this->hasManyThrough(
            Transaction::class,
            Wallet::class,
            'holder_id'
        );
    }
```

**Comment by khanhnam99** [comment]
$user = User::first();
        $s = $user->transactions(['type'=>'withdraw']);
        print_r($s);
        exit;


![Capture](https://user-images.githubusercontent.com/575720/61690070-ad6c7300-ad52-11e9-993d-315dea1e4c6d.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 
```php
$user->transactions()
    ->where('type', Transaction::TYPE_WITHDRAW)
    ->get()
```

**Comment by khanhnam99** [comment]
thanks

**Comment by khanhnam99** [comment]
thanks , i did it
