### ISSUE TITLE
problem with eager loading with selected columns

### ISSUE THREAD

**Issue by Shahryar1991** [bavix/laravel-wallet#613]
Hi
I've tried to select some columns but it show me this error:
`Transaction failed. Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'App\Models\User-1-default' for key 'wallets_holder_type_holder_id_slug_unique' (SQL: insert into 'wallets' ('balance', 'decimal_places', 'uuid', 'holder_id', 'holder_type', 'name', 'slug', 'meta', 'updated_at', 'created_at') values (0, 2, be8d82f1-3255-41fa-9d80-771c024abc95, 1, App\Models\User, Default Wallet, default, [], 2022-12-06 00:51:15, 2022-12-06 00:51:15))`

a short version of my code is this:
`User::with('wallet', fn($query) => $query->select(['name', 'balance']))->all()`

without selecting columns (Ex. `User::with('wallet')->all()`), it'll give me sensitive information about user wallet that i don't want to pass it to the user as API calls. Ofcourse we can use json resource or similar ways to manipulate results but still unnecessary information will be extracted from the database.

I've found similar issue [here](https://github.com/bavix/laravel-wallet/issues/438) but it's appear that the problem came back to 9.6 version.

**Comment by rez1dent3** [comment]
Here is the minimum you need:
```php
            'wallet' => fn ($query) => $query->select(['name', 'balance', 'holder_type', 'holder_id', 'slug', 'uuid']),
```

But even with this minimum, there may be problems if you decide to deposit/withdraw funds from balance.

**Comment by Shahryar1991** [comment]
Thanks, that will do the job. With that query I just want to get account balance and show it to user.

**Comment by rez1dent3** [comment]
If I were you, I would make a pure sql query to the database, without eloquent. It will be faster in case performance is important to you.
