### ISSUE TITLE
Argument 1 passed to App\Models\User\User::transfer() must implement interface Bavix\Wallet\Interfaces\Wallet, int given, called in

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#62]
in controller

 public function address(Request $request)
    {
        $first = User::first();
        $second = 1;
        $first->transfer($second, 5);
        exit;
}

![Capture](https://user-images.githubusercontent.com/575720/61680769-0200f580-ad35-11e9-8b35-cbd611a194e1.PNG)

**Comment by rez1dent3** [comment]
![Screenshot from 2019-07-23 08-37-30](https://user-images.githubusercontent.com/5111255/61685356-27860300-ad25-11e9-9e8d-b9604dc902d9.png)

https://bavix.github.io/laravel-wallet/#/transfer

**Comment by khanhnam99** [comment]
thanks
