### ISSUE TITLE
how insert slug, name in table wallets

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#63]
ex: slug have a name 'coin' , or 'bit'

how insert slug, name in table wallets
$user = User::first();

**Comment by rez1dent3** [comment]
@khanhnam99 
https://bavix.github.io/laravel-wallet/#/new-wallet?id=create-a-wallet

**Comment by khanhnam99** [comment]
in my controller 


  $user = User::first();
        $wallet = $user->createWallet([
            'name' => 'New Wallet',
            'slug' => 'my-wallet',
        ]);
        $wallet->deposit(100);

        exit;

![Capture](https://user-images.githubusercontent.com/575720/61705533-1e6e5380-ad70-11e9-97e6-a65acaaf6a19.PNG)

**Comment by khanhnam99** [comment]
$user = User::first();
        $wallet = $user->createWallet([
            'name' => 'New Wallet',
            'slug' => 'my-wallet',
            'holder_type' => 'App\Models\User\User',
        ]);
        $wallet->deposit(100);

        exit;



![Capture](https://user-images.githubusercontent.com/575720/61706367-23340700-ad72-11e9-8ac4-f45dd419febc.PNG)

**Comment by rez1dent3** [comment]
Can not reproduce.  I'll try tomorrow.

the code is fine, this problem should not be
https://github.com/bavix/laravel-wallet/blob/master/src/Models/Wallet.php#L34

**Comment by rez1dent3** [comment]
@khanhnam99 I can not reproduce. I need your code: models, controller, etc.
https://github.com/bavix/laravel-wallet/blob/master/tests/MultiWalletTest.php#L303

**Comment by khanhnam99** [comment]
thanks

**Comment by rez1dent3** [comment]
#51

**Comment by rez1dent3** [comment]
@khanhnam99 I studied the code carefully and kind of found a possible problem. I fixed it in version 3.1 and wrote unit tests.
Release 3.1 will be released within an hour.

**Comment by rez1dent3** [comment]
@khanhnam99 Version 3.1 has been released. Please check this error.

**Comment by Kuraj11101** [comment]
How do I assign a new empty wallet to every newly registered users and manually allow deposit from a credit and sending to another user manually?
