### ISSUE TITLE
how insert from table transfers , have column fee = 10

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#64]
how insert from table transfers , have column fee = 10?

**Comment by rez1dent3** [comment]
Give me more data.  Nothing is clear.

**Comment by khanhnam99** [comment]
$first = User::first();
$last = User::orderBy('id', 'desc')->first(); // last user
$first->getKey() !== $last->getKey(); // true

$first->transfer($last, 5);
$first->balance; // int(95)
$last->balance; // int(5)     


how add fee = 10 in  $first->transfer($last, 5)

**Comment by khanhnam99** [comment]
how use function fee()
![Capture](https://user-images.githubusercontent.com/575720/61760656-75b70700-adf6-11e9-86ad-d713ebc7f8cb.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 Taxes, commissions, I did not describe in the documentation. But you can learn an example from unit tests.
https://github.com/bavix/laravel-wallet/blob/master/tests/TaxTest.php

**Comment by rez1dent3** [comment]
The tax consists of a percentage and there is no minimum payment. That is, to set a commission of 10 will not work.

**Comment by khanhnam99** [comment]
thanks

**Comment by rez1dent3** [comment]
@khanhnam99 in the next version I will add the ability to fix the minimum fee.

the interface will be like this:
https://github.com/bavix/laravel-wallet/blob/3.1/src/Interfaces/MinimalTaxable.php#L10

Here is an example of working from a unit test.
https://github.com/bavix/laravel-wallet/blob/3.1/tests/MinTaxTest.php

PS, Version 3.1 is in development and is not stable. Do not use in production.
