### ISSUE TITLE
Balance state in Transaction

### ISSUE THREAD

**Issue by fikurimax** [bavix/laravel-wallet#647]
I wanna have a balance state in the transactions table. I've tried to use meta and it works for deposit and withdraw, but it doesn't work for transfer because the meta is applied to both subject and target which is incorrect for the subject.

What do you think if you add one column to hold the balance state in transactions table? or let me know if there are another alternatives. Thanks

**Comment by fikurimax** [comment]
Actually i can accomplish that by using deposit and withdraw, but maybe this last balance state would be a good idea to validate the transactions

**Comment by rez1dent3** [comment]
@fikurimax hello. The package is able to separate metadata into different transactions (deposit/withdraw).

```php
use Bavix\Wallet\External\Dto\Extra;
use Bavix\Wallet\Services\AtomicServiceInterface;

app(AtomicServiceInterface::class)->block($user, function () use ($user, $wallet) {
    $user->transfer($wallet, 1000, new Extra(
        deposit: ['balance' => $user->balance],
        withdraw: ['balance' => $wallet->balance],
    ));
});
```

If I understand your question correctly.

**Comment by rez1dent3** [comment]
I thought that both wallets should be blocked. So like this:
```php
use Bavix\Wallet\External\Dto\Extra;
use Bavix\Wallet\Services\AtomicServiceInterface;

app(AtomicServiceInterface::class)->blocks([$user, $wallet], function () use ($user, $wallet) {
    $user->transfer($wallet, 1000, new Extra(
        deposit: ['balance' => $wallet->balance],
        withdraw: ['balance' => $user->balance],
    ));
});
```

**Comment by fikurimax** [comment]
Yeah, that solves my problem. Thanks
