### ISSUE TITLE
Is there a way not to delete the wallet column from the users table

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#65]
table  users(wallet)

how not remove wallet column  in users table?

![Capture](https://user-images.githubusercontent.com/575720/61771025-e5d68480-ae18-11e9-8c67-130eeb5dde0c.PNG)

**Comment by khanhnam99** [comment]
pls help me!

**Comment by rez1dent3** [comment]
@khanhnam99 You can rename the column in users table.There is no other option.

**Comment by khanhnam99** [comment]
thanks
