### ISSUE TITLE
How to define relationship between Bavix Wallet's Model and other new model that I created ???

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#651]
Hello.

I want to define **_One To One_** relationships between `Business` model with I just created and `Bavix Wallet's` model. But I don't find this `Bavix Wallet's` in `App\Model` folder.
So, how to etablish relationship between Bavix Wallet's model and other model that I create ???

Help please.

**Comment by rez1dent3** [comment]
Hello.
> in App\Model folder.

There are no package models and will not be in App.

> So, how to etablish relationship between Bavix Wallet's model and other model that I create ???

Use correct namespace. 

https://github.com/bavix/laravel-wallet/blob/0c1f9115568cd24891e1ca60eea17faaa35b3d16/src/Models/Wallet.php#L5

**Comment by chegmarco1989** [comment]
All right. Thanks
