### ISSUE TITLE
Is there a way to create "One to One" Relationship with "Wallet" directly in "Businessinfo" intead of Models ?

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#653]
Hello.

I added into `businessinfos` migration, this: `$table->foreignId('wallet_id')->constrained('wallets')->cascadeOnUpdate()->cascadeOnDelete();` to create a new column `wallet_id` in `Businessinfo`.

So, I want to define **_One To One_** Relationship (between `Businessinfo` Database Table and Bavix's `Wallet` Table) directly in my `BusinessinfoController` using DB facade (Illuminate\Support\Facades\DB) and `leftJoin` or `join` but I don't know how to do it.

So, could you please help me to make relationship between `Businessinfo` Database Table and Bavix's `Wallet` Table directly in `BusinessinfoController` using DB facade ???

Please help.
Awaiting your reply.

**Comment by rez1dent3** [comment]
Hello. I don't understand your issue. If you need the one2one relation, then check out the framework documentation.
https://laravel.com/docs/10.x/eloquent-relationships#one-to-one
https://www.learn2torials.com/a/laravel-eloquent-one-to-one-relationship
