### ISSUE TITLE
Pay with Discount 

### ISSUE THREAD

**Issue by Mghobadid** [bavix/laravel-wallet#654]
how can pay  item (product) with coupon code?  is there any way to send discount value to _getAmountProduct_ method? 
can we pay by force?

**Comment by rez1dent3** [comment]
Hello, @Mghobadid. For the `Cart::withItem` method, you can set the cost per piece.

https://github.com/bavix/laravel-wallet/blob/150f248cb8cc3b28551d6125f7b60e02475ceaf2/tests/Units/Domain/ProductTest.php#L281-L288
