### ISSUE TITLE
How to define transaction's "fee" with Laravel Bavix Wallet ???

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#655]
Hello.

How to define transaction's "fee" with Laravel Bavix Wallet ??? We tried to search it without found it on the documentation page: https://bavix.github.io/laravel-wallet/#/.
**_So, how to determine transaction's `fee` when making deposits and withdrawals with Laravel Bavix Wallet ???_**

**Comment by rez1dent3** [comment]
Hello. Use the interface:
```php
use Bavix\Wallet\Interfaces\Taxable;
```

https://bavix.github.io/laravel-wallet/#/taxing?id=item-model
