### ISSUE TITLE
Laravel Nova - Wallet recreation after updating user info from dashboard

### ISSUE THREAD

**Issue by myounis97** [bavix/laravel-wallet#658]
**Describe the bug**
Whenever i click save on User Resource in Nova dashboard i receive an error message says duplicate entry for wallets table

**To Reproduce**
1. Open nova user's resource
2. Click on edit
3. Click save

**Screenshots**
![bug](https://user-images.githubusercontent.com/43533983/224510761-aebfecc3-b109-44ae-8f79-520b287fb5af.jpg)

**Server:**
 - php version: 8.1
 - database:  mysql
 - wallet version 9.6.1
 - cache lock: redis
 - cache wallets: redis

**Comment by rez1dent3** [comment]
Hello. I'll take a look during the week.

**Comment by myounis97** [comment]
@rez1dent3 thanks

**Comment by AutobookNft** [comment]
Hi, I've downloaded the package and I'm taking my first steps.

the first question that comes to your mind is how the wallet connects to my dApp. When the user lands on my marketplace, he must register his wallet before anything else by clicking on my "Connect wallet" button.
but in the scripts I didn't find the connection procedure.
Can you help me?
Thanks in advance.

**Comment by rez1dent3** [comment]
@myounis97 Hello. Long awaited release. v10.0.0

**Comment by myounis97** [comment]
@rez1dent3 thanks for your efforts 🎉🎊
