### ISSUE TITLE
WalletCreatedEvent not working

### ISSUE THREAD

**Issue by oasin** [bavix/laravel-wallet#659]
**Describe the bug**
WalletCreated events and other events do not work.

From Telescope these are the events fired

\Wallet\Internal\Events\BalanceUpdatedEvent_pushed | 1 | 1h ago |  
\Wallet\Internal\Events\BalanceUpdatedEvent | 1 | 1h ago |  
\Wallet\Internal\Events\TransactionCreatedEvent_pushed | 1 | 1h ago |  
\Wallet\Internal\Events\TransactionCreatedEvent | 0 | 1h ago

**Server:**
 - php version: [e.g. 8.1]
 - database: [e.g mysql 8.0]
 - wallet version [e.g. 8.2]
 - cache lock: [e.g. redis]
 - cache wallets: [e.g. redis]

**Comment by rez1dent3** [comment]
Hello.
1. Need details;
2. Events without listeners do not work;
3. Wallet version 8.x is not supported;

**Comment by rez1dent3** [comment]
I need examples. I can't help without them, my events are being sent.

**Comment by oasin** [comment]
i have Listeners created already.

```php
class WalletCreatedListener
{
    public function __construct()
    {
    }

    public function handle(WalletCreatedEventInterface $event): void
    {
    }
}
```

**Comment by oasin** [comment]
The WalletCreatedEvent does not work.

I have this registered in my event service provider

```php
 WalletCreatedEventInterface::class => [
            WalletCreatedListener::class,
        ],
```

**Comment by rez1dent3** [comment]
@oasin Yes, there is indeed a bug. I did not notice him, because. in our project, the creation of a wallet occurs in a transaction with logging. Thank you

**Comment by rez1dent3** [comment]
It works now. Tag 9.6.2

<img width="1281" alt="Снимок экрана 2023-03-15 в 20 38 59" src="https://user-images.githubusercontent.com/5111255/225396065-799084a4-d1b7-41bc-b8eb-df764ef4da63.png">
