### ISSUE TITLE
Inconsitent Value

### ISSUE THREAD

**Issue by oasin** [bavix/laravel-wallet#660]
I download the swap package

tried to exchange from wallet 1 to wallet 2

the exchange rate between wallet 1 to wallet 2 is in decimal value.

After the exchange is done, decimal values ( 0.004636) are inserted to the transfer and transaction table while wallet 2 balance will remain 0.0000

From your example try.

private array $rates = [
        'USD' => [
            'BTC' => '0.000045',
        ],
    ];

**Comment by rez1dent3** [comment]
Hello. Can not understand anything. What "decimal_places" value do you have for these wallets? Need details.

**Comment by rez1dent3** [comment]
Thanks for the example. I'll look at it on the weekend. There's too much work right now

**Comment by rez1dent3** [comment]
@oasin jfyi

**Comment by oasin** [comment]
I wrote a new Trait CanExchangeFloat 


so I did this
```php

//Get exchange rate 
        $rate = app(ExchangeServiceInterface::class)->convertTo(
                $castService->getWallet($this)->getCurrencyAttribute(),
                $castService->getWallet($to)->currency,
                1
            );


            //change value to decimal float
            $decimalPlacesValue = app(CastServiceInterface::class)->getWallet($this)->decimal_places;
            $decimalPlaces = $mathService->powTen($decimalPlacesValue);
            $rate = $mathService->round($mathService->mul($rate, $decimalPlaces, $decimalPlacesValue));
```

**Comment by rez1dent3** [comment]
@oasin There is a mantissa problem in numerical methods. But I don't see any problems with the exchange method. I provided an example.

**Comment by oasin** [comment]
Hello @rez1dent3, did you also try the above trait? from the Test you added there is a 10000000000 value, this is unusual :(

**Comment by oasin** [comment]
Thanks for the explanation. this is correct
