### ISSUE TITLE
how check a deposit or withdraw to finish in table transactions? 

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#68]
$user = User::first();
$user->balance; // int(0)
$user->deposit(10) // how check a deposit to finish ? 

i think there is a column status in table transactions
how check a deposit or withdraw to finish in table transactions?

**Comment by rez1dent3** [comment]
php is not multi-threaded. This check does not make sense.

If successful, the deposit and withdraw methods return the Bavix\Wallet\Models\Transaction model.
![Screenshot from 2019-07-25 08-40-47](https://user-images.githubusercontent.com/5111255/61848787-effb9000-aeb7-11e9-9c8e-e3385f7963e0.png)

**Comment by khanhnam99** [comment]
![Capture](https://user-images.githubusercontent.com/575720/61849339-272f6880-aedb-11e9-89d6-11bc0c3ab78b.PNG)


how insert in transactions , confirmed = false or confirmed = 0

**Comment by rez1dent3** [comment]
$wallet->deposit(1, null, false)
$wallet->withdraw(1, null, false)

**Comment by khanhnam99** [comment]
thanks, i did it
