### ISSUE TITLE
1062 Duplicate entry 'App\Models\User-13009-default' for key 'wallets.wallets_holder_type_holder_id_slug_unique'

### ISSUE THREAD

**Issue by WebPajooh** [bavix/laravel-wallet#682]
**Describe your task**
Hi.
My question is about this error is happening (seen in Sentry):
```
Transaction failed.
Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'App\Models\User-13009-default' for key 'wallets.wallets_holder_type_holder_id_slug_unique' (SQL: insert into `wallets` (`balance`, `decimal_places`, `uuid`, `holder_id`, `holder_type`, `name`, `slug`, `meta`, `updated_at`, `created_at`) values (0, 2, xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx, 13009, App\Models\User, Default Wallet, default, [], 2023-04-12 15:49:18, 2023-04-12 15:49:18))
```

Why does it happen?
Thank you for your help.

**Server:**
 - php version: 8.1
 - database: MySQL 8.0.32
 - wallet version 8.4.1
 - cache lock: -
 - cache wallets: -

**Comment by rez1dent3** [comment]
Hello. 
> Why does it happen?

You need to set up a lock service. 

You receive two requests to create a wallet. At the first request, the wallet is created, and for the second you get an error. You can read about the race condition.

**Comment by rez1dent3** [comment]
https://github.com/bavix/laravel-wallet/blob/3a66b2c730b256f06843cb9e5089cbc6c824b72d/config/config.php#L63-L69

**Comment by WebPajooh** [comment]
Thanks for your answer. @rez1dent3 
The problem is that I'm not creating anything.

This is the line that error was caught:
```php
'balance' => $this->user->balanceFloat,
```

If the wallet doesn't exist, this is one request and if it does exist, why should it be created again? 🤔

**Comment by rez1dent3** [comment]
The wallet is currently created automatically when the balance is displayed. If two requests come to you in this method at the same time, but the first one will be executed and create a wallet, and the second one will give an error (race condition). What I wrote about above.

PS,
Version 10.x will not be automatic, but it will not be released soon (around 2023 Q3).

**Comment by onemoreahmad** [comment]
Sorry to reopen this issue, but I have the exact same issue. 

when I do `$user->deposit(10);` it automatically create a wallet if not exists. and when I run the command again even after few minutes, I got the duplication error. It seems it **always** try to create a wallet without checking if it exists already or not.
