### ISSUE TITLE
Connection to the wallet

### ISSUE THREAD

**Issue by AutobookNft** [bavix/laravel-wallet#684]
**Describe your task**
A clear and concise description of your task.

I am creating a marketplace with Laravel/Livewire using Algorand as blockchain.
I downloaded Laravel Wallet package and installed it, did the configurations and migrations.
But I don't understand how to make the connection to the Wallet.
The user must link his Wallet to my Marketplace. I can't find the procedure to make the connection.
How is this accomplished?
Thanks in advance.

**Comment by rez1dent3** [comment]
Hello. This is a VIRTUAL wallet. Connection and configuration is the concern of the developer. Those, you decide how it should work and with what.

**Comment by AutobookNft** [comment]
Ah, ok.
Thank you so much.
