### ISSUE TITLE
how test in  https://github.com/bavix/laravel-wallet/tree/master/tests

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#69]
https://github.com/bavix/laravel-wallet/tree/master/tests

example
 in php 7.3 how test this file

https://github.com/bavix/laravel-wallet/blob/master/tests/WalletTest.php

**Comment by rez1dent3** [comment]
https://phpunit.readthedocs.io/en/8.2/textui.html

example:
```bash
./vendor/bin/phpunit --filter WalletTest
```

**Comment by khanhnam99** [comment]
Thanks , what's your name ? everyone call me Stephen, from Vietnam

my site use nodejs , reactjs

https://nhidong1.medpro.com.vn/
https://umc.medpro.com.vn/

**Comment by rez1dent3** [comment]
@khanhnam99 My name is Maxim, from Russia. 
Good projects.
