### ISSUE TITLE
problem orderBy('id', 'desc')

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#70]
this is run
$user = User::find(1);
$data= $user->transactions()->where(['type'=>Transaction::TYPE_DEPOSIT])->paginate(15);
exit;
-----------------------------------------------------
this error
$user = User::find(1);
$data= $user->transactions()->where(['type'=>Transaction::TYPE_DEPOSIT])->paginate(15)->orderBy('id', 'desc');

orderBy('id', 'desc')

![Capture](https://user-images.githubusercontent.com/575720/61933362-e8b7ad80-afaf-11e9-9731-8902de33c360.PNG)

**Comment by rez1dent3** [comment]
collections have no orderBy.
https://laravel.com/docs/5.8/collections#method-sortby

you need database level sorting. 

Do so: $user->transactions()->where(['type'=>Transaction::TYPE_DEPOSIT])->orderBy('id', 'desc')->paginate(15);

PS, read the framework documentation
