### ISSUE TITLE
create 2 wallet for user with same holder id

### ISSUE THREAD

**Issue by munaZd** [bavix/laravel-wallet#702]
describe when i create user with wallet it duplicate but the duplicated one name as default wallet 
**Trace Error**
Full error trace...
**Server:**
 - php version: [e.g. 8.1]
 - database: [e.g mysql 8.0]
 - wallet version [e.g. 8.2]
-laravel 9

**Comment by rez1dent3** [comment]
Hello. You can create an unlimited number of wallets for a user, there are no restrictions on this. There is only one standard wallet, this is guaranteed with a unique index: https://github.com/bavix/laravel-wallet/blob/37189bd579d85a66acaf116a2677d95857e44c37/database/2018_11_15_124230_create_wallets_table.php#L38

Wallet versions <9.x are not supported.
