### ISSUE TITLE
Support IDR Currency?🤔

### ISSUE THREAD

**Issue by dzaki236** [bavix/laravel-wallet#713]
It is has a idr currency support?, or just dollar(US)?, i want use this, but in my case,i want to use IDR(rupiah currency), it is has been there before yet?

I'd like to this library, it can be used for IDR(Rupiah) currency, or someelse..

Maybe, it has been available before, but i don't know and see?

for additional, thanks for your work, i like it, maybe i'll use this on my case 💖

**Comment by rez1dent3** [comment]
Hello. The library is not tied to a specific currency. You implement all the business logic yourself. You can sell both real currency and virtual.

Here is a simple example:
```php
$idr = $user->createWallet([
    'name' => 'rupiah currency',
    'meta' => ['currency' => 'IDR'],
]);

$idr->currency; // IDR
$idr->deposit(100); // Top up with one rupee
$idr->balanceFloatNum; // 1.00
$idr->balanceInt; // 100
```

If you need a currency exchange, then you can look towards https://github.com/bavix/laravel-wallet-swap

Docs: https://bavix.github.io/laravel-wallet/#/laravel-wallet-swap

`swap` is a wrapper around the `florianv/laravel-swap` library. And there are a lot of providers in this library, there are even crypto exchanges.

**Comment by dzaki236** [comment]
Alright i understands, thanks, great work!🔥
