### ISSUE TITLE
Little Clarrification

### ISSUE THREAD

**Issue by oasin** [bavix/laravel-wallet#716]
I am doing a workaround on the library, I am having some difficulties understanding the below lines

 >>> app(RegulatorServiceInterface::class)->sync($this, $balance);

This is found in the `refreshBalance` method of the Wallet class, I looked up the called method in the regulator service the below code is found in the `sync` method

        $this->persist($wallet);
        return $this->storageService->sync(
            $wallet->uuid,
            $this->mathService->round(
                $this->mathService->negative($this->mathService->sub($this->amount($wallet), $value))
            )
        );

I believe this synchronizes the Transactions Table and update the wallet. 

I am trying to replicate this by synchronizing another table and updating the wallet table but it seems not to work.

I would appreciate your time for some clarification, thanks.

**Comment by rez1dent3** [comment]
Hello. Start by reading articles on inner workings: https://github.com/bavix/laravel-wallet/pull/412 https://github.com/bavix/laravel-wallet/discussions/562 https://github.com/bavix/laravel-wallet/pull/589

The Regulator only works with the array cache, while the Bookkeeper works with the cache state. Those changes from the Regulator are applied at the end of the transaction.
https://github.com/bavix/laravel-wallet/blob/2260214f055fcf2608eb5690177c1be6cb46b81f/src/WalletServiceProvider.php#L300-L310
