### ISSUE TITLE
how add negative in deposit(-10)?

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#72]
how add negative ? 
$user = User::first();
$user->deposit(-10);

**Comment by rez1dent3** [comment]
@khanhnam99 Deposit - no way. There is a withdraw operation.
No one forbids adding your method to the model.

```php
public function myDeposit($amount)
{
    if ($amount > 0) {
         return $this->deposit($amount);
    }
    return $this->withdraw($amount);
}
```

**Comment by rez1dent3** [comment]
@khanhnam99 Please check it out.
https://github.com/bavix/laravel-wallet/issues/63#issuecomment-515675134

**Comment by khanhnam99** [comment]
thanks
