### ISSUE TITLE
Wallet balance not changing on deposit

### ISSUE THREAD

**Issue by rrutwik** [bavix/laravel-wallet#729]
### Discussed in https://github.com/bavix/laravel-wallet/discussions/728

<div type='discussions-op-text'>

<sup>Originally posted by **rrutwik** July 18, 2023</sup>
I am using 
$this->deposit($amount, $meta);
to deposit amount in a user wallet.
In logs, i see balance changing.. but it does not change in database.
Transaction is updated fine, in database</div>

**Comment by rez1dent3** [comment]
Hello. Attach an example. And also, which version of the wallet, php and db you use.

**Comment by rrutwik** [comment]
PHP 8.1.2
Wallet 7.3.5
DB MySQL 8.0
Example is i am depositing amount lets say 80. It is adding to transaction but not updating in wallet. Though logs before and after this function shows balance in updated. But it is not updated in DB.

**Comment by rez1dent3** [comment]
Does the update happen in a transaction?

If yes, then you will have to replace laravel transactions with package transactions: https://bavix.github.io/laravel-wallet/#/transaction?id=if-you-are-using-a-version-below-96-then-the-following-is-relevant-for-you

If you do not want or cannot use package transactions, then you need to upgrade your wallet to version 9.6+, because. for the wallet, changes were made to the framework itself: https://github.com/laravel/framework/pull/44608

**Comment by rrutwik** [comment]
It works find with ->forceWithdraw.. not sure why..

**Comment by rez1dent3** [comment]
I won't tell you either. Both methods should not work correctly on your version.

https://github.com/bavix/laravel-wallet/blob/f9fa790c98bec2ab765ea6e7a7c4c9dd55e1284d/src/Traits/HasWallet.php#L52-L59

https://github.com/bavix/laravel-wallet/blob/f9fa790c98bec2ab765ea6e7a7c4c9dd55e1284d/src/Traits/HasWallet.php#L214-L221


Well, yes, if you need transactions - upgrade the package to 9.6+

**Comment by rrutwik** [comment]
yes, i checked that but deposit is not committing changes.

**Comment by rez1dent3** [comment]
As I wrote above, you have two choices:
- https://bavix.github.io/laravel-wallet/#/transaction?id=if-you-are-using-a-version-below-96-then-the-following-is-relevant-for-you
- up wallet 7.x to 9.6+

**Comment by rrutwik** [comment]
I followed first point, still same transaction is added but wallet is not updated.
public function depositPayment($amount, $meta = []) {   
        $driver = $this;
        $this->getConnection()->transaction(static function () use ($driver, $amount, $meta) {
            $payer = $driver;
            $payer->deposit($amount, $meta);
        });
    }

**Comment by rez1dent3** [comment]
@rrutwik what are your wallet settings (wallet.php)?

**Comment by rrutwik** [comment]
`<?php

declare(strict_types=1);

use Bavix\Wallet\Internal\Assembler\AvailabilityDtoAssembler;
use Bavix\Wallet\Internal\Assembler\BalanceUpdatedEventAssembler;
use Bavix\Wallet\Internal\Assembler\TransactionDtoAssembler;
use Bavix\Wallet\Internal\Assembler\TransactionQueryAssembler;
use Bavix\Wallet\Internal\Assembler\TransferDtoAssembler;
use Bavix\Wallet\Internal\Assembler\TransferLazyDtoAssembler;
use Bavix\Wallet\Internal\Assembler\TransferQueryAssembler;
use Bavix\Wallet\Internal\Events\BalanceUpdatedEvent;
use Bavix\Wallet\Internal\Events\WalletCreatedEvent;
use Bavix\Wallet\Internal\Repository\TransactionRepository;
use Bavix\Wallet\Internal\Repository\TransferRepository;
use Bavix\Wallet\Internal\Repository\WalletRepository;
use Bavix\Wallet\Internal\Service\ClockService;
use Bavix\Wallet\Internal\Service\DatabaseService;
use Bavix\Wallet\Internal\Service\DispatcherService;
use Bavix\Wallet\Internal\Service\JsonService;
use Bavix\Wallet\Internal\Service\LockService;
use Bavix\Wallet\Internal\Service\MathService;
use Bavix\Wallet\Internal\Service\StorageService;
use Bavix\Wallet\Internal\Service\TranslatorService;
use Bavix\Wallet\Internal\Service\UuidFactoryService;
use Bavix\Wallet\Internal\Transform\TransactionDtoTransformer;
use Bavix\Wallet\Internal\Transform\TransferDtoTransformer;
use Bavix\Wallet\Models\Transaction;
use Bavix\Wallet\Models\Transfer;
use Bavix\Wallet\Models\Wallet;
use Bavix\Wallet\Services\AssistantService;
use Bavix\Wallet\Services\AtmService;
use Bavix\Wallet\Services\AtomicService;
use Bavix\Wallet\Services\BasketService;
use Bavix\Wallet\Services\BookkeeperService;
use Bavix\Wallet\Services\CastService;
use Bavix\Wallet\Services\ConsistencyService;
use Bavix\Wallet\Services\DiscountService;
use Bavix\Wallet\Services\ExchangeService;
use Bavix\Wallet\Services\PrepareService;
use Bavix\Wallet\Services\PurchaseService;
use Bavix\Wallet\Services\RegulatorService;
use Bavix\Wallet\Services\TaxService;
use Bavix\Wallet\Services\WalletService;

return [
    /**
     * Arbitrary Precision Calculator.
     *
     *  'scale' - length of the mantissa
     */
    'math' => ['scale' => 64],

    /**
     * Storage of the state of the balance of wallets.
     */
    'cache' => ['driver' => 'array'],

    /**
     * A system for dealing with race conditions.
     */
    'lock' => [
        'driver' => 'array',
        'seconds' => 1,
    ],

    /**
     * Internal services that can be overloaded.
     */
    'internal' => [
        'clock' => ClockService::class,
        'database' => DatabaseService::class,
        'dispatcher' => DispatcherService::class,
        'json' => JsonService::class,
        'lock' => LockService::class,
        'math' => MathService::class,
        'storage' => StorageService::class,
        'translator' => TranslatorService::class,
        'uuid' => UuidFactoryService::class,
    ],

    /**
     * Services that can be overloaded.
     */
    'services' => [
        'assistant' => AssistantService::class,
        'atm' => AtmService::class,
        'atomic' => AtomicService::class,
        'basket' => BasketService::class,
        'bookkeeper' => BookkeeperService::class,
        'regulator' => RegulatorService::class,
        'cast' => CastService::class,
        'consistency' => ConsistencyService::class,
        'discount' => DiscountService::class,
        'exchange' => ExchangeService::class,
        'prepare' => PrepareService::class,
        'purchase' => PurchaseService::class,
        'tax' => TaxService::class,
        'wallet' => WalletService::class,
    ],

    /**
     * Repositories for fetching data from the database.
     */
    'repositories' => [
        'transaction' => TransactionRepository::class,
        'transfer' => TransferRepository::class,
        'wallet' => WalletRepository::class,
    ],

    /**
     * Objects of transformer from DTO to array.
     */
    'transformers' => [
        'transaction' => TransactionDtoTransformer::class,
        'transfer' => TransferDtoTransformer::class,
    ],

    /**
     * Builder class, needed to create DTO.
     */
    'assemblers' => [
        'availability' => AvailabilityDtoAssembler::class,
        'balance_updated_event' => BalanceUpdatedEventAssembler::class,
        'transaction' => TransactionDtoAssembler::class,
        'transfer_lazy' => TransferLazyDtoAssembler::class,
        'transfer' => TransferDtoAssembler::class,
        'transaction_query' => TransactionQueryAssembler::class,
        'transfer_query' => TransferQueryAssembler::class,
    ],

    /**
     * Package system events.
     */
    'events' => [
        'balance_updated' => BalanceUpdatedEvent::class,
        'wallet_created' => WalletCreatedEvent::class,
    ],

    /**
     * Base model 'transaction'.
     */
    'transaction' => [
        'table' => 'transactions',
        'model' => Transaction::class,
    ],

    /**
     * Base model 'transfer'.
     */
    'transfer' => [
        'table' => 'transfers',
        'model' => Transfer::class,
    ],

    /**
     * Base model 'wallet'.
     */
    'wallet' => [
        'table' => 'wallets',
        'model' => Wallet::class,
        'creating' => [],
        'default' => [
            'name' => 'Default Wallet',
            'slug' => 'default',
            'meta' => [],
        ],
    ],
];
`

**Comment by rez1dent3** [comment]
I suspect that you have db transaction level > 0 inside the controller. You can do:
```php
dd(DB::transactionLevel());
```

If the value before the start of the transaction is greater than zero, then this is the problem.

Without an example, I can't help. I do not reproduce.

**Comment by rrutwik** [comment]
local: INFO: db level 1 , not sure about this value. What does it do ?

**Comment by rez1dent3** [comment]
This value indicates that you already have a transaction running. Therefore, it doesn't work. If you do DB::rollBack() before the call, then everything will work.

And here is where your transaction starts - I will not tell you.

**Comment by rez1dent3** [comment]
If the code
```
dd(DB::transactionLevel());
```
starts to return =0, then everything will start working correctly.

**Comment by rrutwik** [comment]
hmm kool

**Comment by rez1dent3** [comment]
If you cannot find where the transaction starts, then you will only have to update the package version. Starting from version 9.6, the package listens for events from Laravel DB. When the transaction closes, the changes will be applied.

**Comment by rrutwik** [comment]
kool
