### ISSUE TITLE
refund ? 

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#73]
$user = User::first();
$user->balance; // int(100)

$user->withdraw(1);
$user->balance; // int(99)

how refund 1 for user User ?

**Comment by rez1dent3** [comment]
@khanhnam99 You can not cancel the operation. The only option is to affix confirmed = false and recalculate the user's balance.

https://bavix.github.io/laravel-wallet/#/refresh

```php
$wallet->refreshBalance();
```

**Comment by rez1dent3** [comment]
The refund operation works only with purchases.
https://bavix.github.io/laravel-wallet/#/refund

**Comment by rez1dent3** [comment]
I close issue, there will be questions create new
