### ISSUE TITLE
Attach Dto to Product payment

### ISSUE THREAD

**Issue by Joemires** [bavix/laravel-wallet#734]
My application works by generating a custom reference number for transactions
How can I achieve this using the Product pay trait 
I want to be able to add an Extra Dto data to properly describe my transactions (withdraw & deposit)

**Comment by rez1dent3** [comment]
Hello. If I understand you correctly, then you need method `withMeta` in Cart.

https://github.com/bavix/laravel-wallet/blob/78357a719d457028e08d8dd046bb7b1ee4728462/src/Objects/Cart.php#L51
