### ISSUE TITLE
Suspended wallet balance

### ISSUE THREAD

**Issue by Abdallah9Saeed** [bavix/laravel-wallet#757]
If I have orders and their value has been deducted from the wallet, I want to hold part of the amount as a security balance, and when the order is completed, I will return the security balance to the purchasing user’s wallet.

**Comment by rez1dent3** [comment]
Hello. This is no longer the responsibility of the package, but of your business logic. You will have to implement this logic in your application. Conventionally, you have some kind of message broker and the "order is completed" event appeared there and you subscribe to this event and replenish the user's balance by the required percentage of the order amount.
