### ISSUE TITLE
2 project with api

### ISSUE THREAD

**Issue by TinoSic** [bavix/laravel-wallet#758]
Hi, 
I have a problem with get balance because responde 0, the wallet is installated up 2 projects with one DB. But if create a wallet with Project 1 and set balance to 100, in the project 2 the wallet not visible and function for get balance responded 0 amount, but if access with to project1 the balance it's correct with 100

**Comment by rez1dent3** [comment]
Hello. Let's start from the very beginning, namely with the configuration. What are you using?
Versions: wallet, php, db, cache, lock, etc...

**Comment by TinoSic** [comment]
Two project write in php up Laravel and api with sanctum middleware

**Comment by rez1dent3** [comment]
Need configuration (wallet.php) and versions (wallet, php, db, cache, lock, etc...). Without information, I can't help you.
