### ISSUE TITLE
Bavix\Wallet\Internal\Exceptions\TransactionFailedException Transaction failed

### ISSUE THREAD

**Issue by mr-krunal** [bavix/laravel-wallet#791]
**Transaction Failed**
I have installed the package and followed the step, I have already transactions table in my database so I changed the wallet.php and set table to wallet_transactions migration also run properly.

when I tried to add deposit its giving error
![error](https://github.com/bavix/laravel-wallet/assets/4983855/5567edce-f557-46f4-aed0-64542142ed2d)

**To Reproduce**

**Trace Error**
Full error trace... If there is

**Expected behavior**

**Screenshots**

**Server:**
 - php version: [ 8.2.11 ]
 - database: [Ver 15.1 Distrib 10.4.28-MariaDB, for osx10.10 (x86_64)]
 - wallet version [^7.3]
 - cache lock: [e.g. redis]
 - cache wallets: [e.g. redis]

**Additional context**

**Comment by rez1dent3** [comment]
Hello. I need the code, then I can tell you.

**Comment by mr-krunal** [comment]
Ok,

Please find the code snippets for the same, 

My system tables are Lead, transactions primary keys are UUID and the package name i changed to wallet_transactions from wallet.php

![image](https://github.com/bavix/laravel-wallet/assets/4983855/f573d8cc-55a6-4cd2-a7d3-aaa6b3488c1c)

![image](https://github.com/bavix/laravel-wallet/assets/4983855/5d629905-7466-4ce7-9334-1936b58a1546)

![image](https://github.com/bavix/laravel-wallet/assets/4983855/a5075a9a-ee8e-48c8-bfb8-dd8cb85a2d50)

**Comment by rez1dent3** [comment]
Ah, got it. You need to upgrade to laravel-wallet 9+. uuid support appeared in the ninth version of the package.

Also, you need to install the package https://github.com/bavix/laravel-wallet-uuid and perform the migration.

**Comment by mr-krunal** [comment]
ok, but my laravel version is 8.12 and when I try to install package ^9.0

it says

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].
    - Root composer.json requires soarecostin/file-vault ^1.2 -> satisfiable by soarecostin/file-vault[v1.2.0].
    - Conclusion: don't install bavix/laravel-wallet 9.6.2 (conflict analysis result)
    - bavix/laravel-wallet[9.0.0-alpha, ..., 9.6.0] require illuminate/contracts ^9.0 -> satisfiable by illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev].
    - Conclusion: don't install illuminate/contracts v9.52.16 (conflict analysis result)
    - Root composer.json requires bavix/laravel-wallet ^9.0 -> satisfiable by bavix/laravel-wallet[9.0.0-alpha, ..., 9.6.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by rez1dent3** [comment]
You need to update laravel and all packages, that's right. I don't support older versions of laravel.

**Comment by rez1dent3** [comment]
Or use int for the primary key in your models, but it seems to me easier to update laravel and use uuid in models, if there is such a need.
