### ISSUE TITLE
Package not working with laravel 10.30.1

### ISSUE THREAD

**Issue by yungfarz** [bavix/laravel-wallet#800]
This package failed to work with my laravel version,  unable to fetch balance?? Why please??

**Comment by rez1dent3** [comment]
Hello.
I checked and found no problems. All tests pass. We need details.

Maybe you forgot to apply all migrations?

Example:
https://github.com/bavix/laravel-wallet/actions/runs/6744025947/job/18333036245#step:7:1

**Comment by rez1dent3** [comment]
@yungfarz Hello. I can't help without your help.

**Comment by yungfarz** [comment]
yea i had a typo thanks

**Comment by yungfarz** [comment]
> @yungfarz Hello. I can't help without your help.

fixed it was a typo thanks
