### ISSUE TITLE
Error During Bavix Wallet Migration: Index Conflict in MongoDB

### ISSUE THREAD

**Issue by paulorlima9** [bavix/laravel-wallet#804]
# Describe your task
Encountering an issue during the migration process with Bavix Wallet using MongoDB. The error indicates that an index already exists with a different name: `payable_type_1_payable_id_1`. 

# To Reproduce
1. Run the migration process.
2. Encounter the error related to the existing index.

# Trace Error
```php
MongoDB\Driver\Exception\CommandException 

Index already exists with a different name: payable_type_1_payable_id_1

at vendor/mongodb/mongodb/src/Operation/CreateIndexes.php:198
    194▕                 $cmd[$option] = $this->options[$option];
    195▕             }
    196▕         }
    197▕ 
  ➜ 198▕         $server->executeWriteCommand($this->databaseName, new Command($cmd), $this->createOptions());
    199▕     }
    200▕ }
    201▕ 

      +6 vendor frames 

  7   database/migrations/2018_11_06_222923_create_transactions_table.php:28
      MongoDB\Laravel\Schema\Blueprint::index([], "payable_type_payable_id_ind")
      +2 vendor frames 

  10  database/migrations/2018_11_06_222923_create_transactions_table.php:13
      Illuminate\Support\Facades\Facade::__callStatic("create")
```

# Expected behavior

# Screenshots
Not applicable.

# Server
- PHP version: [e.g., 8.2]
- Database: [e.g., MongoDB]
- Wallet version: [e.g., 10.0]
- Cache lock: [e.g., Redis]
- Cache wallets: [e.g., Redis]

# Additional context
Using MongoDB as the database for the project, attempting to integrate Bavix Wallet.

**Comment by rez1dent3** [comment]
Hello. MongoDB is not supported.

**Comment by paulorlima9** [comment]
Hello, thank you for the feedback. Is there any way to adapt it so that it works?

**Comment by rez1dent3** [comment]
I think there is, but I didn’t have such a task.  

You can look for a solution among the forks. Unfortunately, I can’t tell you whether there are real results.

**Comment by paulorlima9** [comment]
Alright, I appreciate your efforts in responding to me. I'll need to search and see if I can find any alternatives.
