### ISSUE TITLE
package not installed with laravel 10.37

### ISSUE THREAD

**Issue by bdj-Razik** [bavix/laravel-wallet#816]
Problem 1
    - Root composer.json requires bavix/laravel-wallet ^10.0 -> satisfiable by bavix/laravel-wallet[10.0.0, 10.0.1, 10.0.2].
    - nesbot/carbon 2.72.1 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.1.0].
    - carbonphp/carbon-doctrine-types 3.1.0 conflicts with doctrine/dbal 3.7.2.
    - laravel/framework v10.37.3 requires nesbot/carbon ^2.67 -> satisfiable by nesbot/carbon[2.72.1].
    - bavix/laravel-wallet[10.0.0, ..., 10.0.2] require doctrine/dbal ^3.5 -> satisfiable by doctrine/dbal[3.5.0, ..., 3.7.2].
    - laravel/framework is locked to version v10.37.3 and an update of this package was not requested.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bavix/laravel-wallet:*" to figure out if any version is installable, or "composer require bavix/laravel-wallet:^2.1" if you know which you need

**Comment by rez1dent3** [comment]
Hello. 

Everything works fine.

Job: https://github.com/bavix/laravel-wallet/actions/runs/7200506864/job/19614622581
```sh
  - Locking laravel/framework (v10.37.2)
```

You have a conflict due to the carbonphp library. Update it.

```sh
- carbonphp/carbon-doctrine-types 3.1.0 conflicts with doctrine/dbal 3.7.2.
```

**Comment by rez1dent3** [comment]
According to this post:
```sh
You can also try re-running composer require with an explicit version constraint, e.g. "composer require bavix/laravel-wallet:*" to figure out if any version is installable, or "composer require bavix/laravel-wallet:^2.1" if you know which you need
```

It will be very difficult for you to upgrade.

Docs: https://bavix.github.io/laravel-wallet/#/upgrade-guide

It seems to me that it would be faster and easier to raise new tables nearby and write a command to migrate old data to a new structure. But that's what I would do.

**Comment by bdj-Razik** [comment]
Thank you for your answer
A problem has been solved
By installing carbon php/carbon-doctrine-types:^2.1.0 then with install doctrine/dbal matching him

**Comment by rez1dent3** [comment]
You're welcome!
