### ISSUE TITLE
I want to transfer fractional value 

### ISSUE THREAD

**Issue by ritesh8192** [bavix/laravel-wallet#818]
I can send it but it's doesn't store and as well calculation of the wallet amount is wrong. can you help me?

**Comment by rez1dent3** [comment]
Hello. You can do this using the *Float methods.

https://github.com/bavix/laravel-wallet/blob/eb3862dc737e50be52a42d8d00fe202004154b8d/src/Traits/HasWalletFloat.php#L103-L107

**Comment by ritesh8192** [comment]
can you give me example please?

**Comment by rez1dent3** [comment]
```php
$wallet->transferFloat($to, 100.11);
```
