### ISSUE TITLE
Need this for Multi-Tenancy (Teams)

### ISSUE THREAD

**Issue by zenepay** [bavix/laravel-wallet#819]
When implementing with Teams, a user may belong to many teams, a wallet should belong to a team.
Then the wallet table may have team_id as a forieng key. The model Wallet then should BelongsTo a team.

I am trying to inject the team_id value when calling deposit() by lisening to event Wallet creating() in the boot(), unfortunately, deposit() does not dispatch the event creating to wallet. I cannot set team_id before the transaction creating a new wallet.

Please advise, or have this Team feature for new version.

**Comment by zenepay** [comment]
Currently work around by creating wallet before calling deposit().
```
        $user = User::find(1)->first();
        if(!$wallet = $user->getWallet($user->current_team_id.'-my-wallet')){
            $wallet = $user->createWallet([
                'name' => 'Team Wallet',
                'slug' => $user->current_team_id.'-my-wallet',
                'team_id' =>$user->current_team_id
            ]);
        }
        $wallet->deposit(10);
```
And in the config file config/wallet.php, I set default with team_id, so it won't cause error if wallet was not initially created before use. 
```
    /**
     * Base model 'wallet'.
     */
    'wallet' => [
        'table' => 'wallets',
        'model' => Wallet::class,
        'creating' => [],
        'default' => [
            'name' => 'Default Wallet',
            'slug' => '1-default',
            'team_id'=> 1,
            'meta' => [],
        ],
    ],
```
I hope there is a better way to hook it in the future version.

**Comment by rez1dent3** [comment]
Hello. I didn't use this functionality, there was no need. I'll think about a solution in my free time

**Comment by rez1dent3** [comment]
@zenepay 
UPD. 

I was thinking, then why do you need to link a wallet to a specific user? Link wallets to your team. Then you will have code something like this:

```php
use Bavix\Wallet\Traits\HasWallets;
use Bavix\Wallet\Interfaces\Wallet;

class Team extends \Laravel\Jetstream\Team implements Wallet
{
    use HasWallets;
}
```

Then:
```php
$user-> currentTeam->createWallet(...);
$user-> currentTeam-> hasWallet('my-wallet');
```

**Comment by zenepay** [comment]
There is no problem if creating wallet manually using createWallet(), since we can assign team_id with some way. But if using default wallet by just call $user->deposit(10) where the wallet was not initially created, it will fail since it requires team_id to save to database table wallets. 

So, I wonder that how I could listen to event creating of the wallet when calling via deposit().
I try static::creating(fn($model)) … it won’t work. It seem does not dispatch this event.

I cannot modify wallets.team_id before it saving to db.

**Comment by zenepay** [comment]
> Hello. I didn't use this functionality, there was no need. I'll think about a solution in my free time

Thank you. Please,:) it will be high benefit for SaaS projects.

**Comment by rez1dent3** [comment]
@zenepay 

> But if using default wallet by just call $user->deposit(10) where the wallet was not initially created, it will fail since it requires team_id to save to database table wallets.

The default wallet is only needed in very simple projects. In your case, you need to use multi-wallets.

> So, I wonder that how I could listen to event creating of the wallet when calling via deposit().
> I try static::creating(fn($model)) … it won’t work. It seem does not dispatch this event.
> I cannot modify wallets.team_id before it saving to db.

The package has its own events. 
https://bavix.github.io/laravel-wallet/#/wallet-created-event

> it will be high benefit for SaaS projects.

You can follow the example from unit tests and add additional fields through meta data and save them in separate fields.

Although the example is for transactions, it is also perfect for wallets:
https://github.com/bavix/laravel-wallet/blob/eb3862dc737e50be52a42d8d00fe202004154b8d/tests/Units/Domain/WalletExtensionTest.php#L23-L33

**Comment by rez1dent3** [comment]
@zenepay starting from tag 10.1.0 you can used method getDynamicDefaultSlug in model.

```
final class User extends Model implements Wallet
{
    use HasWallet;

    public function getDynamicDefaultSlug(): string
    {
        return $user->current_team_id.'-my-wallet';
    }
}
```

Release today, but later.
