### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by kak2z7702** [bavix/laravel-wallet#82]
Hi) i error race condition))
i have this code
```
        $walletRefill = $user->getWalletRefill();
        $walletHold = $user->getWalletHold();

        try {
            $walletRefill->transfer(
                $walletHold,
                $type,
                [
                    'description' => 'Перевод средств для покупки очереди: ' . $type . '$'
                ]);

        } catch (Exception $e) {
            
            info(__CLASS__ . '(' . __LINE__ . ') ' . $e->getMessage());
            return redirect(route('queue.buy.index', [
                'user' => $user->id
            ]))->with('error', __($e->getMessage()));

        }
```
when many users run this code, then I see such an error

```
App\Http\Controllers\Front\Queue\BuyController(69) SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: update `wallets` set `balance` = 3820, `wallets`.`updated_at` = 2019-08-05 00:18:53 where `id` = 12)
--
```
Do you have any idea how to fix this?)))
tnx)

**Comment by rez1dent3** [comment]
@kak2z7702 
I think you should get redis.
1. Write the key (wallet_id) in redis and set the lifetime to 1 second before the operation (to avoid competing requests)
2. Before the operation of transferring funds, check the key.
3. After a successful transfer operation - delete the key

--- rus
Я думаю стоит обзавестись redis. 
1. Пишите ключ (wallet_id) в redis и ставите срок жизни 1 сек перед операцией (для избежания конкурирующих запросов)
2. Перед операцией перевода средств, проверяем ключ.
3. После успешной операции перевода -- удаляем ключ

PS,
I advise in such requests to do a forced recalculation of wallets.
https://bavix.github.io/laravel-wallet/#/refresh

**Comment by rez1dent3** [comment]
Maybe in the future, I will make a separate module work with the state of the race.

**Comment by rez1dent3** [comment]
@kak2z7702 #83 https://github.com/bavix/laravel-wallet/tree/lock
I make a service to work with the race. I will test it and it is unlikely that this feature will be released.

At the moment, unit tests are passing. Simple setup
```php
// config/wallet.php
return [
   'lock' => [
       'enabled' => true, 
       'seconds' => 1,
   ]
   ...
]
```

--- rus
Я делаю сервис для работы с гонкой. Буду тестировать и не факт что фича попадёт в релиз.

**Comment by rez1dent3** [comment]
@kak2z7702 The code got to the master branch. I will collect the release next week.

--- rus
Код уже в мастер ветке. Буду собирать релиз уже на днях. Мои тесты код прошел.

**Comment by rez1dent3** [comment]
@kak2z7702 
Thanks you. Made a release tag v3.2.0.

You can enable the mode "race condition" in the configuration.
```php
    /**
     * Lock settings for highload projects
     */
    'lock' => [
        'enabled' => true,
        'seconds' => 1, // how much we wait
    ],
```

Please report the result. In my test environment this worked.
