### ISSUE TITLE
Wallet check sum and transactions block summary so transactions can be archived and validate

### ISSUE THREAD

**Issue by zenepay** [bavix/laravel-wallet#820]
Hi, I am just thinking of if Wallet value was changed in database, the transactions records will not be reflected to the sum amount to wallet correctly.  It would be good if there is some functionality to validate the value.

Think about bank statement transactions, the amount is always calculated from the sum amount of the transactions.  It won't be able to just changing the wallet balance.

Anyway, if balance will always sum from the transactions, it will be slow when transactions grow high. If there is block chain to keep monthly sum with hash for validate the values, it will be good one.

**Comment by rez1dent3** [comment]
Hello.

> Think about bank statement transactions, the amount is always calculated from the sum amount of the transactions. It won't be able to just changing the wallet balance.

The first versions of the wallet counted the amount of transactions in real time and it was very slow.

There is no way to implement blockchain without any problems; you need to check the hash sum of all transactions, not just the last one. This will slow down.

You have two ways: update the balance manually after changes in the database, replace the getBalanceAttribute implementation with getAvailableBalanceAttribute.

https://github.com/bavix/laravel-wallet/blob/78357a719d457028e08d8dd046bb7b1ee4728462/src/Models/Wallet.php#L117

https://github.com/bavix/laravel-wallet/blob/78357a719d457028e08d8dd046bb7b1ee4728462/src/Models/Wallet.php#L135

> Anyway, if balance will always sum from the transactions, it will be slow when transactions grow high. If there is block chain to keep monthly sum with hash for validate the values, it will be good one.

Most users don't need this. This functionality is easy to implement through a wallet extension; you can arrange it in a separate package, similar to my packages:

- [Swap](https://github.com/bavix/laravel-wallet-swap) - Addition to the laravel-wallet library for quick setting of exchange rates
- [uuid](https://github.com/bavix/laravel-wallet-uuid) - Addition to laravel-wallet to support model uuid keys
- [Warm Up](https://github.com/bavix/laravel-wallet-warmup) - Addition to the laravel-wallet library for refresh balance wallets

I'll add your implementation to the readme. If it is in great demand, I will add it to the main package. This is how laravel-wallet-vacuum ended up in the main package.
