### ISSUE TITLE
ULIDs Support. 

### ISSUE THREAD

**Issue by yondifon** [bavix/laravel-wallet#829]
**Describe the bug**
I am looking to install this package (Looks great by the way) with an existing application that uses ULIDs but I realized even though I could modify the migrations to match our system but the interfaces and contracts only support integer ids. 

I have a few questions:
- Are there are plans to support ULIDs and UUIDs in the near future??
- If you can't because of WorkLoad, Will you entertain an PR to support those? 

**Screenshots**
<img width="1121" alt="image" src="https://github.com/bavix/laravel-wallet/assets/35140079/bc92a5ce-5144-4131-896d-7aab5a5b4940">

**Server:**
 - Laravel - 10.x

**Comment by rez1dent3** [comment]
Hello. You need to install the extension and perform the migration.

https://github.com/bavix/laravel-wallet-uuid
