### ISSUE TITLE
amount in transaction bug on withdrawFloat

### ISSUE THREAD

**Issue by anthoz69** [bavix/laravel-wallet#85]
Hi, I found some bug of withdrawFloat

my code:
```php
public function withdraw($amount, ?array $desc = null, $confirmed = 0)
    {
        $user = User::find(Auth::id());
        if ($amount > 0) {
            return $user->withdrawFloat($amount, $desc, $confirmed);
        }

        return $user->balanceFloat;
    }

$this->withdraw(2556.72, [], true);
```

when I withdraw amount: 
2556.72 in db transaction amount is show -255671 // 2556.71 it sholud be 2556.72

Thank you. sorry for my english.

**Comment by rez1dent3** [comment]
@anthoz69 Thanks, I'll see in the evening.

![image](https://user-images.githubusercontent.com/5111255/62619243-f4e02b00-b91e-11e9-96ca-cbbcfa7ccc69.png)

**Comment by rez1dent3** [comment]
@anthoz69 now everything works, check it

**Comment by rez1dent3** [comment]
@anthoz69 https://github.com/bavix/laravel-wallet/blob/master/tests/WalletFloatTest.php#L210
And here’s the unit test

**Comment by rez1dent3** [comment]
I close the issue. There are questions open new.

**Comment by anthoz69** [comment]
@rez1dent3 thank you so much.
