### ISSUE TITLE
How can one perform a transfer of funds with a deduction of fees from the destination wallet in version 10.x?

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#855]
Hello **@rez1dent3**
I want to perform a transfer and deduct the fee from my destination wallet. I tested the sample codes from previous discussions but received the following error. Can you provide a new sample code?

**code:**
```
app(AtomicServiceInterface::class)->blocks([$sourceWallet, $targetWallet], function () use ($sourceWallet, $targetWallet, $args, $feeWallet) {
    app(ConsistencyServiceInterface::class)->checkPotential($sourceWallet, $args["amount"]*1.02);
    app(TransactionQueryHandlerInterface::class)->apply([
        new TransferQuery($sourceWallet, $feeWallet, $args["amount"]*0.02, null),
        new TransferQuery($sourceWallet, $targetWallet, $args["amount"], null)
    ]);
});
```

**Error**
`Transaction failed. Message: Bavix\Wallet\External\Api\TransactionQueryHandler::Bavix\Wallet\External\Api\{closure}(): Argument #1 ($query) must be of type Bavix\Wallet\External\Api\TransactionQuery, Bavix\Wallet\External\Api\TransferQuery given`

**Comment by rez1dent3** [comment]
Hello. If I understand correctly, then you need Transfer.

```diff
app(AtomicServiceInterface::class)->blocks([$sourceWallet, $targetWallet], function () use ($sourceWallet, $targetWallet, $args, $feeWallet) {
    app(ConsistencyServiceInterface::class)->checkPotential($sourceWallet, $args["amount"]*1.02);
-   app(TransactionQueryHandlerInterface::class)->apply([
+   app(TransferQueryHandlerInterface::class)->apply(
        new TransferQuery($sourceWallet, $feeWallet, $args["amount"]*0.02, null),
        new TransferQuery($sourceWallet, $targetWallet, $args["amount"], null)
    ]);
});
```

**Comment by hamedkhorasani** [comment]
My mistake, thank you for the code. It solved my problem. However, I would like to perform more operations during the transaction, for example, I want to add balance after the completion of the transaction to the transaction metadata. How should I do this?


I want a code similar to the one below but the code below gives an error.

```
app(TransferQueryHandlerInterface::class)->apply([
	function () use ($sourceWallet, $targetWallet) {
		$transaction = new TransferQuery($sourceWallet, $targetWallet, 1000, null);
		$transaction->balance = 2000;
		$transaction->save();
		return $transaction;
	}
	new TransferQuery($targetWallet,  $feeWallet, 5, null),
])
```

**Comment by rez1dent3** [comment]
I'll be at the laptop in 5-6 hours and I'll be able to tell you, but I don't understand what you want to do. You can describe your actions in text. Thanks.

**Comment by rez1dent3** [comment]
Unfortunately, there is no information from us yet. Let me give you an example:

```php
app(TransferQueryHandlerInterface::class)->apply([
    new TransferQuery($from, $to, 1000, new \Bavix\Wallet\External\Dto\Extra(
        deposit: new \Bavix\Wallet\External\Dto\Option(
            ['msg' => 'deposit meta info', 'feeId' => '58244a74-a732-4b67-967f-0bdf59711580'], // for example
        ),
        withdraw: new \Bavix\Wallet\External\Dto\Option(
            ['msg' => 'withdraw meta info', 'feeId' => '58244a74-a732-4b67-967f-0bdf59711580'],  // for example
        ),
        'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab', // for example. randomly generated transferId
    )),
    new TransferQuery($from,  $fee, 5, new \Bavix\Wallet\External\Dto\Extra(
        deposit: new \Bavix\Wallet\External\Dto\Option(
            ['msg' => 'fee', 'transferId' => 'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab'],  // for example
        ),
        withdraw: new \Bavix\Wallet\External\Dto\Option(
            ['msg' => 'fee', 'transferId' => 'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab'],  // for example
        ),
        '58244a74-a732-4b67-967f-0bdf59711580', // for example. randomly generated feeId
    )),
]);
```

**Comment by rez1dent3** [comment]
Since there are no more questions, I will close the issue.
There will be additional questions - it is better to create a new issue.

**Comment by hamedkhorasani** [comment]
Thank you @rez1dent3 , my problem is solved.

**Comment by hamedkhorasani** [comment]
When I use uuid in TransferQuery, it gives the following error:

`Cannot use a positional argument after a named argument`

**Comment by rez1dent3** [comment]
> When I use uuid in TransferQuery, it gives the following error:
> Cannot use a positional argument after a named argument

This is a syntax error in php. Could you please provide the code?

**Comment by hamedkhorasani** [comment]
The same code that you wrote above gives this error.

> Unfortunately, there is no information from us yet. Let me give you an example:
> 
> ```
> app(TransferQueryHandlerInterface::class)->apply([
>     new TransferQuery($from, $to, 1000, new \Bavix\Wallet\External\Dto\Extra(
>         deposit: new \Bavix\Wallet\External\Dto\Option(
>             ['msg' => 'deposit meta info', 'feeId' => '58244a74-a732-4b67-967f-0bdf59711580'], // for example
>         ),
>         withdraw: new \Bavix\Wallet\External\Dto\Option(
>             ['msg' => 'withdraw meta info', 'feeId' => '58244a74-a732-4b67-967f-0bdf59711580'],  // for example
>         ),
>         'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab', // for example. randomly generated transferId
>     )),
>     new TransferQuery($from,  $fee, 5, new \Bavix\Wallet\External\Dto\Extra(
>         deposit: new \Bavix\Wallet\External\Dto\Option(
>             ['msg' => 'fee', 'transferId' => 'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab'],  // for example
>         ),
>         withdraw: new \Bavix\Wallet\External\Dto\Option(
>             ['msg' => 'fee', 'transferId' => 'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab'],  // for example
>         ),
>         '58244a74-a732-4b67-967f-0bdf59711580', // for example. randomly generated feeId
>     )),
> ]);
> ```

The same code that gives this error

**Comment by rez1dent3** [comment]
@hamedkhorasani Oh, I made a mistake when I wrote you an answer on github. There is missing `uuid:`:
```diff
-        'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab', // for example. randomly generated transferId
+        uuid: 'b5ef3dfc-7640-499c-84e6-a4535cb6f7ab', // for example. randomly generated transferId
...
-        '58244a74-a732-4b67-967f-0bdf59711580', // for example. randomly generated feeId
+        uuid: '58244a74-a732-4b67-967f-0bdf59711580', // for example. randomly generated feeId
```
