### ISSUE TITLE
In the exchange, how do I convert currency with a dynamic exchange rate?

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#856]
Hello **@rez1dent3**
In the example written in the document, the ruble conversion rate is a fixed number, but I want this number to be received every time through the API request.

**Comment by rez1dent3** [comment]
Hello. The laravel-wallet-swap (https://bavix.github.io/laravel-wallet/#/laravel-wallet-swap) package is built around the package https://github.com/florianv/laravel-swap. You can get an api course, or you can get a static one. You can even write your provider.

**Comment by hamedkhorasani** [comment]
Thanks a lot

**Comment by hamedkhorasani** [comment]
Dear **@rez1dent3**
I have a wallet called Lira with 0 decimals
I have a dollar wallet with 2 decimal places
My dollar rate is 548030 lira
When exchanging 10000000 lira from lira to dollars, 18.25 dollars must be deposited
Actually, 1825 should be stored in the database, but exactly 18 are stored.
What is the problem?

**Comment by rez1dent3** [comment]
@hamedkhorasani Hello. 
```
I have a wallet called Lira with 0 decimals
I have a dollar wallet with 2 decimal places
```

This is due to the different number of decimal_places. This behavior has never been tested and there was no need for such functionality. And the task is not an easy one.
