### ISSUE TITLE
The decimal value is converted to an integer in the transfer

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#857]
Hello **@rez1dent3**
In the example below, I want to transfer $0.93, but it transfers $1.

```
$fee = app(TransferQueryHandlerInterface::class)->apply([
	new TransferQuery($targetWallet, $feeWallet, 0.93, new Extra(
		deposit: new Option(
			meta: [
				'name' => 'exchange_fee',
			],
			confirmed: true
		),
		withdraw: new Option(
			meta: [
				'name' => 'exchange_fee',
			],
			confirmed: true
		)
	))
]);
```

**Comment by sinamiandashti** [comment]
same issue !

**Comment by sinamiandashti** [comment]
ah  you should use HasWalletFloat trait hamed jan @hamedkhorasani

**Comment by hamedkhorasani** [comment]
**@sinamiandashti** It didn't work.

```
class User extends Authenticatable implements HasMedia, Wallet, WalletFloat
{
    use Notifiable,
        HasRoles,
        InteractsWithMedia,
        MetaTrait,
        HasHashId,
        SavesHashId,
        HasApiTokens,
        HasWalletFloat,
        HasWallets,
        CanConfirm;
}
```

**Comment by rez1dent3** [comment]
Hello. The architecture of laravel wallet is built around integers, which is surprising to many. You have decimal_places, which specifies the shift of decimal places.

For example, we have a wallet ($) and decimal_places=2. We deposit 123 into the account.
```
123 / 10^2 => $1,23
```

Those, you have 123 stored in your balance, but when displaying the float balance, additional calculations are performed.

High-performance APIs are low-level programming in laravel-wallet, they do not check anything and write directly to the database. You need to do this:
```php
$fee = app(TransferQueryHandlerInterface::class)->apply([
	new TransferQuery($targetWallet, $feeWallet, 93, new Extra(
		deposit: new Option(
			meta: [
				'name' => 'exchange_fee',
			],
			confirmed: true
		),
		withdraw: new Option(
			meta: [
				'name' => 'exchange_fee',
			],
			confirmed: true
		)
	))
]);
```

For example, `$targetWallet` has decimal_places=2 and by this we mean $.
```
93 // $0.93
123 // $1.23
100000 // $1000.00
123456789 // $1234567.89
```

That is, storage is carried out in the minimum currency. 
It's all about numerical methods and mantis. [Example](https://www.cl.cam.ac.uk/teaching/1314/NumMethods/nummeths13slides.pdf).

**Comment by hamedkhorasani** [comment]
Thanks a lot.

**Comment by hamedkhorasani** [comment]
Dear **@rez1dent3** 
I have a wallet called Lira with 0 decimals
I have a dollar wallet with 2 decimal places
My dollar rate is 548030 lira
When exchanging 10000000 lira from lira to dollars, 18.25 dollars must be deposited
Actually, 1825 should be stored in the database, but exactly 18 are stored.
What is the problem?

**Comment by rez1dent3** [comment]
@hamedkhorasani Hello. Version 11.x will add two more contracts to make your life easier.

```php
TransactionFloatQuery::createDeposit(...);
TransactionFloatQuery::createWithdraw(...);
new TransferFloatQuery(...);
```
