### ISSUE TITLE
What is the most reliable way to exchange and transfer at the same time?

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#863]
Dear **@rez1dent3** 
I want to do an exchange with a fee deducted from the deposit transaction. The conversion fee is 5%, which must be deducted from the transaction deposit.
I also need to record information such as the dollar rate.. I want all my operations to be done in an atomic wallet block. How can this be done?

**Comment by rez1dent3** [comment]
@hamedkhorasani Hello. Can I have an example code? 

In general, everything you wrap in AtomicService will be executed in one transaction. The wallet balance will be updated once.

**Comment by Peektower** [comment]
@rez1dent3 
Im trying to do wallet exchange have followed this steps from this link [Laravel Wallet Swap](https://bavix.github.io/laravel-wallet/#/laravel-wallet-swap) but it dosen't exchange the amount instead it just transfer the amount I entered. can you please help

Here is my code 
``public` function quickTransfers()
    {
        $sender = User::findOrFail(12);
        $receiver = User::findOrFail(11);

        $s = $sender->getWallet($sender->tag);
        $r = $receiver->getWallet($receiver->tag);

        $s->exchange($r, 10);

        return $r->balance;
    }`

**Comment by Peektower** [comment]
`"bavix/laravel-wallet-swap": "^6.0",`

**Comment by Peektower** [comment]
`"bavix/laravel-wallet-swap": "^6.0",`

**Comment by hamedkhorasani** [comment]
The problem was with my code. My problem is solved.
