### ISSUE TITLE
Can a new field be added to the transfer table?

### ISSUE THREAD

**Issue by hamedkhorasani** [bavix/laravel-wallet#864]
Hello `@rez1dent3 `
I have two types of transfers. One type of transfer is transfer to friends, which is called transfer. Another type is transfer to the company account, which has a different name, for example, payment.
In the dashboard, the history pages of these two types are different. I want this transfer whose name is Transfer to be displayed on the transfers page and payments on the payments page.
How to fetch only one type of transfer, for example, payment?

**Comment by rez1dent3** [comment]
Hello. I think we need to think about it. It might be worth adding meta, similar to transaction

**Comment by hamedkhorasani** [comment]
I think this is a necessary feature

**Comment by rez1dent3** [comment]
@hamedkhorasani Please look at the PR #865. In theory, this is enough. By analogy with transaction, you can add any number of columns.

**Comment by rez1dent3** [comment]
But, this change breaks backward compatibility. Therefore, it will go to version 11.x, which should be released soon. Version 11 will support laravel 11, so you will need to update.

**Comment by hamedkhorasani** [comment]
For now, using transection solves my problem. 
But it can be more attractive as an idea.
I very much appreciate your help.

**Comment by rez1dent3** [comment]
Okay. The feature will appear in 11.x
