### ISSUE TITLE
conflict with  laravel Cashier

### ISSUE THREAD

**Issue by imhuso** [bavix/laravel-wallet#87]
![image](https://user-images.githubusercontent.com/9276880/62681484-5e7a3b00-b9ec-11e9-9301-51237e30b2cc.png)
![image](https://user-images.githubusercontent.com/9276880/62682821-9e8eed00-b9ef-11e9-9d42-05b42952f540.png)

**Comment by rez1dent3** [comment]
@imhuso remove the `CanPayFloat`.

Upgrade:
```
$user->withdraw(...) to $user->wallet->withdraw(...)
$user->deposit(...) to $user->wallet->deposit(...)
$user->transfer(...) to $user->wallet->transfer(...)
...
```

**Comment by imhuso** [comment]
@rez1dent3 
i can't understand.

**Comment by rez1dent3** [comment]
@imhuso Do not use trait `CanPayFloat`. He creates this error. 
Where do you use shorthand syntax, use the full one.

Those if you use `$user->pay()`, then replace with `$user->wallet->pay()`

**Comment by imhuso** [comment]
`Customer` interface  remove it together?

**Comment by rez1dent3** [comment]
@imhuso Yes, it needs to be removed

**Comment by imhuso** [comment]
@rez1dent3 When I use the `HasWalletFloat` trait then it work

**Comment by rez1dent3** [comment]
@imhuso Made changes, will be released soon.

The model will have two traits.
https://github.com/bavix/laravel-wallet/commit/4bfedf8a16644a7f6a51c4b681456cf8da88b49a#diff-7801eb6c1e99b6063d7706e65ae2827e

Thanks for the information

**Comment by rez1dent3** [comment]
@imhuso 
The release is ready, you can update the package. Tag: 3.1.6
Here are the changes: https://github.com/bavix/laravel-wallet/compare/3.1.5...3.1.6

**Comment by imhuso** [comment]
@rez1dent3 ok thanks

**Comment by rez1dent3** [comment]
@imhuso There will be questions create a new issue
