### ISSUE TITLE
Help with swap package

### ISSUE THREAD

**Issue by rez1dent3** [bavix/laravel-wallet#872]
@rez1dent3 
Im trying to do wallet exchange have followed this steps from this link [Laravel Wallet Swap](https://bavix.github.io/laravel-wallet/#/laravel-wallet-swap) but it dosen't exchange the amount instead it just transfer the amount I entered. can you please help

Here is my code 
```public function quickTransfers()
    {
        $sender = User::findOrFail(12);
        $receiver = User::findOrFail(11);

        $s = $sender->getWallet($sender->tag);
        $r = $receiver->getWallet($receiver->tag);

        $s->exchange($r, 10);

        return $r->balance;
    }
 ```

`"bavix/laravel-wallet-swap": "^6.0",`
    
_Originally posted by @Peektower in https://github.com/bavix/laravel-wallet/issues/863#issuecomment-1912154724_

**Comment by rez1dent3** [comment]
@Peektower hello. Let's continue here.

**Comment by rez1dent3** [comment]
1. I don't understand what tag is. Can you describe your architecture?
2. The wallet must have the currency stamped on it.
a) Multi-wallets:
https://github.com/bavix/laravel-wallet/blob/febd97ba360bcde916ed3bd73961c75c743c88f7/tests/Units/Domain/ExchangeTest.php#L92-L98

b) default wallet:
```php
$wallet->meta['currency'] = 'USD';
$wallet->save();
```

**Comment by Peektower** [comment]
I’m using the tag to identify the user’s wallet

I’m using this trait HasWallets

So I want to exchange the amount based on the currency using the wallet
exchange method.
But when I do, the exact amount is transferred without the conversion

**Comment by rez1dent3** [comment]
You need to add the currency type to the meta and everything will start working.

**Comment by rez1dent3** [comment]
@Peektower Did you succeed? If not, then write. I'll make some detailed example.

**Comment by Peektower** [comment]
Using the exchange does work for me, so I’m opting to use external currency
conversion api

**Comment by rez1dent3** [comment]
@Peektower The laravel-wallet-swap package works on top of the https://github.com/florianv/laravel-swap package, so all package providers (api providers and more) are available to you.

https://github.com/florianv/laravel-swap?tab=readme-ov-file#services

**Comment by Peektower** [comment]
Hi again Maxim,
this is my response when i fetch the transactions

{
"id": 2,
"user": 1,
"type": "withdraw",
"amount": "-22",
"meta": "For lunch"
},


so the challenges here now is how can i know the sender or receiver of the
transactions

**Comment by rez1dent3** [comment]
@Peektower Hello.
The transaction does not have a sender, the transfer does.

Example:
https://github.com/bavix/laravel-wallet/blob/addf96927d0f2d257db20fdbbf24767d365d6470/tests/Units/Domain/EagerLoadingTest.php#L61-L69

And from the wallet you can get the owner of the wallet.
