### ISSUE TITLE
Events are not dispatching

### ISSUE THREAD

**Issue by GeorgeInteli** [bavix/laravel-wallet#903]
**Describe the bug**
The events from the package are not dispatching.

**To Reproduce**
1. Create user with wallet
2. Deposit amount on wallet
3. Expect to receive Balance Updated event
4. No event received

**Expected behavior**
After a deposit I expect to receive event on Balance change and Transaction created.

**Screenshots**
Here is sample test
![image](https://github.com/bavix/laravel-wallet/assets/63303469/fb32ad29-93c6-4708-9707-cdd678f53da9)

**Server:**
 - php version: 8.3
 - database: mysql 8.0
 - wallet version 10
 - cache lock: array
 - cache wallets: array

**Comment by rez1dent3** [comment]
@GeorgeInteli Hello. All events are sent when a transaction is committed. Add a check to your transaction level test, it must be 0 for the event to be sent.

I'm sure the test will fail, because... pest starts a transaction before the test starts and ends it after the test ends.

You need to call commit yourself before checking.

**Comment by GeorgeInteli** [comment]
Hello @rez1dent3 , I can confirm that even on transaction level 0 the events are **not** dispaching.
It was level 1 inside pest, it is going to level 0 after commit, but the test still fails. The most confusing thing about all this is that `balanceInt` is actually being updated, but the event is not fired.

Note that even if the events did fire i dont think reverting or commiting something outside the scope of the function is a solution. I am sure this was discussed before. Any best practices or solutions you might recommend? And what is the reasoning behind transaction level 0. I see it hard coded inside `TransactionCommittedListener.php` (i read #412 and #455)

**Comment by rez1dent3** [comment]
> And what is the reasoning behind transaction level 0

The transaction can be canceled and the event sent.

**Comment by rez1dent3** [comment]
I checked locally again. Events are sent. Need more data.

**Comment by rez1dent3** [comment]
@GeorgeInteli I didn't notice at first, but you're testing the implementation, not the interface. You need to check the contract itself, the trigger for it.

**Comment by GeorgeInteli** [comment]
![image](https://github.com/bavix/laravel-wallet/assets/63303469/7c2cb4d2-5db9-4dd9-bf04-1f20563307aa)

Hmmm i got nothing. Not seeing the event at all inside the dispatcher events stack. 

I am seeing however our own Laravel defined events. There is something specific to this package events.

**Comment by rez1dent3** [comment]
As I already wrote above, you need to determine the listener.

**Comment by rez1dent3** [comment]
@GeorgeInteli Hello. I took some time and started debugging. The flush method is not implemented for Fake in laravel. You will not be able to implement your check.

https://github.com/laravel/framework/blob/0525a8819db53bc66c878413829a4368d63c3d47/src/Illuminate/Support/Testing/Fakes/EventFake.php#L278-L287

**Comment by GeorgeInteli** [comment]
Thank you @rez1dent3 
Now we know what the issue is :) We will just have incomplete test for the moment.

**Comment by rez1dent3** [comment]
@GeorgeInteli You can use it in a similar way to the tests in the package itself. Those,
- refuse Events::fake
- register listeners
- throw errors at the listeners as a sign that the listener has worked

this will give you the ability to write tests.

Look at the tests in the project:
https://github.com/bavix/laravel-wallet/blob/master/tests/Units/Domain/EventTest.php
