### ISSUE TITLE
Error Interface 'Bavix\Wallet\Interfaces\ProductInterface' not found

### ISSUE THREAD

**Issue by amit-eps** [bavix/laravel-wallet#904]
I'm getting error Interface 'Bavix\Wallet\Interfaces\ProductInterface' not found

I'm using laravel version 8.83.27 and laravel-wallet version  "bavix/laravel-wallet": "7.*"

I've checked there is not ProductInterface file in this package in my project.
I'm getting same issue with ProductLimitedInterface
How can I fix this?

**Screenshots**
![image](https://github.com/bavix/laravel-wallet/assets/108069713/bdf49b51-bdee-435f-9408-064b6c6f4251)

![image](https://github.com/bavix/laravel-wallet/assets/108069713/ee769afe-dc3a-4b9d-a563-25626151995a)

**Server:**
 - php version: 7.4
 - database: mysql
 - wallet version 7.*

**Comment by rez1dent3** [comment]
Or like this:
```sh
php -S localhost:3000 -t ./vendor/bavix/laravel-wallet/docs
```
