### ISSUE TITLE
Too many arguments to function php ERROR for "$user = Auth::user();" to make deposit and withdraw on user connected balance

### ISSUE THREAD

**Issue by chegmarco1989** [bavix/laravel-wallet#932]
HELLO.

Using `$user = Auth::user();` because I want connected user to make deposit and withdraw, I see on my VS code, `$amount` (IN: `$user->deposit($amount)` AND `$user->withdraw($amount)`) underlines in **red** with **Too many arguments to function php** error.

So how to define in my case `$user` as user connected so that to allow that user connected to deposit and withdraw ???

Please answer me.

**Comment by rez1dent3** [comment]
Hello. The question is not related to the package. You need to study the phpdoc annotations:
https://docs.phpdoc.org/guide/references/phpdoc/tags/var.html

Example:
```php
/** @var User $user */
$user = Auth::user();
```
