### ISSUE TITLE
Deposit fee

### ISSUE THREAD

**Issue by ringkubd** [bavix/laravel-wallet#955]
How to set deposit fee?

**Comment by rez1dent3** [comment]
Hello. It is not possible to set a commission on a deposit. This functionality is not included in the package, but it is quite easy to implement it yourself.

If you have an interesting idea for implementation, then you can describe the idea in issue and I will think about it.

Thanks for the issue.

**Comment by rez1dent3** [comment]
The architectural solution looks bad in the package. At the moment, I don't plan to add. If there is a greater need in the community, I will return to this issue.

Thank you for your time and all the best.
