### ISSUE TITLE
How refund a id of transactions table or transfers table

### ISSUE THREAD

**Issue by khanhnam99** [bavix/laravel-wallet#98]
in transactions table

How refund a id of transactions table 

![Capture](https://user-images.githubusercontent.com/575720/63850316-f650c080-c9bd-11e9-97c7-90e05cb53907.PNG)

**Comment by rez1dent3** [comment]
@khanhnam99 
I do not understand. I need more information.

**Comment by khanhnam99** [comment]
wallet_id  = 712 from wallets table , there column balance = 900
when deposit = 100 , insert to transactions table , amount = 100
at this time wallet_id  = 712 , there column balance = 1000
-------------------------------------------------------------------------------

Now : 
look at transactions table, id = 1 ,
i would like to refund a id=1 of transactions table
after to finished , wallet_id  = 712 from wallets table , there column balance = 900

**Comment by rez1dent3** [comment]
@khanhnam99 
Describe what you need, I do not understand what you want.

**Comment by rez1dent3** [comment]
I close the issue, as I understand it, the question is no longer relevant
