### ISSUE TITLE
Check balance issue

### ISSUE THREAD

**Issue by Basheer21** [bavix/laravel-wallet#984]
The balance attribute in the modelInstance is returning 0 when accessed via modelInstance->balance, even though querying the associated Wallet model directly returns the correct balance

**To Reproduce**
1. create a wallet for the modelInstance
ex:
                $business->createWallet([
                    'name' => $business->name . ' Wallet',
                    'slug' => 'business-wallet',
                ]);
2. make deposit $business->getWallet('business-wallet')->deposit(100000); // pls note if i do $business->deposit(100000); without specifying the walletName its gonna create another wallet

3. check balance:     $business->balance will retrieve 0 while if I check the balance using the wallet Model will bring the correct balance 
ex/ $wallet = Wallet::where('holder_id', 2)->get();

**Expected behavior**
$business->balance : should retrieve the correct balance

**Comment by rez1dent3** [comment]
Hello.

> $business->balance : should retrieve the correct balance

This is an appeal to the default wallet, and you are replenishing a multi-wallet.

If you want to get his balance, the code should be like this:

```php
$business->getWallet('business-wallet')->balance;
```

**Comment by rez1dent3** [comment]
Multi-wallets: https://bavix.github.io/laravel-wallet/guide/multi/new-wallet.html#how-to-get-the-right-wallet

Single wallet: https://bavix.github.io/laravel-wallet/guide/single/deposit.html#make-a-deposit

**Comment by rez1dent3** [comment]
If you need multi-wallets and do not need the default wallet, then disable it leaving only the `HasWallets` trait.

That is, remove HasWalletFloat or HasWallet.

**Comment by Basheer21** [comment]
Thanks a lot for your fast support.
