### ISSUE TITLE
How to eager load wallets with transactions?

### ISSUE THREAD

**Issue by ISNewton** [bavix/laravel-wallet#986]
**Describe the bug**
I need to eager load user wallets with their transactions :
```
        $students = Student::query()
            ->with('wallets.transactions')
            ->get();
```

I get the follwing error :
```
  TypeError: Bavix\Wallet\Services\CastService::getModel(): Argument #1 ($object) must be of type object, null given, called in /my_project_path/vendor/bavix/laravel-wallet/src/Services/CastService.php on line 55 and defined in /my_project_path/vendor/bavix/laravel-wallet/src/Services/CastService.php:58
```

**Trace Error**
```
  Stack trace:
  #0 /my_project_path/vendor/bavix/laravel-wallet/src/Services/CastService.php(55): Bavix\Wallet\Services\CastService->getModel()
  #1 /my_project_path/vendor/bavix/laravel-wallet/src/Traits/HasWallet.php(114): Bavix\Wallet\Services\CastService->getHolder()
  #2 /my_project_path/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(690): Bavix\Wallet\Models\Wallet->transactions()
  #3/my_project_path/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(106): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
```

**Server:**
 - php version: 8.3
 - database: mysql 8.0
 - wallet version 7.3.6

**Comment by rez1dent3** [comment]
Hello. `transactions` returns all transactions of all wallets. You need to use `walletTransactions`.

```diff
        $students = Student::query()
-           ->with('wallets.transactions')
+           ->with('wallets.walletTransactions')
            ->get();
```

And for wallets, refer to the walletTransactions connection.

**Comment by rez1dent3** [comment]
If you need all transactions of all wallets, then use `transactions`.

```
        $students = Student::query()
            ->with('transactions')
            ->get();
```

**Comment by ISNewton** [comment]
I updated the code to :
```
        $students = Student::query()
            ->with(['wallets.walletTransactions'])
            ->get();

```

 I got this error :
```
  TypeError: Bavix\Wallet\Internal\Events\WalletCreatedEvent::__construct(): Argument #1 ($holderType) must be of type string, null given, called in /my_project_path/vendor/bavix/laravel-wallet/src/Internal/Assembler/WalletCreatedEventAssembler.php on line 23 and defined in /my_project_path/vendor/bavix/laravel-wallet/src/Internal/Events/WalletCreatedEvent.php:17
```


I believe it is related to this issue: https://github.com/bavix/laravel-wallet/issues/613#issuecomment-1339657093

**Comment by rez1dent3** [comment]
> I believe it is related to this issue: https://github.com/bavix/laravel-wallet/issues/613#issuecomment-1339657093

The problems are a little different.

> I got this error :

You need to update to at least laravel-wallet 10.0+ for this to work. Unfortunately, this won't work on versions below 10. I had to change the internal structure of the project very much.

Proof: https://github.com/bavix/laravel-wallet/commit/c6583a76050e7c48dad4da927d392083a1cb4a33
You can run this test locally.

Version 7.x has not been supported for almost two years.

![screen](https://github.com/user-attachments/assets/3d306b17-617b-475c-98a7-764fd471154a)

**Comment by ISNewton** [comment]
Thanks @rez1dent3 .

**Comment by ISNewton** [comment]
Thanks @rez1dent3 .
