### ISSUE TITLE
Cannot use HasWallet and CanPay together on the same model

### ISSUE THREAD

**Issue by abishekrsrikaanth** [bavix/laravel-wallet#99]
Hi,

Just started using the package. I added the traits `HasWallet` and `CanPay` to the User Model and I get the following error

```
Trait method deposit has not been applied, because there are collisions with other trait methods on App\\Shared\\Models\\User at /Users/app-server/vendor/coolAppName/shared/src/Models/User.php:15
```

Can I not use both the traits together?

**Comment by rez1dent3** [comment]
Hello.
@abishekrsrikaanth `CanPay` already has `HasWallet`.

**Comment by rez1dent3** [comment]
Those, you just have to add `CanPay`.

**Comment by abishekrsrikaanth** [comment]
Thanks, that helps. Would be worth mentioning it in the wallet with a few examples.. 
Thanks for the quick support.

**Comment by rez1dent3** [comment]
@abishekrsrikaanth Yes, I should. Thanks you.
I will leave issue open until I add it to the documentation.

**Comment by emad-sure** [comment]
@rez1dent3 

First thanks for you laravel wallet plugin it's really awesome and helpful i just have some mis-understanding in some logic  . 
for my case : 
1- i have a hotel and this hotel have some units where i can book for customers  . 
2- i book the unit that means Reservation Model using trait Has HasWalletFloat
3- then i save the reservation in reservations table and in transactions table in the first status it become a withdraw . so in transactions table i have the morph relation with payable_type ( App\Reservation ) and payable_id ( the reservation id ) . 
4- for now everything is working for me like a charm , but the issue am facing right now  . 
5- sometimes i want to add a transaction which is not related to any reservation ( ex: transaction made to plumber ) it's already a withdraw transaction but is not related to any reservation . 
6- hopfully i have Team Model ( yeah am using spark ) how do i achieve something like i described in ( 5 ) that's my question 

Thanks for your time reading this

**Comment by rez1dent3** [comment]
Updated the documentation. Thanks you
