### ISSUE TITLE
Timeout on BigDecimal operation

### ISSUE THREAD

**Issue by sinamiandashti** [bavix/laravel-wallet#991]
**Describe your task**
Hello

I got the following error (sometimes) during withdraw money on wallets
```Maximum execution time of 30 seconds exceeded {"userId":5806,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/panel/vendor/bavix/laravel-wallet/src/Internal/Service/MathService.php:17)
```

**To Reproduce**
not really reproducable (happening sometimes)

**Trace Error**
Maximum execution time of 30 seconds exceeded {"userId":5806,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/panel/vendor/bavix/laravel-wallet/src/Internal/Service/MathService.php:17)

**Expected behavior**
no timeout

**Screenshots**

**Server:**
 - php version: 8.2
 - database: [e.g mysql 8.0]
 - wallet version [e.g. 8.2]
 - cache lock: [e.g. redis]
 - cache wallets: [e.g. redis]

**Additional context**

does this means that we need to put this operation in a laravel job to be async and no timeout?

**Comment by rez1dent3** [comment]
@sinamiandashti Hello. Without a stack trace it's hard to say. Math operations are fast, very fast, and can be sped up by installing bcmath.
