### ISSUE TITLE
Zero wallet balance when querying the wallet with Query Builder

### ISSUE THREAD

**Issue by ISNewton** [bavix/laravel-wallet#993]
**Describe the bug**
When using the Laravel Query Builder I get the balance as 0 , But when I switch to Laravel Eloquent ORM I get the correct balance 5000.
```
        $student = User::find(1);

        $wallet = $student->createWallet([
            'name' => 'Student wallet',
            'slug' => 'MyUniqueSlug',
            'meta' => ['is_active' => true]
        ]);

        $wallet->deposit(5000);

```
Now this query will return the correct wallet but with the balance 0:
```
        $students = DB::table('users')
            ->join('wallets', function ($join){
                $join->on('wallets.holder_id', 'users.id')
                    ->where('wallets.holder_type', User::class)
                    ->where('wallets.slug', 'MyUniqueSlug');
                ;
            })
```
But this query will return the correct wallet with the correct balance 5000
```
        $students = Student::query()
            ->withWhere('wallets', function ($query) {
                $query->where('wallets.slug' , 'MyUniqueSlug',);
            })
            ->get();

```

I can confirm that the transactions was created.

**To Reproduce**
1. Create a user wallet
2. Deposit 5000
3. Query the wallet  with both ORM and  Query Builder
4. You should see different balances.

**Server:**
 - php version: 8.3
 - database: 8.0.3
 - wallet version 10.1.6

**Comment by rez1dent3** [comment]
Hello. I can't reproduce it, but I'll try again a little later.

<img width="790" alt="Screenshot 2024-09-11 at 18 38 20" src="https://github.com/user-attachments/assets/080652a8-75d2-4c83-b136-835ed16e3004">

```php
/** @var \App\Models\User $student */
$student = \App\Models\User::find(1);

$wallet = $student->createWallet([
    'name' => 'Student wallet',
    'slug' => 'MyUniqueSlug',
    'meta' => ['is_active' => true]
]);

$wallet->deposit(5000);

$students = DB::table('users')
    ->join('wallets', function ($join){
        $join->on('wallets.holder_id', 'users.id')
            ->where('wallets.holder_type', \App\Models\User::class)
            ->where('wallets.slug', 'MyUniqueSlug');
        ;
    });

dd($students->get());
```

**Comment by rez1dent3** [comment]
Hmm. Do you have an open transaction? The balance is updated before committing to the database.

That is, you technically will not be able to get a new balance inside the transaction in the database, because it does not exist yet.

This is done as part of optimization:
https://github.com/bavix/laravel-wallet/pull/589
https://github.com/bavix/laravel-wallet/discussions/562

**Comment by rez1dent3** [comment]
Is this normal?

<img width="715" alt="Screenshot 2024-09-11 at 22 06 37" src="https://github.com/user-attachments/assets/947ef51b-9413-466a-9973-7d83e128f8af">

**Comment by rez1dent3** [comment]
I've been looking and debugging for a long time. I don't see a bug. At the moment I've removed the "bug" tag until a detailed case from your side.

**Comment by ISNewton** [comment]
I was running the code inside a PHPUnit test class that uses the `DatabaseTruncation` trait .
Thanks again @rez1dent3  .

**Comment by rez1dent3** [comment]
This event makes a query to update the balance in the wallet table. If you do DB::commit() before your query, the data will be up-to-date.

https://github.com/bavix/laravel-wallet/blob/22056dde8f998cdc2adb5030fcdd520ff6c14ef7/src/Internal/Listeners/TransactionCommittingListener.php#L28-L37

**Comment by rez1dent3** [comment]
Inside the committing method:
https://github.com/bavix/laravel-wallet/blob/22056dde8f998cdc2adb5030fcdd520ff6c14ef7/src/Services/RegulatorService.php#L114

**Comment by rez1dent3** [comment]
In general, the functionality appeared in the framework only for the sake of our project.

https://github.com/laravel/framework/pull/44608/files
